Repository chainer/chainer, pull requests merged in 2018-11, with the labels that each got.

#5602 extensions guide: method to implement is __call__
  docs/source/guides/extensions.rst
Labels: document, to-be-backported

#5285 Add `F.roi_average_pooling_2d`
  chainer/functions/__init__.py
  chainer/functions/pooling/roi_average_pooling_2d.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_pooling_2d.py
Labels: domain:cv, feature

#5605 [backport] extensions guide: method to implement is __call__
  docs/source/guides/extensions.rst
Labels: backport, document

#5509 Unify implementations on computing size from shape
  chainer/functions/activation/softmax.py
  chainer/functions/array/pad_sequence.py
  chainer/functions/array/repeat.py
  chainer/functions/connection/linear.py
  chainer/functions/normalization/batch_normalization.py
  chainer/initializer.py
  chainer/initializers/orthogonal.py
  chainer/links/connection/linear.py
  chainer/links/connection/lstm.py
  chainer/links/normalization/layer_normalization.py
  chainer/testing/distribution_test.py
  chainer/utils/__init__.py
  chainer/utils/array.py
  tests/chainer_tests/utils_tests/test_array.py
Labels: enhancement, st:test-and-merge

#5611 Fix #5285
  chainer/functions/pooling/roi_average_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_pooling_2d.py
Labels: bug

#4824 Implement double backward of SLSTM function
  chainer/functions/activation/slstm.py
  tests/chainer_tests/functions_tests/activation_tests/test_slstm.py
Labels: feature

#5609 update roi_average_align_2d doc to refer roi_average_pooling_2d
  chainer/functions/pooling/roi_average_align_2d.py
Labels: document, to-be-backported

#5604 Fix `D.OneHotCategorical`
  chainer/distributions/one_hot_categorical.py
  tests/chainer_tests/distributions_tests/test_one_hot_categorical.py
Labels: bug, st:test-and-merge

#5532 Require setuptools and add docs for #5425
  docs/source/upgrade.rst
  setup.py
Labels: install, st:test-and-merge

#5613 Fix `F.negative_sampling` output dtype in CPU mode
  chainer/functions/loss/negative_sampling.py
  tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
Labels: bug, st:test-and-merge, to-be-backported

#5547 Avoid unnecessary copy in `ndarray.astype`
  chainer/functions/array/resize_images.py
  chainer/functions/array/spatial_transformer_sampler.py
  chainer/functions/connection/linear.py
  chainer/functions/evaluation/classification_summary.py
  chainer/functions/evaluation/r2_score.py
  chainer/functions/loss/ctc.py
  chainer/functions/math/basic_math.py
  chainer/functions/math/fft.py
  chainer/testing/unary_math_function_test.py
Labels: enhancement, to-be-backported

#5617 [backport] Update `F.roi_average_align_2d` doc to refer wrapper function
  chainer/functions/pooling/roi_average_align_2d.py
Labels: backport, document

#5304 Add `F.roi_max_pooling_2d`
  chainer/functions/__init__.py
  chainer/functions/pooling/roi_max_pooling_2d.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_pooling_2d.py
Labels: domain:cv, feature, st:test-and-merge

#5623 [backport] Avoid unnecessary copy in `ndarray.astype`
  chainer/functions/array/resize_images.py
  chainer/functions/array/spatial_transformer_sampler.py
  chainer/functions/connection/linear.py
  chainer/functions/evaluation/classification_summary.py
  chainer/functions/evaluation/r2_score.py
  chainer/functions/loss/ctc.py
  chainer/functions/math/fft.py
  chainer/testing/unary_math_function_test.py
Labels: backport, enhancement

#5625 [backport] Fix `F.negative_sampling` output dtype in CPU mode
  chainer/functions/loss/negative_sampling.py
  tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
Labels: backport, bug, st:test-and-merge

#5627 fix args check in roi_average_align_2d.py and roi_average_pooling_2d.py
  chainer/functions/pooling/roi_average_align_2d.py
  chainer/functions/pooling/roi_average_pooling_2d.py
Labels: bug

#5021 Update installation guide of numpy with openblas on macOS
  chainer/_environment_check.py
  docs/source/tips.rst
Labels: document, to-be-backported

#5198 add roi_max_align_2d
  chainer/functions/__init__.py
  chainer/functions/pooling/roi_max_align_2d.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_align_2d.py
Labels: domain:cv

#5567 Simplify pooling with cuDNN
  chainer/functions/pooling/average_pooling_2d.py
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/pooling/max_pooling_2d.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/pooling_2d.py
  chainer/functions/pooling/pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
Labels: enhancement, st:test-and-merge, to-be-backported

#5587 Add KL divergence test for D.OneHotCategorical
  chainer/distributions/one_hot_categorical.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: enhancement

#5630 [backport] Update installation guide of numpy with openblas on macOS
  chainer/_environment_check.py
  docs/source/tips.rst
Labels: backport, document

#5633 Import testing/backend.py definitions in testing/__init__.py
  chainer/testing/__init__.py
Labels: enhancement, to-be-backported

#5639 [backport] Import testing/backend.py definitions in testing/__init__.py
  chainer/testing/__init__.py
Labels: backport, enhancement, st:test-and-merge

#5563 Avoid cuDNN handle around DropoutStates
  chainer/backends/cuda.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/noise/dropout.py
Labels: enhancement, st:test-and-merge, to-be-backported

#5591 Fix text_classification example fails on Python 3 (#5590)
  examples/text_classification/text_datasets.py
Labels: bug, to-be-backported

#5653 Fix typo of example code in Chain docstring
  chainer/link.py
Labels: document, to-be-backported

#5654 Fix typo in `F.max_pooling_nd` docstring
  chainer/functions/pooling/max_pooling_nd.py
Labels: document, to-be-backported

#5655 [backport] Fix typo of example code in Chain docstring
  chainer/link.py
Labels: backport, document

#5658 Fix a typo in the document of chainer.distributions
  chainer/distribution.py
Labels: document, to-be-backported

#5661 [backport] Fix a typo in the document of chainer.distributions
  chainer/distribution.py
Labels: backport, document

#5624 Support all float dtypes in `F.embed_id`
  chainer/functions/connection/embed_id.py
  tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
Labels: feature

#5665 Fix typo in resnet
  chainer/links/model/vision/resnet.py
Labels: document, to-be-backported

#5644 [backport] Avoid cuDNN handle around DropoutStates
  chainer/backends/cuda.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/noise/dropout.py
Labels: backport, enhancement, st:test-and-merge

#5618 Fix test of `F.rrelu`
  chainer/functions/activation/rrelu.py
  tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
Labels: test, to-be-backported

#5525 Use `cupy.linalg.det` in `F.det`
  chainer/functions/math/det.py
Labels: enhancement

#5667 [backport] Fix typo in `L.ResNetLayers`
  chainer/links/model/vision/resnet.py
Labels: backport, document

#5338 add `D.Chisquare`
  chainer/distributions/__init__.py
  chainer/distributions/chisquare.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_chisquare.py
Labels: feature

#5673 [backport] Fix test of `F.rrelu`
  chainer/functions/activation/rrelu.py
  tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
Labels: backport, test

#5676 Fix typo in docstrings
  chainer/exporters/caffe.py
  chainer/sequential.py
Labels: document, to-be-backported

#5352 add `D.Gumbel`
  chainer/distributions/__init__.py
  chainer/distributions/gumbel.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_gumbel.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: feature

#5679 [backport] Fix typo in docstrings
  chainer/exporters/caffe.py
  chainer/sequential.py
Labels: backport, document

#5677 [backport] Include ChainerCV doc
  docs/source/conf.py
  docs/source/reference/datasets.rst
  docs/source/reference/links.rst
Labels: backport, document

#5606 Overlap compute and transfer more
  chainer/dataset/convert.py
Labels: enhancement, to-be-backported

#5356 Rewrite the example of VAE using Chainer distributions
  examples/vae/net.py
  examples/vae/train_vae.py
  examples/vae/train_vae_custom_loop.py
Labels: example

#5680 Support all float dtypes in `F.connectionist_temporal_classification`
  chainer/functions/loss/ctc.py
  tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Labels: feature

#5662 Use automatic broadcasting instead of `F.repeat`
  chainer/distributions/multivariate_normal.py
  chainer/distributions/normal.py
Labels: enhancement, to-be-backported

#5637 [backport] Simplify pooling with cuDNN
  chainer/functions/pooling/average_pooling_2d.py
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/pooling/max_pooling_2d.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/pooling_2d.py
  chainer/functions/pooling/pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
Labels: backport, enhancement

#5657 More consistent use of Variable.array in codes under links
  chainer/links/activation/simplified_dropconnect.py
  chainer/links/activation/swish.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_2d.py
  chainer/links/connection/deconvolution_nd.py
  chainer/links/connection/deformable_convolution_2d.py
  chainer/links/connection/depthwise_convolution_2d.py
  chainer/links/connection/dilated_convolution_2d.py
  chainer/links/connection/embed_id.py
  chainer/links/connection/linear.py
  chainer/links/connection/local_convolution_2d.py
  chainer/links/connection/lstm.py
  chainer/links/connection/n_step_rnn.py
  chainer/links/connection/parameter.py
  chainer/links/connection/peephole.py
  chainer/links/connection/zoneoutlstm.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  chainer/links/normalization/group_normalization.py
  chainer/links/normalization/layer_normalization.py
  chainer/links/theano/theano_function.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4922 Add WaveNet example
  examples/wavenet/README.md
  examples/wavenet/generate.py
  examples/wavenet/modules.py
  examples/wavenet/net.py
  examples/wavenet/requirements.txt
  examples/wavenet/train.py
  examples/wavenet/utils.py
Labels: example

#5689 [backport] More consistent use of `Variable.array` in codes under links
  chainer/links/activation/simplified_dropconnect.py
  chainer/links/activation/swish.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_2d.py
  chainer/links/connection/deconvolution_nd.py
  chainer/links/connection/deformable_convolution_2d.py
  chainer/links/connection/depthwise_convolution_2d.py
  chainer/links/connection/dilated_convolution_2d.py
  chainer/links/connection/embed_id.py
  chainer/links/connection/linear.py
  chainer/links/connection/local_convolution_2d.py
  chainer/links/connection/lstm.py
  chainer/links/connection/n_step_rnn.py
  chainer/links/connection/parameter.py
  chainer/links/connection/peephole.py
  chainer/links/connection/zoneoutlstm.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  chainer/links/normalization/group_normalization.py
  chainer/links/normalization/layer_normalization.py
  chainer/links/theano/theano_function.py
Labels: backport, enhancement

#5691 Ignore h5py is warned by Python 3.7
  setup.cfg
Labels: test, to-be-backported

#5684 [backport] Overlap compute and transfer more
  chainer/dataset/convert.py
Labels: backport, enhancement

#5692 Fix docs for backprop_step
  chainer/_backprop_utils.py
Labels: document, st:test-and-merge, to-be-backported

#5660 Add documentation of `ndarray`
  chainer/functions/activation/clipped_relu.py
  docs/source/reference/functions.rst
  docs/source/reference/variable.rst
Labels: document, st:test-and-merge, to-be-backported

#4887 Simplify array type information fields in function documentation
  chainer/functions/activation/clipped_relu.py
Labels: document

#5648 Support default dtype in `L.BinaryHierarchicalSoftmax`
  chainer/links/loss/hierarchical_softmax.py
  tests/chainer_tests/links_tests/loss_tests/test_hierarchical_softmax.py
Labels: feature, to-be-backported

#5643 Update style check tools to the versions compatible with pycodestyle 2.4
  .travis.yml
  setup.cfg
  setup.py
Labels: other, to-be-backported

#5672 [backport] Simplify softmax with cuDNN
  chainer/functions/activation/log_softmax.py
  chainer/functions/activation/softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: backport, enhancement

#5698 Add gradient consistency checks in `numerical_grad`
  chainer/gradient_check.py
  tests/chainer_tests/test_gradient_check.py
Labels: enhancement, test, to-be-backported

#5610 Use chainer.utils.size_of_shape in ChainerMN
  chainermn/communicators/mpi_communicator_base.py
Labels: ChainerMN, enhancement

#5642 Fix regex of protobuf modules warned by Python 3.7
  setup.cfg
Labels: test, to-be-backported

#5708 [backport] Use automatic broadcasting instead of `F.repeat`
  chainer/distributions/multivariate_normal.py
  chainer/distributions/normal.py
Labels: backport, enhancement

#5710 [backport] Fix docs for backprop_step
  chainer/_backprop_utils.py
Labels: backport, document

#5694 [backport] Ignore h5py is warned by Python 3.7
  setup.cfg
Labels: backport, test

#5683 Fix BatchNormalization with lazy initialization fail on GPU #5682
  chainer/links/normalization/batch_normalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: bug, to-be-backported

#5704 [backport] Add documentation of `ndarray`
  chainer/functions/activation/clipped_relu.py
  docs/source/reference/functions.rst
  docs/source/reference/variable.rst
Labels: backport, document

#5717 Make docs in chainer.distribution* refer `ndarray`
  chainer/distribution.py
  chainer/distributions/bernoulli.py
  chainer/distributions/beta.py
  chainer/distributions/categorical.py
  chainer/distributions/chisquare.py
  chainer/distributions/dirichlet.py
  chainer/distributions/exponential.py
  chainer/distributions/gamma.py
  chainer/distributions/gumbel.py
  chainer/distributions/laplace.py
  chainer/distributions/log_normal.py
  chainer/distributions/multivariate_normal.py
  chainer/distributions/normal.py
  chainer/distributions/one_hot_categorical.py
  chainer/distributions/pareto.py
  chainer/distributions/poisson.py
  chainer/distributions/uniform.py
Labels: document, to-be-backported

#5715 [backport] Update style check tools to the versions compatible with pycodestyle 2.4
  .travis.yml
  setup.cfg
  setup.py
Labels: backport, other

#5705 [backport] Add gradient consistency checks in `numerical_grad`
  chainer/gradient_check.py
  tests/chainer_tests/test_gradient_check.py
Labels: backport, enhancement, test

#5720 modify image URL in README
  examples/chainermn/dcgan/README.md
Labels: ChainerMN

#5719 [backport] Make docs in chainer.distribution* refer `ndarray`
  chainer/distribution.py
  chainer/distributions/bernoulli.py
  chainer/distributions/beta.py
  chainer/distributions/categorical.py
  chainer/distributions/dirichlet.py
  chainer/distributions/laplace.py
  chainer/distributions/log_normal.py
  chainer/distributions/multivariate_normal.py
  chainer/distributions/normal.py
  chainer/distributions/uniform.py
Labels: backport, document

#5736 Change link.add_hook to return self
  chainer/link.py
  tests/chainer_tests/test_link_hook.py
Labels: enhancement, st:test-and-merge, to-be-backported
