Repository chainer/chainer, pull requests merged in 2018-03, with the labels that each got.

#3883 Add testing.patch which calls mock.patch with wraps argument
  chainer/testing/__init__.py
  chainer/testing/helper.py
  tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_relu.py
  tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py
  tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
  tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_pooling_nd_kernel.py
  tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
Labels: feature, st:test-and-merge, test

#4423 [backport] new style zoneout function
  chainer/functions/noise/zoneout.py
  tests/chainer_tests/functions_tests/noise_tests/test_zoneout.py
Labels: backport, feature, st:test-and-merge

#4188 add link to CuPy upgrade guide
  docs/source/upgrade.rst
Labels: document, to-be-backported

#4108 optimize rsqrt function with CuPy
  chainer/functions/math/sqrt.py
  tests/chainer_tests/functions_tests/math_tests/test_sqrt.py
Labels: enhancement

#3996 add warning for batch normalization when batchsize=1 and train=True
  chainer/functions/normalization/batch_normalization.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4432 chmod 644 *.py
  chainer/functions/connection/shift.py
  chainer/optimizers/adam.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4417 Add n_cell property to NStepRNN family
  chainer/links/connection/n_step_gru.py
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
  tests/chainer_tests/links_tests/connection_tests/test_n_step_gru.py
  tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py
  tests/chainer_tests/links_tests/connection_tests/test_n_step_rnn.py
Labels: feature

#4355 Extract a function that concatenates weight and bias matrixes for cuDNN
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: enhancement

#4433 [backport] add warning for batch normalization when batchsize=1 and train=True
  chainer/functions/normalization/batch_normalization.py
Labels: backport, enhancement

#4428 Fix docs format in upgrade guide
  docs/source/upgrade_v2.rst
Labels: document, st:test-and-merge, to-be-backported

#4434 Typecheck split_at
  chainer/datasets/sub_dataset.py
  tests/chainer_tests/datasets_tests/test_sub_dataset.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4437 fix Evaluator.device docs
  chainer/training/extensions/evaluator.py
Labels: document, st:test-and-merge, to-be-backported

#4436 reset Link._device_id to None in to_intel64
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: bug, st:test-and-merge

#4438 add ChainerUI link to comparison table
  docs/source/comparison.rst
Labels: document, st:test-and-merge, to-be-backported

#4439 [backport] Update comparison.rst (Web interface)
  docs/source/comparison.rst
Labels: backport, document, st:test-and-merge

#4440 [backport] Fix docs format in upgrade guide
  docs/source/upgrade_v2.rst
Labels: backport, document

#4445 [backport] add ChainerUI link to comparison table
  docs/source/comparison.rst
Labels: backport, document, st:test-and-merge

#4442 [backport] fix Evaluator.device docs
  chainer/training/extensions/evaluator.py
Labels: backport, document, st:test-and-merge

#4446 fix underline in docs
  docs/source/guides/extensions.rst
Labels: document, to-be-backported

#4430 Extract stack function from CTC loss
  chainer/functions/loss/ctc.py
  tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Labels: enhancement

#3977 Create `chainer.optimizer_hooks` namespace and move hooks there.
  chainer/optimizer.py
  chainer/optimizer_hooks/__init__.py
  chainer/optimizer_hooks/gradient_clipping.py
  chainer/optimizer_hooks/gradient_hard_clipping.py
  chainer/optimizer_hooks/gradient_noise.py
  chainer/optimizer_hooks/lasso.py
  chainer/optimizer_hooks/weight_decay.py
  docs/source/guides/optimizers.rst
  docs/source/reference/index.rst
  docs/source/reference/optimizer_hooks.rst
  examples/cifar/train_cifar.py
  examples/dcgan/train_dcgan.py
  examples/ptb/train_ptb.py
  examples/sentiment/train_sentiment.py
  setup.py
  tests/chainer_tests/optimizer_hooks_tests/test_gradient_clipping.py
  tests/chainer_tests/optimizer_hooks_tests/test_gradient_hard_clipping.py
  tests/chainer_tests/optimizer_hooks_tests/test_gradient_noise.py
  tests/chainer_tests/optimizer_hooks_tests/test_lasso.py
  tests/chainer_tests/optimizer_hooks_tests/test_weight_decay.py
  tests/chainer_tests/test_optimizer.py
Labels: enhancement, reviewer-team, st:awaiting-response

#4127 Added ZippedImageDataset and MultiZippedImageDataset
  chainer/datasets/__init__.py
  chainer/datasets/image_dataset.py
  tests/chainer_tests/datasets_tests/image_dataset/zipped_images_1.zip
  tests/chainer_tests/datasets_tests/image_dataset/zipped_images_2.zip
  tests/chainer_tests/datasets_tests/test_image_dataset.py
Labels: feature, st:awaiting-response, st:test-and-merge

#4451 add license to source distribution
  MANIFEST.in
Labels: other, to-be-backported

#4444 [backport] updated english for extension documentation
  docs/source/tutorial/extension.rst
Labels: backport, document, enhancement, st:test-and-merge

#3809 Improve extensions part in trainer tutorial
  docs/source/examples/mnist.rst
Labels: document, enhancement, to-be-backported

#4452 [backport] add license to source distribution
  MANIFEST.in
Labels: backport, other, st:test-and-merge

#4435 Remove future.types.newint
  chainer/backends/cuda.py
Labels: enhancement

#4328 Refactor F.split_axis
  chainer/functions/array/split_axis.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: enhancement, st:awaiting-response

#4447 Accelerate multi-add for intel64 backend
  chainer/functions/math/basic_math.py
  tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
Labels: enhancement

#4462 [backport] add link to CuPy upgrade guide
  docs/source/upgrade.rst
Labels: backport, document, st:test-and-merge

#4464 Fix trainer docs
  docs/source/reference/index.rst
  docs/source/reference/training.rst
  docs/source/reference/triggers.rst
Labels: document

#4457 Fix to disable using iDeep in optimizers if to_intel64 is not called
  chainer/optimizers/momentum_sgd.py
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: bug

#3662 document missing environment variables
  docs/source/reference/configuration.rst
Labels: document, st:test-and-merge

#4025 Add alias for conv1d and conv3d
  chainer/functions/__init__.py
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_nd.py
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/unpooling_nd.py
  chainer/links/__init__.py
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_nd.py
  docs/source/reference/functions.rst
  docs/source/reference/links.rst
Labels: feature, st:test-and-merge

#4466 Fix to use CUDNN_BN_MIN_EPSILON
  chainer/functions/normalization/batch_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Labels: enhancement, st:test-and-merge

#4312 Improve error messages of array type check.
  chainer/function_node.py
  docs/source/upgrade.rst
  tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
  tests/chainer_tests/test_function_node.py
Labels: enhancement, st:awaiting-response

#4465 [backport] document missing environment variables
  docs/source/reference/core/configuration.rst
  docs/source/reference/environment.rst
Labels: backport, document

#4471 Deprecate `sep` argument of `PrintHook`
  chainer/function_hooks/debug_print.py
Labels: enhancement, st:test-and-merge

#4474 fix typo of configuration parameter
  docs/source/reference/configuration.rst
Labels: document

#4164 Add explanation to the document of concat_examples
  chainer/dataset/convert.py
Labels: document

#4483 Reduce UserWarning
  tests/chainer_tests/test_optimizer.py
  tests/chainer_tests/training_tests/triggers_tests/test_interval_trigger.py
  tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: test

#4485 fix doctest failure in chainer.dataset.concat_examples
  chainer/dataset/convert.py
Labels: test

#3782 Delegate cuDNN convolution operation to CuPy
  chainer/backends/cuda.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/deconvolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py
  tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py
  tests/chainer_tests/test_cuda.py
Labels: enhancement, to-be-backported

#4425 Fix document in NStepLSTM/GRU/RNN
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
Labels: document

#4486 Fix sectioning of "Datasets" reference
  docs/source/reference/datasets.rst
Labels: document

#4490 [backport] Fix document in NStepLSTM/GRU/RNN
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
Labels: backport, document

#4476 add Dockerfiles for Chainer with iDeep
  docker/intel/README.md
  docker/intel/python2/Dockerfile
  docker/intel/python3/Dockerfile
Labels: install

#4152 [RFC]Fix progress bar
  chainer/training/extensions/progress_bar.py
Labels: enhancement

#4488 fix for optimizer hook namespace change
  docs/source/reference/index.rst
  docs/source/reference/optimizer_hooks.rst
  docs/source/reference/optimizers.rst
Labels: document

#4153 Fix to make it consistent with numpy.split and cupy.split
  chainer/functions/array/split_axis.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: bug, st:awaiting-response, to-be-backported

#4494 fix typo in comment of UpdateRule
  chainer/optimizer.py
Labels: document

#4500 avoid running TestSplitAxis tests on NumPy 1.10
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: test

#4505 Remove eps from batch normalization statistics
  chainer/functions/normalization/batch_normalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: bug, to-be-backported

#4503 Travis test against v4 branch
  .travis.yml
Labels: test, to-be-backported

#4495 document arithmetic special functions
  docs/source/_templates/autosummary/class.rst
Labels: document, to-be-backported

#4496 let stalebot ignore issues labelled with roadmap
  .github/stale.yml
Labels: other, to-be-backported

#4515 [backport] document arithmetic special functions
  docs/source/_templates/autosummary/class.rst
Labels: backport, document, st:test-and-merge

#3101 Add count_params method to Link
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: feature

#4477 add document on using iDeep
  docs/source/install.rst
  docs/source/tips.rst
Labels: document, st:test-and-merge, to-be-backported

#4506 Fix doctest
  chainer/dataset/convert.py
Labels: st:test-and-merge, test, to-be-backported

#4222 End-to-end memory networks example
  examples/memnn/README.md
  examples/memnn/babi.py
  examples/memnn/download.py
  examples/memnn/memnn.py
  examples/memnn/test_memnn.py
  examples/memnn/train_memnn.py
Labels: example

#4309 Improve docstring of CTC
  chainer/functions/loss/ctc.py
Labels: document

#3792 New style forget
  chainer/functions/util/forget.py
  tests/chainer_tests/functions_tests/util_tests/test_forget.py
Labels: feature

#4461 Save snapshot in the OS default permission
  chainer/training/extensions/_snapshot.py
  tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
Labels: bug

#4493 Fix order of items in Reference section
  docs/source/reference/index.rst
Labels: document, st:test-and-merge, to-be-backported

#4516 improve docs for supported operators in Variable
  chainer/variable.py
Labels: document, to-be-backported

#4527 [backport] improve docs for supported operators in Variable
  chainer/variable.py
Labels: backport, document

#4521 [backport] Fix doctest
  chainer/dataset/convert.py
Labels: backport, st:test-and-merge, test

#4526 [backport] Fix order of items in Reference section
  docs/source/reference/index.rst
Labels: backport, document

#4518 [backport] Travis test against v4 branch
  .travis.yml
Labels: backport, st:test-and-merge, test

#4378 Optimize imports for PyCharm code completion
  chainer/__init__.py
  chainer/dataset/__init__.py
  chainer/datasets/__init__.py
  chainer/function_hooks/__init__.py
  chainer/functions/__init__.py
  chainer/initializers/__init__.py
  chainer/iterators/__init__.py
  chainer/links/caffe/__init__.py
  chainer/optimizers/__init__.py
  chainer/serializers/__init__.py
  chainer/testing/__init__.py
  chainer/training/__init__.py
  chainer/training/extensions/__init__.py
  chainer/training/trigger.py
  chainer/training/triggers/__init__.py
  chainer/training/updaters/__init__.py
  chainer/utils/__init__.py
  docs/source/conf.py
Labels: enhancement, st:test-and-merge

#4522 [backport] New style forget
  chainer/functions/util/forget.py
  tests/chainer_tests/functions_tests/util_tests/test_forget.py
Labels: backport, feature

#4519 [backport] fix debug mode documentation
  chainer/__init__.py
  docs/source/reference/debug.rst
Labels: backport, document, st:test-and-merge

#4520 [backport] add document on using iDeep
  docs/source/install.rst
  docs/source/tips.rst
Labels: backport, document, st:test-and-merge

#4524 [backport] Save snapshot in the OS default permission
  chainer/training/extensions/_snapshot.py
  tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
Labels: backport, bug, st:test-and-merge

#4531 [backport] Improve docstring of CTC
  chainer/functions/loss/ctc.py
Labels: backport, document

#4529 [backport] Support deserializing into array of different dtype
  chainer/serializers/hdf5.py
  chainer/serializers/npz.py
  tests/chainer_tests/serializers_tests/test_hdf5.py
  tests/chainer_tests/serializers_tests/test_npz.py
Labels: backport, enhancement

#4532 use --no-cache-dir in Dockerfile
  docker/intel/python2/Dockerfile
  docker/intel/python3/Dockerfile
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: install, to-be-backported

#4535 [backport] use --no-cache-dir in Dockerfile
  docker/intel/python2/Dockerfile
  docker/intel/python3/Dockerfile
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: backport, install, st:test-and-merge

#4517 [backport] Remove eps from batch normalization statistics
  chainer/functions/normalization/batch_normalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: backport, bug

#4497 Implement Variable.xp
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: feature, to-be-backported

#4536 [backport] Implement Variable.xp
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: backport, feature

#4537 Support dilated convolution on ideep backend
  chainer/functions/connection/deconvolution_2d.py
Labels: enhancement, to-be-backported

#4470 Avoid use of `from __future__ print_function`
  chainer/configuration.py
  chainer/dataset/download.py
  chainer/function_hooks/debug_print.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  chainer/training/trainer.py
  examples/cifar/models/VGG.py
  examples/cifar/train_cifar.py
  examples/cifar/train_cifar_custom_loop.py
  examples/dcgan/net.py
  examples/dcgan/train_dcgan.py
  examples/dcgan/updater.py
  examples/imagenet/train_imagenet.py
  examples/imagenet/train_imagenet_data_parallel.py
  examples/mnist/train_mnist.py
  examples/mnist/train_mnist_custom_loop.py
  examples/mnist/train_mnist_data_parallel.py
  examples/mnist/train_mnist_model_parallel.py
  examples/modelzoo/download_mean_file.py
  examples/modelzoo/download_model.py
  examples/modelzoo/evaluate_caffe_net.py
  examples/ptb/train_ptb.py
  examples/ptb/train_ptb_custom_loop.py
  examples/reinforcement_learning/ddpg_pendulum.py
  examples/reinforcement_learning/dqn_cartpole.py
  examples/text_classification/run_text_classifier.py
  examples/text_classification/train_text_classifier.py
  examples/vae/train_vae.py
  examples/vae/train_vae_custom_loop.py
Labels: enhancement

#4499 Call FunctionHooks in chainer.grad
  chainer/function_node.py
  tests/chainer_tests/test_function_hook.py
Labels: bug, st:test-and-merge

#4541 [backport] Call FunctionHooks in chainer.grad
  chainer/function_node.py
  tests/chainer_tests/test_function_hook.py
Labels: backport, bug, st:test-and-merge

#4528 Fix temporary file permission issue in LogReport
  chainer/dataset/download.py
  chainer/testing/serializer.py
  chainer/training/extensions/_snapshot.py
  chainer/training/extensions/log_report.py
  chainer/utils/__init__.py
Labels: enhancement, st:test-and-merge, to-be-backported

#3477 Add higher-order derivative support of Chainer to the comparison table
  docs/source/comparison.rst
Labels: document, to-be-backported
