Repository chainer/chainer, pull requests merged in 2018-07, with the labels that each got.

#4958 Fix `GetItem.backward` for 0-dim boolean index
  chainer/functions/array/get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_get_item.py
Labels: bug, to-be-backported

#5037 Fix attribute name collisions in docstring
  chainer/initializer.py
  chainer/initializers/constant.py
  chainer/initializers/orthogonal.py
  chainer/initializers/uniform.py
  chainer/link.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  chainer/links/normalization/batch_normalization.py
  chainer/links/normalization/layer_normalization.py
  chainer/training/extension.py
  chainer/variable.py
  docs/source/_napoleon_patch.py
  docs/source/conf.py
Labels: document, st:test-and-merge, to-be-backported

#5045 [backport] Fix `GetItem.backward` for 0-dim boolean index
  chainer/functions/array/get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_get_item.py
Labels: backport, bug

#5034 Support default dtype in `L.BatchNormalization` and `L.BatchRenormalization`
  chainer/links/normalization/batch_normalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: feature, st:awaiting-response

#5047 [backport] Fix attribute name collisions in docstring
  chainer/initializer.py
  chainer/initializers/constant.py
  chainer/initializers/orthogonal.py
  chainer/initializers/uniform.py
  chainer/link.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  chainer/links/normalization/batch_normalization.py
  chainer/links/normalization/layer_normalization.py
  chainer/training/extension.py
  chainer/variable.py
  docs/source/_napoleon_patch.py
  docs/source/conf.py
Labels: backport, document

#5017 Avoid hasattr in `L.BatchNormalization`
  chainer/links/normalization/batch_normalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: enhancement, to-be-backported

#4864 Update style check tools
  docs/source/contribution.rst
  setup.cfg
  setup.py
Labels: test

#5051 Fix dead link to ``numpy.dtype.kind`` in Tips
  docs/source/tips.rst
Labels: document, to-be-backported

#5054 [backport] Fix dead link to ``numpy.dtype.kind`` in Tips
  docs/source/tips.rst
Labels: backport, document

#5053 Support all float dtypes in `F.mean_absolute_error`
  chainer/functions/loss/mean_absolute_error.py
  tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
Labels: feature

#5061 Fix kernels not memorized
  chainer/functions/loss/ctc.py
  chainer/functions/math/batch_l2_norm_squared.py
  chainer/functions/math/sparse_matmul.py
  chainer/functions/pooling/roi_pooling_2d.py
  chainer/functions/pooling/upsampling_2d.py
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: bug, to-be-backported

#5062 Support default dtype in `L.InceptionBN`
  chainer/links/connection/inceptionbn.py
  tests/chainer_tests/links_tests/connection_tests/test_inceptionbn.py
Labels: feature

#5058 Support default dtype in `L.Maxout`
  chainer/links/activation/maxout.py
  tests/chainer_tests/links_tests/activation_tests/test_maxout.py
Labels: feature

#5056 Fix ideep call in MultiAdd
  chainer/functions/math/basic_math.py
Labels: bug

#4644 Add `F.einsum`
  chainer/functions/__init__.py
  chainer/functions/math/einsum.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_einsum.py
Labels: feature

#4860 Create function to identify fashion-MNIST labels
  chainer/datasets/__init__.py
  chainer/datasets/fashion_mnist.py
  docs/source/reference/datasets.rst
  tests/chainer_tests/datasets_tests/test_mnist.py
Labels: enhancement, st:test-and-merge

#5030 Improve Variable guide
  docs/source/guides/variables.rst
Labels: document, st:test-and-merge, to-be-backported

#5073 [backport] Improve Variable guide
  docs/source/guides/variables.rst
Labels: backport, document, st:test-and-merge

#5072 [backport] Clarify distinction between `chainer.dataset` and `chainer.datasets`
  docs/source/reference/datasets.rst
Labels: backport, document

#5046 Let `F.depthwise_convolution_2d` use `F.convlution_2d` as an implementation
  chainer/functions/connection/depthwise_convolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_depthwise_convolution_2d.py
Labels: enhancement

#5044 Fix cross-link and format of Chainer at a glance documentation
  docs/source/glance.rst
Labels: document, st:test-and-merge

#5080 [backport] Add Chainer at a Glance documentation
  docs/image/glance/accuracy.png
  docs/image/glance/loss.png
  docs/image/glance/trainer-dataset.png
  docs/image/glance/trainer-extensions.png
  docs/image/glance/trainer-iterator.png
  docs/image/glance/trainer-model.png
  docs/image/glance/trainer-optimizer.png
  docs/image/glance/trainer-trainer.png
  docs/image/glance/trainer-updater.png
  docs/image/glance/trainer.png
  docs/source/glance.rst
  docs/source/index.rst
  docs/source/mushrooms.csv
Labels: backport, document

#5077 Support 0-dim params in distributions
  chainer/distributions/laplace.py
  chainer/distributions/normal.py
  chainer/testing/distribution_test.py
  chainer/variable.py
  tests/chainer_tests/distributions_tests/test_laplace.py
  tests/chainer_tests/distributions_tests/test_normal.py
Labels: enhancement, st:blocked-by-another-pr

#5090 Update caffe.rst
  docs/source/reference/caffe.rst
Labels: document, st:test-and-merge, to-be-backported

#5084 Support default dtype in `L.StatefulMGU`
  chainer/links/connection/mgu.py
  tests/chainer_tests/links_tests/connection_tests/test_mgu.py
Labels: feature

#5079 Fix `F.einsum` to support NumPy 1.15
  chainer/functions/math/einsum.py
Labels: enhancement

#5092 [backport] Update caffe.rst
  docs/source/reference/caffe.rst
Labels: backport, document

#5071 Remove test_get_dummy_device_for_empty_array
  tests/chainer_tests/test_cuda.py
Labels: st:test-and-merge, test, to-be-backported

#4987 Add `log_scale` option of Normal Distritbuion
  chainer/distributions/normal.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_normal.py
Labels: enhancement, st:test-and-merge

#5064 Initialize gradient of uninitialized parameter with default dtype when initializer is callable
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: enhancement, st:test-and-merge

#5066 [backport] Avoid hasattr in `L.BatchNormalization`
  chainer/links/normalization/batch_normalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: backport, enhancement

#4980 Add extension.name clarification
  chainer/training/extension.py
  chainer/training/trainer.py
Labels: document, st:test-and-merge, to-be-backported

#5100 Fix dataset path to support Windows
  chainer/dataset/download.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4961 LabeledZippedImageDataset
  chainer/datasets/__init__.py
  chainer/datasets/image_dataset.py
  docs/source/reference/datasets.rst
  tests/chainer_tests/datasets_tests/test_image_dataset.py
Labels: feature, st:test-and-merge

#5025 Add Bernoulli distribution
  chainer/distributions/__init__.py
  chainer/distributions/bernoulli.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_bernoulli.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: feature, st:test-and-merge

#5102 [backport] Fix dataset path to support Windows
  chainer/dataset/download.py
Labels: backport, enhancement

#4894 Add `StepShift` Extension.
  chainer/training/extensions/__init__.py
  chainer/training/extensions/step_shift.py
  docs/source/reference/training.rst
  tests/chainer_tests/training_tests/extensions_tests/test_step_shift.py
Labels: feature

#4769 Avoid zero division in F.normalize
  chainer/functions/normalization/l2_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: enhancement, to-be-backported

#5108 [backport] Avoid zero division in `F.normalize`
  chainer/functions/normalization/l2_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: backport, enhancement

#5093 Add upgrade guide for `Link.copyparams` changes
  docs/source/upgrade.rst
Labels: document

#5101 Support default dtype in `L.ResNetLayers`
  chainer/links/model/vision/resnet.py
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: feature

#5099 Support default dtype in `L.GoogLeNet`
  chainer/links/model/vision/googlenet.py
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: feature

#4758 Flush the output stream after PrintReport reports
  chainer/training/extensions/print_report.py
  tests/chainer_tests/training_tests/extensions_tests/test_print_report.py
Labels: bug, st:test-and-merge, to-be-backported

#5106 Add raw kernel function
  chainer/backends/cuda.py
  docs/source/reference/util/cuda.rst
Labels: feature

#5107 Support default dtype in `L.VGG16Layers`
  chainer/links/model/vision/vgg.py
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: feature

#5138 Fix L.Convolution2D error message
  chainer/links/connection/convolution_2d.py
Labels: enhancement, st:test-and-merge, to-be-backported

#5052 Support all float dtypes in `F.mean_squared_error`
  chainer/functions/loss/mean_squared_error.py
  tests/chainer_tests/functions_tests/loss_tests/test_mean_squared_error.py
Labels: feature

#5146 Flush the output stream after PrintReport reports
  chainer/training/extensions/print_report.py
  tests/chainer_tests/training_tests/extensions_tests/test_print_report.py
Labels: bug, st:test-and-merge, to-be-backported

#5141 Fix backward compatibility of `Link.__call__` MRO
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: bug, st:test-and-merge, to-be-backported

#5140 [backport] Fix L.Convolution2D error message
  chainer/links/connection/convolution_2d.py
Labels: backport, enhancement, st:test-and-merge

#5149 [backport] Flush the output stream after PrintReport reports
  chainer/training/extensions/print_report.py
  tests/chainer_tests/training_tests/extensions_tests/test_print_report.py
Labels: backport, bug

#5151 [backport] Fix backward compatibility of `Link.__call__` MRO
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: backport, bug

#5147 Trivial fix for parameterized test case of F.contrastive
  tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Labels: st:test-and-merge, test, to-be-backported

#5110 [backport] Add docs for `Extension.name`
  chainer/training/extension.py
  chainer/training/trainer.py
Labels: backport, document

#5122 Ignore float warnings if testing extreme value
  tests/chainer_tests/distributions_tests/test_bernoulli.py
Labels: test

#5154 [hotfix] [backport] Fix backward compatibility of `Link.__call__` MRO
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: backport, bug

#5152 Support all float data types in `F.contrastive`
  chainer/functions/loss/contrastive.py
  tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Labels: feature

#5145 Support all float data types in `F.absolute_error`
  chainer/functions/loss/absolute_error.py
  tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py
Labels: feature

#5120 Use `cuda.get_array_module` in fused function
  chainer/functions/activation/lstm.py
Labels: enhancement, to-be-backported

#5133 Fix test failure of TestResNetLayers
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: bug

#5157 Support old numpy in `F.split_axis`
  chainer/functions/array/split_axis.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: bug, to-be-backported

#5121 Add iDeep to backend docs
  chainer/backends/intel64.py
  docs/source/reference/util/cuda.rst
Labels: document, to-be-backported

#5144 Remove `cuda_fusion.py`
  chainer/backends/cuda.py
  chainer/backends/cuda_fusion.py
Labels: enhancement

#5162 [backport] Add iDeep to backend docs
  chainer/backends/intel64.py
  docs/source/reference/util/cuda.rst
Labels: backport, document

#5135 Rename VAE hyperparameter `C` to `beta` in the example
  examples/vae/net.py
Labels: example

#5063 Avoid numpy.ascontiguousarray when iDeep is used
  chainer/functions/connection/convolution_2d.py
Labels: enhancement

#5148 Avoid use of ideep in doctest
  docs/source/tips.rst
Labels: document, st:test-and-merge, to-be-backported

#5168 [backport] Avoid use of ideep in doctest
  docs/source/tips.rst
Labels: backport, document

#5170 [backport] Fix cross-link and format of Chainer at a glance documentation
  docs/source/glance.rst
Labels: backport, document
