Repository chainer/chainer, pull requests merged in 2018-08, with the labels that each got.

#5167 Normalize chainer.config.dtype in chainer.get_dtype()
  chainer/__init__.py
Labels: enhancement

#5150 Implement eps_inside_sqrt option to RMSprop
  chainer/optimizers/rmsprop.py
  tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
Labels: enhancement

#4899 Add multivariate normal distribution
  chainer/backends/cuda.py
  chainer/distributions/__init__.py
  chainer/distributions/bernoulli.py
  chainer/distributions/laplace.py
  chainer/distributions/multivariate_normal.py
  chainer/distributions/normal.py
  chainer/testing/distribution_test.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_multivariate_normal.py
Labels: feature

#5129 Fix the condition for the switching of cuDNN in `F.deconvolution_nd`
  chainer/functions/connection/deconvolution_nd.py
Labels: bug, st:test-and-merge, to-be-backported

#5175 Support all float dtypes in `F.hinge`
  chainer/functions/loss/hinge.py
  tests/chainer_tests/functions_tests/loss_tests/test_hinge.py
Labels: feature

#5176 Support all float dtypes in `F.huber_loss`
  chainer/functions/loss/huber_loss.py
  tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
Labels: feature

#5173 Minor fixes to `D.MultivariateNormal`
  chainer/distribution.py
  chainer/distributions/multivariate_normal.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_multivariate_normal.py
Labels: enhancement

#4772 New backward_accumulate
  chainer/_backprop_utils.py
  chainer/function_node.py
  chainer/variable.py
  tests/chainer_tests/test_backprop_utils.py
  tests/chainer_tests/test_function_node.py
Labels: enhancement

#4581 Implemented dataset using pickle
  chainer/datasets/__init__.py
  chainer/datasets/pickle_dataset.py
  docs/source/reference/datasets.rst
  tests/chainer_tests/datasets_tests/test_pickle_dataset.py
Labels: feature

#5094 Use `F.cumprod` in backward of `F.prod`
  chainer/functions/math/prod.py
  tests/chainer_tests/functions_tests/math_tests/test_prod.py
Labels: enhancement, st:test-and-merge

#5186 Fix windows test failure
  tests/chainer_tests/datasets_tests/test_pickle_dataset.py
Labels: test

#5182 Fix doctests of `open_pickle_dataset`
  chainer/datasets/pickle_dataset.py
Labels: test

#5193 Add .pytest_cache/ to .gitignore
  .gitignore
Labels: other, to-be-backported

#5190 Support 0-dim input in `F.logsumexp`
  chainer/functions/math/logsumexp.py
  tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py
Labels: bug, to-be-backported

#5179 Fix backward computation in F.forget
  chainer/functions/util/forget.py
  tests/chainer_tests/functions_tests/util_tests/test_forget.py
Labels: bug, no-compat

#5185 Avoid cancellation in Normal
  chainer/distributions/normal.py
Labels: bug

#5181 Make imports in alphabetical order
  chainer/functions/array/split_axis.py
  chainer/functions/loss/ctc.py
  chainer/functions/math/tensordot.py
  chainer/functions/normalization/batch_normalization.py
  chainer/link.py
  chainer/utils/__init__.py
Labels: enhancement

#5123 Add Uniform distribution
  chainer/distributions/__init__.py
  chainer/distributions/uniform.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_uniform.py
Labels: feature

#5195 Implement erfcx
  chainer/functions/__init__.py
  chainer/functions/math/erfcx.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_erfcx.py
Labels: feature

#5201 Fix docstring of erfinv
  chainer/functions/math/erfinv.py
Labels: document

#5178 Fix grammar in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: document, to-be-backported

#5124 Add LogNormal distribution
  chainer/distributions/__init__.py
  chainer/distributions/log_normal.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_log_normal.py
Labels: feature

#5095 Move `backends.cuda.copyto` to `backends.copyto` and make it work with iDeep
  chainer/backends/__init__.py
  chainer/backends/cuda.py
  chainer/link.py
  chainer/variable.py
  docs/source/reference/util/cuda.rst
  tests/chainer_tests/backends_test/test_init.py
  tests/chainer_tests/test_cuda.py
  tests/chainer_tests/test_variable.py
Labels: bug

#5194 [backport] Add .pytest_cache/ to .gitignore
  .gitignore
Labels: backport, other

#5199 Retain outputs in `F.erfinv`
  chainer/functions/math/erfinv.py
Labels: enhancement

#5070 Add roi_align_2d function
  chainer/functions/__init__.py
  chainer/functions/pooling/roi_align_2d.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_align_2d.py
Labels: feature

#5203 Fix Sphinx issues in the reference of probability distributions
  chainer/distribution.py
Labels: document

#3409 Simplify and stabilize softmax_cross_entropy test
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: test, to-be-backported

#5119 Return params and children as ordered by name in Link and Chain
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: enhancement

#5088 Add beta distribution
  chainer/distributions/__init__.py
  chainer/distributions/beta.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_beta.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: feature

#5187 Add sphinx to doctest requirements
  setup.py
Labels: test

#5174 Support all float dtypes in `F.decov`
  chainer/functions/loss/decov.py
  tests/chainer_tests/functions_tests/loss_tests/test_decov.py
Labels: feature

#5180 Fix collections.Iterable
  chainer/functions/pooling/pooling_2d.py
  chainer/links/caffe/caffe_function.py
  chainer/links/theano/theano_function.py
Labels: enhancement

#5216 [backport] Simplify and stabilize softmax_cross_entropy test
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: backport, test

#5208 Change iDeep in tips.rst to Chainer Backend for Intel Architecture
  docs/source/tips.rst
Labels: document

#5028 Add categorical distribution
  chainer/distributions/__init__.py
  chainer/distributions/bernoulli.py
  chainer/distributions/categorical.py
  chainer/distributions/utils.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_bernoulli.py
  tests/chainer_tests/distributions_tests/test_categorical.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_utils.py
Labels: feature

#5212 Support all float dtypes in `F.squared_error`
  chainer/functions/loss/squared_error.py
  tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py
Labels: feature

#5207 Use `xp.einsum` in `F.bilinear`
  chainer/functions/connection/bilinear.py
Labels: enhancement, st:test-and-merge

#5218 Fix occasional test failure of `contrastive`
  tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Labels: test, to-be-backported

#5189 Improve type check messages for some math functions
  chainer/functions/math/basic_math.py
  chainer/functions/math/batch_l2_norm_squared.py
  chainer/functions/math/clip.py
  chainer/functions/math/cumprod.py
  chainer/functions/math/cumsum.py
  chainer/functions/math/det.py
  chainer/functions/math/digamma.py
  chainer/functions/math/einsum.py
  chainer/functions/math/erf.py
  chainer/functions/math/erfc.py
  chainer/functions/math/erfinv.py
  chainer/functions/math/exponential.py
  chainer/functions/math/exponential_m1.py
  chainer/functions/math/fft.py
  chainer/functions/math/fmod.py
  chainer/functions/math/hyperbolic.py
  chainer/functions/math/inv.py
Labels: enhancement, st:test-and-merge

#5191 Avoid keyword arguments in `FunctionHook` callbacks
  chainer/function_hook.py
  chainer/function_node.py
Labels: enhancement

#5222 [backport] Fix occasional test failure of `l2normalize`
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: backport, test

#5223 Ignore Theano warns in python 3.7
  setup.cfg
Labels: st:test-and-merge, test, to-be-backported

#5177 [backport] Use collections.abc to avoid DeprecationWarning in Python 3.7
  chainer/functions/array/split_axis.py
  chainer/functions/loss/ctc.py
  chainer/functions/math/tensordot.py
  chainer/link.py
  chainer/utils/__init__.py
Labels: backport, enhancement, st:test-and-merge

#4935 Add `WarmupShift` and `MultistepShift` extensions
  chainer/training/extensions/__init__.py
  chainer/training/extensions/multistep_shift.py
  chainer/training/extensions/warmup_shift.py
  docs/source/reference/training.rst
  tests/chainer_tests/training_tests/extensions_tests/test_multistep_shift.py
  tests/chainer_tests/training_tests/extensions_tests/test_warmup_shift.py
Labels: feature

#5227 [backport] Ignore Theano warns in python 3.7
  setup.cfg
Labels: backport, test

#5224 Improve type check messages for some array functions
  chainer/functions/array/diagonal.py
  chainer/functions/array/dstack.py
  chainer/functions/array/expand_dims.py
  chainer/functions/array/flip.py
  chainer/functions/array/fliplr.py
  chainer/functions/array/flipud.py
  chainer/functions/array/get_item.py
  chainer/functions/array/hstack.py
  chainer/functions/array/im2col.py
  chainer/functions/array/moveaxis.py
  chainer/functions/array/pad.py
  chainer/functions/array/pad_sequence.py
  chainer/functions/array/permutate.py
  chainer/functions/array/repeat.py
  chainer/functions/array/reshape.py
  chainer/functions/array/resize_images.py
  chainer/functions/array/rollaxis.py
  chainer/functions/array/scatter_add.py
  chainer/functions/array/select_item.py
  chainer/functions/array/separate.py
  chainer/functions/array/space2depth.py
  chainer/functions/array/spatial_transformer_grid.py
Labels: enhancement, st:test-and-merge

#5235 Support all float dtypes in `F.batch_l2_norm_squared`
  chainer/functions/math/batch_l2_norm_squared.py
  tests/chainer_tests/functions_tests/math_tests/test_batch_l2_norm_squared.py
Labels: feature

#4742 Change the initial avg_var of BatchNormalization to 1
  chainer/initializers/__init__.py
  chainer/links/normalization/batch_normalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: bug, feature, no-compat, st:test-and-merge

#5238 Fix cpu codes of indexing in `F.softmax_cross_entropy`
  chainer/functions/loss/softmax_cross_entropy.py
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: bug, to-be-backported

#5241 [backport] Fix cpu codes of indexing in `F.softmax_cross_entropy`
  chainer/functions/loss/softmax_cross_entropy.py
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: backport, bug

#5237 Add `F.ndtr`
  chainer/functions/__init__.py
  chainer/functions/math/ndtr.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_ndtr.py
Labels: feature, st:test-and-merge

#5086 Use automatic broadcasting in distributions
  chainer/distributions/bernoulli.py
  chainer/distributions/laplace.py
  chainer/distributions/log_normal.py
  chainer/distributions/normal.py
Labels: enhancement

#5236 Adjust tolerance of TestMatMul
  tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
Labels: test

#5230 Ignore `DeprecationWarning`s at importing Theano
  setup.cfg
  tests/chainer_tests/links_tests/theano_tests/test_theano_function.py
Labels: test

#5200 Improve type check messages for some functions
  chainer/functions/connection/shift.py
  chainer/functions/evaluation/accuracy.py
  chainer/functions/evaluation/binary_accuracy.py
  chainer/functions/evaluation/classification_summary.py
  chainer/functions/evaluation/r2_score.py
  chainer/functions/loss/absolute_error.py
  chainer/functions/loss/contrastive.py
  chainer/functions/loss/cross_covariance.py
  chainer/functions/loss/ctc.py
  chainer/functions/loss/decov.py
  chainer/functions/loss/hinge.py
  chainer/functions/loss/huber_loss.py
  chainer/functions/loss/mean_absolute_error.py
  chainer/functions/loss/mean_squared_error.py
  chainer/functions/loss/negative_sampling.py
  chainer/functions/loss/squared_error.py
  chainer/functions/loss/triplet.py
Labels: enhancement

#5243 [backport] Ignore `DeprecationWarning`s at importing Theano
  setup.cfg
  tests/chainer_tests/links_tests/theano_tests/test_theano_function.py
Labels: backport, test

#5225 Minor fixes to `D.Uniform`
  chainer/distributions/uniform.py
Labels: enhancement

#5068 Better initializer support in `L.Maxout`
  chainer/links/activation/maxout.py
  tests/chainer_tests/links_tests/activation_tests/test_maxout.py
Labels: feature

#3059 Add Randomized Leaky ReLU(RReLU) activation function
  chainer/functions/__init__.py
  chainer/functions/activation/rrelu.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
Labels: feature, reviewer-team

#5239 Add log_ndtr
  chainer/functions/__init__.py
  chainer/functions/math/log_ndtr.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_log_ndtr.py
Labels: feature

#5242 Use erfcinv for Normal.icdf
  chainer/distributions/normal.py
Labels: enhancement

#5240 Use ndtr and log_ndtr in normal distribution
  chainer/distributions/normal.py
Labels: enhancement

#5215 Support axis argument for log_softmax
  chainer/functions/activation/log_softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
Labels: feature, st:test-and-merge

#4607 Stalled dataset detection in MultiprocessIterator
  chainer/iterators/multiprocess_iterator.py
  tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
Labels: enhancement, st:awaiting-response

#5196 [backport] Support 0-dim input in `F.logsumexp`
  chainer/functions/math/logsumexp.py
  tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py
Labels: backport, bug, st:test-and-merge

#5247 Add `F.ndtri`
  chainer/functions/__init__.py
  chainer/functions/math/ndtri.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_ndtri.py
Labels: feature

#5248 Improve type check messages for some functions
  chainer/functions/math/lgamma.py
  chainer/functions/math/linear_interpolate.py
  chainer/functions/math/logarithm_1p.py
  chainer/functions/math/logsumexp.py
  chainer/functions/math/matmul.py
  chainer/functions/math/maximum.py
  chainer/functions/math/minimum.py
  chainer/functions/math/minmax.py
  chainer/functions/math/polygamma.py
  chainer/functions/math/prod.py
  chainer/functions/math/sparse_matmul.py
  chainer/functions/math/sqrt.py
  chainer/functions/math/square.py
  chainer/functions/math/squared_difference.py
  chainer/functions/math/sum.py
  chainer/functions/math/tensordot.py
  chainer/functions/math/trigonometric.py
  chainer/functions/noise/dropout.py
  chainer/functions/noise/gaussian.py
  chainer/functions/noise/simplified_dropconnect.py
Labels: enhancement

#5253 [backport] Fix occasional test failure of `contrastive`
  tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Labels: backport, test

#5254 Use ndtri in normal distribution
  chainer/distributions/normal.py
Labels: enhancement

#5252 [backport] Trivial fix for parameterized test case of F.contrastive
  tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Labels: backport, test

#5257 Fix toc level of Order sampler examples
  docs/source/reference/iterators.rst
Labels: document, st:test-and-merge

#5259 Rename roi_align_2d to roi_average_align_2d
  chainer/functions/__init__.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_align_2d.py
Labels: enhancement

#5250 [backport] Improve Iterator description in Chainer at a glance documentation
  docs/source/glance.rst
Labels: backport, document

#5260 Use normcdfinv in F.ndtri
  chainer/functions/math/ndtri.py
Labels: enhancement, st:test-and-merge

#5261 Comment out extreme test of D.Categorical
  tests/chainer_tests/distributions_tests/test_categorical.py
Labels: bug

#5163 Include platform information to `chainer.print_runtime_info()`
  chainer/_runtime_info.py
Labels: feature, to-be-backported

#4977 Fix seq2seq example to support `--resume` option and improve docs
  chainer/training/trainer.py
  docs/source/guides/serializers.rst
  examples/seq2seq/seq2seq.py
Labels: example, st:test-and-merge, to-be-backported

#5258 Avoid mutating in_params of coo_matmul
  chainer/functions/math/sparse_matmul.py
Labels: enhancement

#5269 Use `with cuda_device`
  chainer/function_node.py
  chainer/variable.py
Labels: enhancement

#5271 Fix import order
  chainer/_runtime_info.py
Labels: bug, to-be-backported

#5211 Support all float dtypes in `F.sigmoid_cross_entropy`
  chainer/functions/loss/sigmoid_cross_entropy.py
  tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
Labels: feature

#5270 Add `contains_nan`
  chainer/backends/__init__.py
  chainer/function_node.py
  chainer/variable.py
Labels: feature

#5275 [backport] Fix seq2seq example to support `--resume` option and improve docs
  chainer/training/trainer.py
  docs/source/guides/serializers.rst
  examples/seq2seq/seq2seq.py
Labels: backport, example

#5268 [backport] Include platform information to `chainer.print_runtime_info()`
  chainer/_runtime_info.py
Labels: backport, feature

#5255 Use log_softmax in `D.Categorical`
  chainer/distributions/categorical.py
Labels: enhancement

#4587 Support None for the in_channels argument in ConvolutionND/DeconvolutionND
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_nd.py
  tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4831 Improve performance of sparse_matmul
  chainer/functions/math/sparse_matmul.py
  chainer/utils/__init__.py
  chainer/utils/sparse.py
  tests/chainer_tests/functions_tests/math_tests/test_sparse_matmul.py
  tests/chainer_tests/utils_tests/test_sparse.py
Labels: feature

#4844 Allow weighted scalar reporting by providing a tuple to the reporter
  chainer/reporter.py
  tests/chainer_tests/test_reporter.py
Labels: feature, st:test-and-merge, takeover

#5114 Support default dtype in `F.spatial_transformer_grid`
  chainer/functions/array/spatial_transformer_grid.py
  tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_grid.py
Labels: feature

#5251 Improve type check messages for some functions
  chainer/functions/activation/clipped_relu.py
  chainer/functions/activation/crelu.py
  chainer/functions/activation/elu.py
  chainer/functions/activation/hard_sigmoid.py
  chainer/functions/activation/leaky_relu.py
  chainer/functions/activation/log_softmax.py
  chainer/functions/activation/lstm.py
  chainer/functions/activation/prelu.py
  chainer/functions/activation/relu.py
  chainer/functions/activation/sigmoid.py
  chainer/functions/activation/slstm.py
  chainer/functions/activation/softmax.py
  chainer/functions/activation/softplus.py
  chainer/functions/activation/swish.py
  chainer/functions/activation/tanh.py
  chainer/functions/array/broadcast.py
  chainer/functions/array/cast.py
  chainer/functions/array/copy.py
  chainer/functions/array/depth2space.py
Labels: enhancement

#5256 Support all float dtypes in `F.normalize`
  chainer/functions/normalization/l2_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: feature

#5279 [backport] Support None for the in_channels argument in ConvolutionND/DeconvolutionND
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_nd.py
  tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py
Labels: backport, enhancement
