Repository chainer/chainer, pull requests merged in 2018-12, with the labels that each got.

#5752 Add warning in ChainerX documentation
  docs/source/chainerx/index.rst
Labels: ChainerX, document

#5711 [backport] Fix regex of protobuf modules warned by Python 3.7
  setup.cfg
Labels: backport, test

#5743 Build ChainerX documentation on ReadTheDocs
  .travis.yml
  docs/rtd_conda.yml
  docs/source/conf.py
  readthedocs.yml
  setup.py
Labels: ChainerX, document

#5714 [backport] Support default dtype in `L.BinaryHierarchicalSoftmax`
  chainer/links/loss/hierarchical_softmax.py
  tests/chainer_tests/links_tests/loss_tests/test_hierarchical_softmax.py
Labels: backport, feature

#5750 [backport] Change `Link.add_hook` to return `self`
  chainer/link.py
  tests/chainer_tests/test_link_hook.py
Labels: backport, enhancement

#5727 Fix test of `F.connectionist_temporal_classification`
  tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Labels: st:test-and-merge, test

#5768 Add robots.txt to hide older versions from search results
  docs/source/_static/robots.txt
Labels: document

#5713 [backport] Fix BatchNormalization with lazy initialization fail on GPU #5682
  chainer/links/normalization/batch_normalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: backport, bug, st:test-and-merge

#5748 Improve gradient mismatch error
  chainerx_cc/chainerx/array_test.cc
  chainerx_cc/chainerx/backward.cc
  chainerx_cc/chainerx/backward.h
  chainerx_cc/chainerx/backward_test.cc
  chainerx_cc/chainerx/error.h
  chainerx_cc/chainerx/python/error.cc
Labels: ChainerX, enhancement, st:test-and-merge

#5733 Refactor tests of `F.split_axis` and `F.concat`
  tests/chainer_tests/functions_tests/array_tests/test_concat.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: st:test-and-merge, test

#5766 Build ChainerX on ReadTheDocs
  chainerx_build_helper.py
  docs/rtd_conda.yml
  docs/source/conf.py
  readthedocs.yml
  setup.py
Labels: ChainerX, document

#5769 Return exitcode of `make html` to Travis
  .travis.yml
Labels: st:test-and-merge, test, to-be-backported

#5744 Fixes for clang
  chainerx_cc/CMakeLists.txt
  chainerx_cc/chainerx/routines/connection_test.cc
  chainerx_cc/chainerx/routines/manipulation_test.cc
  chainerx_cc/chainerx/routines/normalization_test.cc
  chainerx_cc/chainerx/routines/pooling_test.cc
Labels: ChainerX

#5772 [backport] Fix typo in v2 Upgrade Guide
  docs/source/upgrade_v2.rst
Labels: backport, document

#5770 Do not overwrite CMAKE_CXX_FLAGS a user specified
  chainerx_cc/CMakeLists.txt
Labels: ChainerX, enhancement, st:test-and-merge

#5659 Bugfix of MultiNodeOptimizer with loss scaling
  chainermn/optimizers.py
Labels: ChainerMN, bug, st:test-and-merge, to-be-backported

#5666 Add test mode to text classification example
  examples/text_classification/train_text_classifier.py
Labels: test, to-be-backported

#5784 [backport] Add test mode to text classification example
  examples/text_classification/train_text_classifier.py
Labels: backport, test

#5445 Make build_computational_graph accept single output
  chainer/computational_graph.py
  tests/chainer_tests/test_computational_graph.py
Labels: feature, st:test-and-merge

#5787 Fix to test against new chainerx.GradientError
  tests/chainerx_tests/unit_tests/test_array.py
Labels: test

#5739 fix side effect of MultiprocessParallelUpdater
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: bug, to-be-backported

#5781 Resolve _as_noncontiguous_array workaround for ChainerX
  chainer/testing/array.py
Labels: ChainerX, enhancement, st:test-and-merge

#5789 Fix a couple of broken links from markdown files
  chainerx_cc/README.md
  examples/pix2pix/README.md
Labels: document, to-be-backported

#5754 Forbid fallback get/setitem for arrays with backprop required
  chainer/utils/array.py
Labels: ChainerX, enhancement, st:test-and-merge

#5775 Remove some TODOs of the chainerx resnet example
  chainerx_cc/examples/imagenet/resnet50.py
  chainerx_cc/examples/imagenet/train_imagenet.py
Labels: ChainerX, st:test-and-merge

#5777 Switch device during gradient_check
  chainer/gradient_check.py
Labels: ChainerX, st:test-and-merge

#5779 Fix `testing.BackendConfig` context for repeated use
  chainer/testing/backend.py
Labels: bug, st:test-and-merge

#5798 Update pybind dependency to v2.2.4
  chainerx_cc/third_party/pybind11.cmake
Labels: ChainerX, st:test-and-merge

#5760 Implement BFC algorithm
  chainerx_cc/chainerx/cuda/memory_pool.cc
  chainerx_cc/chainerx/cuda/memory_pool.h
  chainerx_cc/chainerx/cuda/memory_pool_test.cc
Labels: ChainerX, enhancement, st:test-and-merge

#5664 Use default dtype in `L.NegativeSampling`
  chainer/links/loss/negative_sampling.py
  tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
Labels: feature

#5788 Fix scalar handling of `indices_and_sections` in `chainerx.split`
  chainerx_cc/chainerx/python/routines.cc
  tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Labels: ChainerX, bug, st:test-and-merge

#5745 `FunctionNode` automatic fallback of array attributes in forward
  chainer/function_node.py
  tests/chainer_tests/functions_tests/activation_tests/test_prelu.py
  tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
Labels: ChainerX, st:test-and-merge

#5811 Fix `F.cast` gradient for casts between the same dtypes
  chainer/functions/array/cast.py
  tests/chainer_tests/functions_tests/array_tests/test_cast.py
Labels: bug, to-be-backported

#5795 Fix wording in documentation
  docs/source/index.rst
Labels: document, to-be-backported

#5640 Support unretained `Variable`s in `_check_grad_type`
  chainer/function.py
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: enhancement, to-be-backported

#5809 Fix bug when CuPy not installed and cuda.fuse decorator used without parenthesis
  chainer/backends/cuda.py
Labels: bug, to-be-backported

#5820 [backport] Fix wording in documentation
  docs/source/index.rst
Labels: backport, document, st:test-and-merge

#5726 Use new RNN implementation
  chainer/functions/connection/n_step_rnn.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: enhancement, st:test-and-merge, to-be-backported

#5718 Make docs of activation functions refer `ndarray`
  chainer/functions/activation/crelu.py
  chainer/functions/activation/elu.py
  chainer/functions/activation/hard_sigmoid.py
  chainer/functions/activation/leaky_relu.py
  chainer/functions/activation/log_softmax.py
  chainer/functions/activation/lstm.py
  chainer/functions/activation/maxout.py
  chainer/functions/activation/prelu.py
  chainer/functions/activation/relu.py
  chainer/functions/activation/rrelu.py
  chainer/functions/activation/selu.py
  chainer/functions/activation/sigmoid.py
  chainer/functions/activation/slstm.py
  chainer/functions/activation/softmax.py
  chainer/functions/activation/softplus.py
  chainer/functions/activation/swish.py
  chainer/functions/activation/tanh.py
  chainer/functions/activation/tree_lstm.py
Labels: document, to-be-backported

#5825 [backport] Fix bug when CuPy not installed and cuda.fuse decorator used without parenthesis
  chainer/backends/cuda.py
Labels: backport, bug

#5813 Remove `F.clip` type restriction
  chainer/functions/math/clip.py
  tests/chainer_tests/functions_tests/math_tests/test_clip.py
Labels: enhancement, st:test-and-merge

#5805 ignore chainerx reference generated doc
  .gitignore
Labels: document

#5818 [backport] Fix `F.cast` gradient for casts between the same dtypes
  chainer/functions/array/cast.py
  tests/chainer_tests/functions_tests/array_tests/test_cast.py
Labels: backport, bug

#5833 Add comment to MultiprocessIterator.__copy__
  chainer/iterators/multiprocess_iterator.py
Labels: document, st:test-and-merge

#5836 Fix gitignore to avoid ignoring some necessary files
  .gitignore
Labels: other, to-be-backported

#5838 [backport] Fix `.gitignore` to avoid ignoring some necessary files
  .gitignore
Labels: backport, other

#5840 Move workaround `utils._getitem`/`_setitem` to `chainerx`
  chainer/dataset/convert.py
  chainer/gradient_check.py
  chainer/testing/array.py
  chainer/utils/__init__.py
  chainer/utils/array.py
  chainer/utils/walker_alias.py
  chainerx/__init__.py
  chainerx/_docs/__init__.py
  chainerx/_fallback_workarounds.py
  chainerx/_ndarray.py
Labels: ChainerX, st:test-and-merge

#5801 Random code enhancements
  chainerx_cc/chainerx/cuda/cuda_conv_test.cc
  chainerx_cc/chainerx/routines/connection_test.cc
  chainerx_cc/chainerx/routines/manipulation.cc
Labels: ChainerX, enhancement, st:test-and-merge

#5791 Model Parallel Documentation
  docs/image/model_parallel/averaging.png
  docs/image/model_parallel/comm_split.png
  docs/image/model_parallel/communication_as_function.png
  docs/image/model_parallel/delegate_variable_0.png
  docs/image/model_parallel/delegate_variable_1.png
  docs/image/model_parallel/empty_dataset.png
  docs/image/model_parallel/model_parallel_mlp.png
  docs/image/model_parallel/multi_node_iterator.png
  docs/image/model_parallel/parallel_conv.png
  docs/image/model_parallel/pseudo_connect_0.png
  docs/image/model_parallel/pseudo_connect_1.png
  docs/image/model_parallel/scatter_dataset.png
  docs/image/model_parallel/seq2seq_0.png
  docs/image/model_parallel/seq2seq_1.png
  docs/image/model_parallel/spmd.png
  docs/source/chainermn/index.rst
  docs/source/chainermn/model_parallel/example1_simple_mlp.rst
  docs/source/chainermn/model_parallel/example2_seq2seq.rst
  docs/source/chainermn/model_parallel/example3_parallel_conv.rst
  docs/source/chainermn/model_parallel/example4_ensemble.rst
  docs/source/chainermn/model_parallel/index.rst
  docs/source/chainermn/model_parallel/model_parallel_on_chainermn.rst
  docs/source/chainermn/model_parallel/overview.rst
Labels: ChainerMN, document

#5792 [backport] Fix a couple of broken links from markdown files
  examples/pix2pix/README.md
Labels: backport, document

#5843 [backport] Model Parallel Documentation
  docs/image/model_parallel/averaging.png
  docs/image/model_parallel/comm_split.png
  docs/image/model_parallel/communication_as_function.png
  docs/image/model_parallel/delegate_variable_0.png
  docs/image/model_parallel/delegate_variable_1.png
  docs/image/model_parallel/empty_dataset.png
  docs/image/model_parallel/model_parallel_mlp.png
  docs/image/model_parallel/multi_node_iterator.png
  docs/image/model_parallel/parallel_conv.png
  docs/image/model_parallel/pseudo_connect_0.png
  docs/image/model_parallel/pseudo_connect_1.png
  docs/image/model_parallel/scatter_dataset.png
  docs/image/model_parallel/seq2seq_0.png
  docs/image/model_parallel/seq2seq_1.png
  docs/image/model_parallel/spmd.png
  docs/source/chainermn/index.rst
  docs/source/chainermn/model_parallel/example1_simple_mlp.rst
  docs/source/chainermn/model_parallel/example2_seq2seq.rst
  docs/source/chainermn/model_parallel/example3_parallel_conv.rst
  docs/source/chainermn/model_parallel/example4_ensemble.rst
  docs/source/chainermn/model_parallel/index.rst
  docs/source/chainermn/model_parallel/model_parallel_on_chainermn.rst
  docs/source/chainermn/model_parallel/overview.rst
Labels: ChainerMN, backport, document

#5815 Fix ChainerX Python docstring allocation issue
  chainerx_cc/chainerx/python/core_module.cc
Labels: ChainerX, bug, st:test-and-merge

#5849 Update gsl-lite to v0.32.0
  chainerx_cc/third_party/gsl-lite.cmake
Labels: ChainerX, st:test-and-merge

#5737 fix usage of downsample_fb in resnet
  chainer/links/model/vision/resnet.py
Labels: bug, st:test-and-merge, to-be-backported

#5850 [backport] fix usage of downsample_fb in resnet
  chainer/links/model/vision/resnet.py
Labels: backport, bug, st:test-and-merge

#5761 Add ChainerX native float16
  chainerx_cc/LICENSE.txt
  chainerx_cc/chainerx/CMakeLists.txt
  chainerx_cc/chainerx/float16.cc
  chainerx_cc/chainerx/float16.h
  chainerx_cc/chainerx/float16_test.cc
Labels: ChainerX, feature

#5568 Simplify batch normalization with cuDNN
  chainer/functions/normalization/batch_normalization.py
  chainer/functions/normalization/batch_renormalization.py
  chainermn/functions/batch_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Labels: enhancement, st:test-and-merge, to-be-backported

#5803 [backport] Add `hasattr` check to user-specified `flush` call to file-like objects.
  chainer/datasets/pickle_dataset.py
  chainer/function_hooks/cupy_memory_profile.py
  chainer/function_hooks/debug_print.py
  chainer/function_hooks/timer.py
  chainer/training/extensions/progress_bar.py
Labels: backport, enhancement

#5827 [backport] Use new RNN implementation
  chainer/functions/connection/n_step_rnn.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: backport, enhancement

#5686 Add explanations for lenet5
  docs/source/examples/cnn.rst
Labels: document, to-be-backported

#5835 Remove unnecessary cast in `F.huber_loss`
  chainer/functions/loss/huber_loss.py
Labels: enhancement, st:test-and-merge

#5834 Use iter.reset() in ptb example
  examples/ptb/train_ptb_custom_loop.py
  examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py
Labels: example

#5857 [backport] Use `iter.reset()` in PTB example
  examples/ptb/train_ptb_custom_loop.py
  examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py
Labels: backport, example

#5337 add `D.Cauchy`
  chainer/distributions/__init__.py
  chainer/distributions/cauchy.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_cauchy.py
Labels: feature

#5343 add `D.Geometric`
  chainer/distributions/__init__.py
  chainer/distributions/geometric.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_geometric.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: feature

#5853 [backport] Simplify batch normalization with cuDNN
  chainer/functions/normalization/batch_normalization.py
  chainer/functions/normalization/batch_renormalization.py
  chainermn/functions/batch_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Labels: backport, enhancement

#5858 Refactor CI scripts
  scripts/ci/chainerx/jenkins/Dockerfile.template
  scripts/ci/chainerx/jenkins/clear-docker-cache.sh
  scripts/ci/chainerx/jenkins/run.sh
  scripts/ci/chainerx/jenkins/run_docker.sh
  scripts/ci/chainerx/setup-conda.sh
  scripts/ci/chainerx/setup-ubuntu.sh
  scripts/ci/run-step.sh
  scripts/ci/steps.sh
Labels: test

#5751 Support all float dtypes in `F.spatial_transformer_sampler`
  chainer/functions/array/spatial_transformer_sampler.py
  tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py
Labels: feature

#5860 Remove `.circleci`
  .circleci/config.yml
Labels: test

#5855 [backport] Add explanations for lenet5
  docs/source/examples/cnn.rst
Labels: backport, document

#5800 Code enhancements: avoid array copies
  chainerx_cc/chainerx/routines/manipulation.cc
  chainerx_cc/chainerx/routines/math.cc
  chainerx_cc/chainerx/routines/normalization.cc
  chainerx_cc/chainerx/routines/pooling.cc
Labels: ChainerX, enhancement, st:test-and-merge

#5081 remove v1 v2 references
  chainer/backends/cuda.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/noise/dropout.py
  chainer/functions/noise/zoneout.py
  chainer/functions/normalization/batch_normalization.py
  chainer/link.py
  chainer/links/caffe/caffe_function.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/deconvolution_2d.py
  chainer/links/connection/gru.py
  chainer/links/connection/mlp_convolution_2d.py
  chainer/links/connection/n_step_gru.py
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
  chainer/links/connection/parameter.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  chainer/links/normalization/batch_normalization.py
  chainer/reporter.py
  chainer/serializer.py
  chainer/training/extensions/computational_graph.py
  chainer/variable.py
  docs/source/compatibility.rst
  docs/source/contribution.rst
  docs/source/examples/cnn.rst
  docs/source/guides/gpu.rst
  docs/source/guides/links.rst
  docs/source/guides/models.rst
  docs/source/reference/debug.rst
  docs/source/reference/functions.rst
Labels: document

#5629 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: cat:document, to-be-backported

#5246 Add description for initializer dtype
  docs/source/reference/initializers.rst
Labels: cat:document, to-be-backported

#5864 Add `chainerx.ndarray` to the `ndarray` doc
  docs/source/reference/variable.rst
Labels: ChainerX, cat:document, st:test-and-merge

#5870 Fix clang-tidy error
  chainerx_cc/chainerx/routines/math.cc
Labels: cat:code-fix, st:test-and-merge

#5863 Make docs of array functions refer `ndarray`
  chainer/functions/array/broadcast.py
  chainer/functions/array/cast.py
  chainer/functions/array/concat.py
  chainer/functions/array/copy.py
  chainer/functions/array/depth2space.py
  chainer/functions/array/diagonal.py
  chainer/functions/array/dstack.py
  chainer/functions/array/expand_dims.py
  chainer/functions/array/flatten.py
  chainer/functions/array/flip.py
  chainer/functions/array/fliplr.py
  chainer/functions/array/flipud.py
  chainer/functions/array/get_item.py
  chainer/functions/array/hstack.py
  chainer/functions/array/im2col.py
  chainer/functions/array/moveaxis.py
  chainer/functions/array/pad.py
  chainer/functions/array/pad_sequence.py
  chainer/functions/array/permutate.py
  chainer/functions/array/repeat.py
  chainer/functions/array/reshape.py
  chainer/functions/array/resize_images.py
  chainer/functions/array/rollaxis.py
  chainer/functions/array/scatter_add.py
  chainer/functions/array/select_item.py
  chainer/functions/array/separate.py
  chainer/functions/array/space2depth.py
  chainer/functions/array/spatial_transformer_grid.py
  chainer/functions/array/spatial_transformer_sampler.py
  chainer/functions/array/split_axis.py
  chainer/functions/array/squeeze.py
  chainer/functions/array/stack.py
  chainer/functions/array/swapaxes.py
  chainer/functions/array/tile.py
  chainer/functions/array/transpose.py
  chainer/functions/array/transpose_sequence.py
  chainer/functions/array/vstack.py
  chainer/functions/array/where.py
Labels: cat:document, st:test-and-merge, to-be-backported

#5869 some small fixes to grammar and spelling
  chainer/dataset/convert.py
  chainer/dataset/iterator.py
  chainer/datasets/pickle_dataset.py
  chainer/functions/array/repeat.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/loss/contrastive.py
  chainer/functions/loss/ctc.py
  chainer/functions/loss/negative_sampling.py
  chainer/functions/math/average.py
  chainer/functions/math/inv.py
  chainer/gradient_check.py
  chainer/graph_optimizations/static_graph.py
  chainer/iterators/multiprocess_iterator.py
  chainer/iterators/multithread_iterator.py
  chainer/iterators/serial_iterator.py
  chainer/links/caffe/caffe_function.py
  chainer/links/loss/hierarchical_softmax.py
  chainer/links/model/classifier.py
  chainer/testing/condition.py
  chainer/training/extensions/parameter_statistics.py
  chainer/training/extensions/variable_statistics_plot.py
  chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
  docs/source/glance.rst
  docs/source/reference/iterators.rst
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
  tests/chainer_tests/utils_tests/test_type_check.py
Labels: cat:document

#5873 [backport] Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: backport, cat:document

#5859 Refactor Travis script
  .travis.yml
  scripts/ci/travis/run-tests.sh
Labels: cat:test, st:test-and-merge

#5886 [v5] Document optional arguments as `None`
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/deconvolution_nd.py
Labels: cat:document

#5828 Automatic ChainerX fallback of array attributes in `Function`
  chainer/function.py
  chainer/function_node.py
  tests/chainer_tests/test_backprop.py
Labels: ChainerX, cat:feature

#5879 Enable ChainerX in docker image
  docker/intel/python3/Dockerfile
  docker/python3/Dockerfile
Labels: ChainerX, cat:install

#5895 Accept splitting at the tail of dataset in `split_dataset`
  chainer/datasets/sub_dataset.py
  tests/chainer_tests/datasets_tests/test_sub_dataset.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#5894 Fix typo on internal attribute
  chainer/function.py
  chainer/function_node.py
Labels: ChainerX, cat:code-fix, st:test-and-merge

#5851 LocalResponseNormalization -> FunctionNode implementation
  chainer/functions/normalization/local_response_normalization.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#5776 Patch files for macOS
  chainerx_cc/CMakeLists.txt
  chainerx_cc/chainerx/CMakeLists.txt
  chainerx_cc/chainerx/context_testdata/CMakeLists.txt
  chainerx_cc/chainerx/native/native_device/memory.cc
  chainerx_cc/chainerx/python/CMakeLists.txt
  chainerx_cc/chainerx/python/routines.cc
  chainerx_cc/chainerx/python/testing/device_buffer.cc
  chainerx_cc/chainerx/testing/array.h
Labels: ChainerX

#5899 [backport] Accept splitting at the tail of dataset in `split_dataset`
  chainer/datasets/sub_dataset.py
  tests/chainer_tests/datasets_tests/test_sub_dataset.py
Labels: backport, cat:bug

#5807 Support custom initializer in links.CRF1d
  chainer/links/loss/crf1d.py
  tests/chainer_tests/links_tests/loss_tests/test_crf1d.py
Labels: cat:enhancement, st:test-and-merge

#5883 Fix `static_graph` module path in documentation
  docs/source/reference/static_graph.rst
  docs/source/reference/static_graph_design.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#5906 [backport] Fix `static_graph` module path in documentation
  docs/source/reference/static_graph.rst
  docs/source/reference/static_graph_design.rst
Labels: backport, cat:document

#5907 Change `.data` to `.array` in Guides and Examples docs
  docs/source/examples/mnist.rst
  docs/source/examples/train_loop.rst
  docs/source/guides/functions.rst
  docs/source/guides/links.rst
Labels: cat:example

#5913 [backport] Change `.data` to `.array` in Guides and Examples docs
  docs/source/examples/mnist.rst
  docs/source/examples/train_loop.rst
  docs/source/guides/functions.rst
  docs/source/guides/links.rst
Labels: backport, cat:document

#5806 Add test for conveter device argument in Evaluator
  tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
Labels: cat:test

#5915 fix typo
  docs/source/reference/datasets.rst
Labels: cat:document, to-be-backported

#5917 [backport] fix typo
  docs/source/reference/datasets.rst
Labels: backport, cat:document

#5900 [backport] LocalResponseNormalization -> FunctionNode implementation
  chainer/functions/normalization/local_response_normalization.py
Labels: backport, cat:enhancement

#5852 Write "Wx + b" in the document of `Linear`.
  chainer/functions/connection/linear.py
Labels: cat:document, to-be-backported

#5865 Remove some CI requirements
  setup.py
Labels: cat:test

#5868 Allow skipping linkcode in docs with environment variable
  docs/source/conf.py
Labels: cat:other

#5911 Update third-party.cmake to follow the recent way
  chainerx_cc/CMakeLists.txt
  chainerx_cc/cmake/third-party.cmake
  chainerx_cc/third_party/gsl-lite.cmake
  chainerx_cc/third_party/gtest.cmake
  chainerx_cc/third_party/optional-lite.cmake
  chainerx_cc/third_party/pybind11.cmake
Labels: ChainerX, cat:code-fix

#5534 Support inputs with ndim!=2 for `F.huber_loss`
  chainer/functions/loss/huber_loss.py
  tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
Labels: cat:enhancement, st:test-and-merge

#5871 Do not retain input on iDeep `F.relu`
  chainer/functions/activation/relu.py
Labels: cat:enhancement, st:test-and-merge

#5898 Fix broken `F.leaky_relu` grad when slope = 0
  chainer/functions/activation/leaky_relu.py
  tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#5922 [backport] Fix broken `F.leaky_relu` grad when slope = 0
  chainer/functions/activation/leaky_relu.py
  tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py
Labels: backport, cat:bug

#5919 [backport] Write "Wx + b" in the document of `Linear`.
  chainer/functions/connection/linear.py
Labels: backport, cat:document

#5912 Stop using unified memory by default
  chainerx_cc/chainerx/cuda/cuda_backend_test.cc
  chainerx_cc/chainerx/cuda/cuda_device_test.cc
  chainerx_cc/chainerx/cuda/memory_pool.cc
Labels: ChainerX, cat:enhancement, st:test-and-merge

#5901 Fix clang-tidy warnings on clang-tidy 6
  chainerx_cc/chainerx/context.cc
  chainerx_cc/chainerx/context_testdata/backend0.cc
  chainerx_cc/chainerx/context_testdata/backend1.cc
  chainerx_cc/chainerx/cuda/cuda.cc
  chainerx_cc/chainerx/cuda/cuda.h
  chainerx_cc/chainerx/cuda/cuda_backend.cc
  chainerx_cc/chainerx/cuda/cuda_backend.h
  chainerx_cc/chainerx/float16_test.cc
  chainerx_cc/chainerx/native/native_backend.cc
  chainerx_cc/chainerx/python/chainer_interop.cc
  chainerx_cc/chainerx/python/core_module.cc
  chainerx_cc/scripts/run-clang-tidy.sh
Labels: ChainerX, cat:code-fix, st:test-and-merge

#5926 [backport] Support all float dtypes in `F.embed_id`
  chainer/functions/connection/embed_id.py
  tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
Labels: backport, cat:feature

#5933 Fix for clang-tidy 7
  chainerx_cc/chainerx/python/graph.cc
  chainerx_cc/scripts/run-clang-tidy.sh
Labels: ChainerX, cat:code-fix, st:test-and-merge

#5831 [backport] Make docs of activation functions refer `ndarray`
  chainer/functions/activation/crelu.py
  chainer/functions/activation/elu.py
  chainer/functions/activation/hard_sigmoid.py
  chainer/functions/activation/leaky_relu.py
  chainer/functions/activation/log_softmax.py
  chainer/functions/activation/lstm.py
  chainer/functions/activation/maxout.py
  chainer/functions/activation/prelu.py
  chainer/functions/activation/relu.py
  chainer/functions/activation/rrelu.py
  chainer/functions/activation/selu.py
  chainer/functions/activation/sigmoid.py
  chainer/functions/activation/slstm.py
  chainer/functions/activation/softmax.py
  chainer/functions/activation/softplus.py
  chainer/functions/activation/swish.py
  chainer/functions/activation/tanh.py
  chainer/functions/activation/tree_lstm.py
Labels: backport, cat:document

#5881 [backport] Make docs of array functions refer `ndarray`
  chainer/functions/array/broadcast.py
  chainer/functions/array/cast.py
  chainer/functions/array/concat.py
  chainer/functions/array/copy.py
  chainer/functions/array/depth2space.py
  chainer/functions/array/diagonal.py
  chainer/functions/array/dstack.py
  chainer/functions/array/expand_dims.py
  chainer/functions/array/flatten.py
  chainer/functions/array/flip.py
  chainer/functions/array/fliplr.py
  chainer/functions/array/flipud.py
  chainer/functions/array/get_item.py
  chainer/functions/array/hstack.py
  chainer/functions/array/im2col.py
  chainer/functions/array/moveaxis.py
  chainer/functions/array/pad.py
  chainer/functions/array/pad_sequence.py
  chainer/functions/array/permutate.py
  chainer/functions/array/repeat.py
  chainer/functions/array/reshape.py
  chainer/functions/array/resize_images.py
  chainer/functions/array/rollaxis.py
  chainer/functions/array/scatter_add.py
  chainer/functions/array/select_item.py
  chainer/functions/array/separate.py
  chainer/functions/array/space2depth.py
  chainer/functions/array/spatial_transformer_grid.py
  chainer/functions/array/spatial_transformer_sampler.py
  chainer/functions/array/split_axis.py
  chainer/functions/array/squeeze.py
  chainer/functions/array/stack.py
  chainer/functions/array/swapaxes.py
  chainer/functions/array/tile.py
  chainer/functions/array/transpose.py
  chainer/functions/array/transpose_sequence.py
  chainer/functions/array/vstack.py
  chainer/functions/array/where.py
Labels: backport, cat:document, st:test-and-merge

#5889 [backport] Make docs of connection functions refer `ndarray`
  chainer/functions/connection/bilinear.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/deconvolution_nd.py
  chainer/functions/connection/deformable_convolution_2d_sampler.py
  chainer/functions/connection/depthwise_convolution_2d.py
  chainer/functions/connection/dilated_convolution_2d.py
  chainer/functions/connection/embed_id.py
  chainer/functions/connection/linear.py
  chainer/functions/connection/local_convolution_2d.py
  chainer/functions/connection/shift.py
Labels: backport, cat:document

#5867 Add C++ linter checks in Travis CI
  .travis.yml
  scripts/ci/travis/run-tests.sh
  setup.py
Labels: cat:test, st:test-and-merge

#5905 [backport] Support custom initializer in links.CRF1d
  chainer/links/loss/crf1d.py
  tests/chainer_tests/links_tests/loss_tests/test_crf1d.py
Labels: backport, cat:enhancement

#5928 Adjust testing tolerance of F.connectionist_temporal_classification
  tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Labels: cat:test

#5942 Fix typo
  docs/source/chainerx/tutorial/index.rst
Labels: ChainerX, cat:document, to-be-backported

#5923 Adjust testing tolerance of numerical gradient
  tests/chainer_tests/test_gradient_check.py
Labels: cat:test, to-be-backported

#5675 Add type hints for link, link_hook, Initializer and chainerx
  .gitignore
  appveyor.yml
  chainer/backend.py
  chainer/backends/_chainerx.py
  chainer/backends/cuda.py
  chainer/backends/intel64.py
  chainer/configuration.py
  chainer/function.py
  chainer/function_hooks/cupy_memory_profile.py
  chainer/functions/activation/clipped_relu.py
  chainer/functions/activation/log_softmax.py
  chainer/functions/activation/relu.py
  chainer/functions/activation/sigmoid.py
  chainer/functions/activation/softmax.py
  chainer/functions/activation/tanh.py
  chainer/functions/array/spatial_transformer_grid.py
  chainer/functions/array/spatial_transformer_sampler.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/normalization/batch_normalization.py
  chainer/functions/pooling/pooling_nd.py
  chainer/initializer.py
  chainer/initializers/__init__.py
  chainer/initializers/constant.py
  chainer/iterators/multiprocess_iterator.py
  chainer/link.py
  chainer/link_hook.py
  chainer/links/connection/linear.py
  chainer/optimizers/ada_delta.py
  chainer/optimizers/ada_grad.py
  chainer/optimizers/adam.py
  chainer/optimizers/corrected_momentum_sgd.py
  chainer/optimizers/momentum_sgd.py
  chainer/optimizers/msvag.py
  chainer/optimizers/nesterov_ag.py
  chainer/optimizers/rmsprop.py
  chainer/optimizers/rmsprop_graves.py
  chainer/optimizers/sgd.py
  chainer/optimizers/smorms3.py
  chainer/py.typed
  chainer/reporter.py
  chainer/types.py
  chainer/utils/__init__.py
  chainer/utils/type_check.py
  chainer/variable.py
  chainerx/__init__.pyi
  chainerx/py.typed
  chainerx_build_helper.py
  scripts/ci/chainerx/jenkins/run.sh
  scripts/ci/steps.sh
  scripts/ci/travis/run-tests.sh
  setup.cfg
  setup.py
Labels: cat:enhancement, st:test-and-merge

#5946 [backport] Adjust testing tolerance of numerical gradient
  tests/chainer_tests/test_gradient_check.py
Labels: backport, cat:test
