Repository chainer/chainer, pull requests merged in 2018-06, with the labels that each got.

#4614 simplify rsqrt
  chainer/functions/math/sqrt.py
Labels: enhancement, st:awaiting-response

#4591 Support grouped and dilated convolutions for ConvolutionND and DeconvolutionND
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_nd.py
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_nd.py
  chainer/utils/conv_nd.py
  chainer/utils/conv_nd_kernel.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
Labels: feature

#4829 Fix ResNetLayers pass wrong kwargs to Convolution2D
  chainer/links/model/vision/resnet.py
Labels: bug

#4830 v4: fix required version of CuPy
  setup.py
Labels: install

#4271 Add pix2pix example
  examples/pix2pix/README.md
  examples/pix2pix/facade_dataset.py
  examples/pix2pix/facade_visualizer.py
  examples/pix2pix/image/example.png
  examples/pix2pix/net.py
  examples/pix2pix/requirements.txt
  examples/pix2pix/train_facade.py
  examples/pix2pix/updater.py
Labels: example

#4836 Fix `F.rollaxis` backward when `axis=0` and `start=0`
  chainer/functions/array/rollaxis.py
  tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
Labels: bug, to-be-backported

#4162 Use input_num to remove array creation overhead
  chainer/functions/activation/lstm.py
Labels: enhancement

#4834 [backport] Replace ternary numpy.einsum
  chainer/functions/connection/bilinear.py
Labels: backport

#4774 Select devices appropriately when calling user code in ParallelUpdater
  chainer/training/updaters/parallel_updater.py
Labels: bug, to-be-backported

#4510 Add chainer.config.dtype and use it in initializers and dataset loaders.
  chainer/__init__.py
  chainer/datasets/cifar.py
  chainer/datasets/fashion_mnist.py
  chainer/datasets/image_dataset.py
  chainer/datasets/mnist.py
  chainer/datasets/svhn.py
  chainer/initializers/__init__.py
  docs/source/reference/configuration.rst
  docs/source/reference/initializers.rst
  tests/chainer_tests/initializer_tests/test_init.py
Labels: feature, st:test-and-merge

#4799 Allow more than 2 axis in `F.normalize`
  chainer/functions/normalization/l2_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: st:test-and-merge

#4809 Add Performance Best Practices document
  docs/source/index.rst
  docs/source/performance.rst
  docs/source/reference/configuration.rst
Labels: document, to-be-backported

#4716 Raise an error when `devices` argument given to `MultiprocessParallelUpdater` is not dict and list
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: bug, st:test-and-merge, to-be-backported

#4841 [backport] Fix input checks of `TestMin` and `TestMax`
  tests/chainer_tests/functions_tests/math_tests/test_minmax.py
Labels: backport, test

#4842 [backport] Select devices appropriately when calling user code in `ParallelUpdater`
  chainer/training/updaters/parallel_updater.py
Labels: backport, bug, st:test-and-merge

#4843 [backport] Fix `F.rollaxis` backward when `axis=0` and `start=0`
  chainer/functions/array/rollaxis.py
  tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
Labels: backport, bug, st:test-and-merge

#4837 Simplify classification custom loop example
  examples/mnist/train_mnist_custom_loop.py
Labels: enhancement, example, st:awaiting-response

#4052 Linking to Chainer function or Python function for docs
  chainer/function.py
  chainer/gradient_check.py
  chainer/links/connection/mlp_convolution_2d.py
  chainer/links/model/classifier.py
  chainer/optimizer.py
  chainer/training/triggers/minmax_value_trigger.py
  docs/source/reference/functions.rst
Labels: document, st:test-and-merge, to-be-backported

#4675 Add training mode checking to `extract` vision models (ResNet, VGG16, GoogLeNet).
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4694 Refactor sentiment example
  examples/sentiment/train_sentiment.py
Labels: example

#4848 Remove redundant device allocation in word2vec example
  examples/word2vec/train_word2vec.py
Labels: enhancement, st:test-and-merge, takeover, to-be-backported

#4849 Add call_for_each_param to docs
  chainer/optimizer_hooks/gradient_hard_clipping.py
  chainer/optimizer_hooks/gradient_lars.py
  chainer/optimizer_hooks/gradient_noise.py
  chainer/optimizer_hooks/lasso.py
  chainer/optimizer_hooks/weight_decay.py
Labels: document, to-be-backported

#4847 [backport] Raise an error when `devices` argument given to `MultiprocessParallelUpdater` is not dict and list
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: backport, bug

#4473 Add M-SVAG optimizer
  chainer/optimizers/__init__.py
  chainer/optimizers/msvag.py
  tests/chainer_tests/optimizers_tests/test_optimizers.py
  tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
Labels: feature

#4856 [backport] Remove redundant device allocation in word2vec example
  examples/word2vec/train_word2vec.py
Labels: backport, enhancement, st:test-and-merge, takeover

#4846 Remove deprecated imp.load_source in setup.py
  setup.py
Labels: install, st:test-and-merge, to-be-backported

#4785 Add type check trouble shooting to FAQ
  docs/source/tips.rst
Labels: document, to-be-backported

#3830 Support double-backprop in `F.contrastive`
  chainer/functions/loss/contrastive.py
  tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Labels: feature, st:test-and-merge, to-be-backported

#4750 [backport] Raise an error when CUDA has been initialized before MultiprocessParallelUpdater is initialized
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: backport, enhancement

#3436 Issue a warning when repeat property of some iterators in Evaluator is True.
  chainer/iterators/multithread_iterator.py
  chainer/iterators/serial_iterator.py
  chainer/training/extensions/evaluator.py
  tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
Labels: st:test-and-merge

#4819 [backport] Fix a documenation bug in `TransformDataset`
  chainer/datasets/transform_dataset.py
Labels: backport, document, st:test-and-merge

#4861 [backport] Support double-backprop in `F.contrastive`
  chainer/functions/loss/contrastive.py
  tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Labels: backport, feature, st:test-and-merge

#4863 Set output grad in `TestCUDAProfileHook`
  tests/chainer_tests/function_hooks_tests/test_cuda_profile.py
Labels: test, to-be-backported

#4859 [backport] Remove deprecated `imp.load_source` in `setup.py`
  setup.py
Labels: backport, install

#4867 [backport] Improve error message and exception type during `MultiprocessParallelUpdater` initialization
  chainer/training/updaters/multiprocess_parallel_updater.py
  tests/chainer_tests/training_tests/updaters_tests/snippets/cuda_init.py
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: backport, enhancement, st:test-and-merge

#4818 Correct docs of batch_{re}normalization about running averages
  chainer/functions/normalization/batch_normalization.py
  chainer/functions/normalization/batch_renormalization.py
Labels: document, st:test-and-merge, to-be-backported

#4865 [backport] Issue a warning when `repeat` attribute of some iterators in `Evaluator` is `True`
  chainer/iterators/multithread_iterator.py
  chainer/iterators/serial_iterator.py
  chainer/training/extensions/evaluator.py
  tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
Labels: backport, enhancement

#4782 Implement TextDataset to load line-oriented text files
  chainer/datasets/__init__.py
  chainer/datasets/text_dataset.py
  docs/source/reference/datasets.rst
  examples/seq2seq/seq2seq.py
  tests/chainer_tests/datasets_tests/test_text_dataset.py
  tests/chainer_tests/datasets_tests/text_dataset/ascii_1.txt
  tests/chainer_tests/datasets_tests/text_dataset/ascii_2.txt
  tests/chainer_tests/datasets_tests/text_dataset/ascii_blank_line.txt
  tests/chainer_tests/datasets_tests/text_dataset/ascii_noeol.txt
  tests/chainer_tests/datasets_tests/text_dataset/utf8_1.txt
  tests/chainer_tests/datasets_tests/text_dataset/utf8_2.txt
  tests/chainer_tests/datasets_tests/text_dataset/utf8_crlf.txt
  tests/chainer_tests/datasets_tests/text_dataset/utf8sig.txt
  tests/chainer_tests/test_runnable.py
Labels: feature, to-be-backported

#4740 Add small examples for serialization feature
  examples/serialization/README.md
  examples/serialization/load.py
  examples/serialization/model.py
  examples/serialization/save.py
Labels: example, st:test-and-merge

#4872 Mark multi_gpu tests as gpu tests
  chainer/testing/attr.py
Labels: test, to-be-backported

#4882 [backport] Remove flake8 from AppVeyor test
  appveyor.yml
  setup.py
Labels: backport, st:test-and-merge, test

#4881 [backport] Mark multi_gpu tests as gpu tests
  chainer/testing/attr.py
Labels: backport, test

#4565 Add `InverseShift` extension
  chainer/training/extensions/__init__.py
  chainer/training/extensions/inverse_shift.py
  docs/source/reference/training.rst
  tests/chainer_tests/training_tests/extensions_tests/test_inverse_shift.py
Labels: feature

#4770 Add __call__ method to Link for backward compatibility
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: other, st:test-and-merge, to-be-backported

#4880 Improve argument processing performance
  chainer/functions/array/spatial_transformer_grid.py
  chainer/functions/array/spatial_transformer_sampler.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/noise/dropout.py
  chainer/functions/noise/zoneout.py
  chainer/functions/normalization/batch_normalization.py
  chainer/links/caffe/caffe_function.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/deconvolution_2d.py
  chainer/links/connection/n_step_rnn.py
  chainer/links/connection/zoneoutlstm.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  chainer/links/normalization/batch_normalization.py
  chainer/training/extension.py
  chainer/training/trainer.py
  chainer/utils/argument.py
  chainer/variable.py
Labels: enhancement

#4835 Add `CorrectedMomentumSGD` optimizer
  chainer/optimizers/__init__.py
  chainer/optimizers/corrected_momentum_sgd.py
  docs/source/reference/optimizers.rst
  tests/chainer_tests/optimizers_tests/test_optimizers.py
  tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
Labels: feature

#2468 Add DeformableConvolution2D
  chainer/functions/__init__.py
  chainer/functions/connection/deformable_convolution_2d_sampler.py
  chainer/links/__init__.py
  chainer/links/connection/deformable_convolution_2d.py
  docs/source/reference/functions.rst
  docs/source/reference/links.rst
  tests/chainer_tests/functions_tests/connection_tests/test_deformable_convolution_2d_sampler.py
  tests/chainer_tests/links_tests/connection_tests/test_deformable_convolution_2d.py
Labels: feature

#4888 [backport] Raise an error if neither `__call__` nor `forward` is defined in a link
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: backport, other

#4900 Improve the documentation of `F.moveaxis` and discourage `F.rollaxis`
  chainer/functions/array/moveaxis.py
  chainer/functions/array/rollaxis.py
Labels: document

#4875 Support importing Caffe Reshape layer
  chainer/links/caffe/caffe_function.py
  tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
Labels: feature, to-be-backported

#4873 Deselect gpu tests instead of skipping them
  .travis.yml
  appveyor.yml
  chainer/testing/distribution_test.py
Labels: st:awaiting-response, test, to-be-backported

#4857 [backport] Document `call_for_each_param` attribute in optimizer hooks
  chainer/optimizer_hooks/gradient_hard_clipping.py
  chainer/optimizer_hooks/gradient_lars.py
  chainer/optimizer_hooks/gradient_noise.py
  chainer/optimizer_hooks/lasso.py
  chainer/optimizer_hooks/weight_decay.py
Labels: backport, document

#4868 Stop using freeze_running_statistics in TestFixedBatchRenormalization
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
Labels: st:test-and-merge, test, to-be-backported

#4869 Deprecate `F.fixed_batch_renormalization`
  chainer/functions/normalization/batch_renormalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
Labels: enhancement, to-be-backported

#4884 Fix Caffe exporter to export eps of BatchNormalization layer
  chainer/exporters/caffe.py
  tests/chainer_tests/exporters_tests/test_caffe.py
Labels: st:test-and-merge, test, to-be-backported

#4876 Catch warnings in `test_count_params`
  tests/chainer_tests/test_link.py
Labels: st:test-and-merge, test

#4779 Add backprop tests
  tests/chainer_tests/test_function_node.py
  tests/chainer_tests/test_variable.py
Labels: test, to-be-backported

#4908 [backport] Stop using freeze_running_statistics in TestFixedBatchRenormalization
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
Labels: backport, st:test-and-merge, test

#4905 [backport] Support importing Caffe Reshape layer
  chainer/links/caffe/caffe_function.py
  tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
Labels: backport, feature, st:test-and-merge

#4906 [backport] Deselect gpu tests instead of skipping them
  .travis.yml
  appveyor.yml
Labels: backport, st:test-and-merge, test

#4918 Tentatively restrict pytest-timeout version to <1.3.0
  setup.py
Labels: test, to-be-backported

#4919 [backport] Tentatively restrict pytest-timeout version to <1.3.0
  setup.py
Labels: backport, st:test-and-merge, test

#4915 Fix `SigmoidCrossEntropy.backward`
  chainer/functions/loss/sigmoid_cross_entropy.py
  chainer/gradient_check.py
  tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
Labels: bug, st:test-and-merge

#4926 [backport] Quote example codes properly in `gradient_check`
  chainer/gradient_check.py
Labels: backport, document

#4928 Fix ValueError in caffe exporter on Windows with Python 2.7
  chainer/exporters/caffe.py
Labels: bug, to-be-backported

#4921 Replace 0xa0 (nbsp) with 0x20 (space) in documentation
  docs/source/examples/train_loop.rst
Labels: document, st:test-and-merge, to-be-backported

#4917 Check docs build in Travis CI
  .travis.yml
  setup.py
Labels: st:test-and-merge, test, to-be-backported

#4930 [backport] Replace 0xa0 (nbsp) with 0x20 (space) in documentation
  docs/source/examples/train_loop.rst
Labels: backport, document, st:test-and-merge

#4929 [backport] Fix ValueError in caffe exporter on Windows with Python 2.7
  chainer/exporters/caffe.py
Labels: backport, bug, st:test-and-merge

#4886 Add distribution reference
  chainer/distribution.py
  docs/source/reference/distributions.rst
  docs/source/reference/index.rst
Labels: document

#4896 Remove experimental warning
  chainer/exporters/caffe.py
  chainer/function_node.py
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/unpooling_nd.py
  chainer/functions/theano/theano_function.py
  chainer/links/connection/tree_lstm.py
  chainer/links/normalization/layer_normalization.py
  chainer/links/theano/theano_function.py
Labels: other

#4934 Suggest users to use iDeep4py v1 for now
  docs/source/tips.rst
Labels: document, to-be-backported

#4914 Delete redundant `no_grads` from test
  tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
Labels: test, to-be-backported

#4936 Add support for importing and exporting Caffe Deconvolution layer
  chainer/exporters/caffe.py
  chainer/links/caffe/caffe_function.py
  tests/chainer_tests/exporters_tests/test_caffe.py
  tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
Labels: feature, to-be-backported

#4680 assign user-friendly name for better type check exception message
  chainer/functions/connection/linear.py
  chainer/functions/loss/sigmoid_cross_entropy.py
  chainer/functions/loss/softmax_cross_entropy.py
  chainer/utils/type_check.py
Labels: enhancement

#4924 [v4] Fix `SigmoidCrossEntropy.backward`
  chainer/functions/loss/sigmoid_cross_entropy.py
  tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
Labels: backport, bug

#4931 [backport] Check docs build in Travis CI
  .travis.yml
  setup.py
Labels: backport, st:test-and-merge, test

#4660 Support remove/replace child link in ChainList #4659
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: feature

#4937 Add support for exporting Caffe LeakyReLU layer
  chainer/exporters/caffe.py
  tests/chainer_tests/exporters_tests/test_caffe.py
Labels: feature, st:test-and-merge

#4938 [backport] Delete redundant `no_grads` from test
  tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
Labels: backport, test

#4892 [fix] normal document
  chainer/distributions/normal.py
Labels: document

#4855 Improve function reference and documentation
  chainer/links/connection/mlp_convolution_2d.py
  chainer/links/model/classifier.py
  chainer/optimizer.py
  docs/source/guides/functions.rst
  docs/source/reference/functions.rst
Labels: document, st:test-and-merge, to-be-backported

#4850 [backport] Improve documentation about wrapper functions
  chainer/function.py
  chainer/gradient_check.py
  chainer/links/connection/mlp_convolution_2d.py
  chainer/links/model/classifier.py
  chainer/optimizer.py
  chainer/training/triggers/minmax_value_trigger.py
  docs/source/reference/functions.rst
Labels: backport, document, st:blocked-by-another-pr

#4941 [backport] Add training mode checking to `extract` vision models (ResNet, VGG16, GoogLeNet).
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: backport, enhancement

#4845 Remove wrong length check from `GetItem.check_type_forward`
  chainer/functions/array/get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_get_item.py
Labels: bug, to-be-backported

#4944 [backport] Remove wrong-length check from `GetItem.check_type_forward`
  chainer/functions/array/get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_get_item.py
Labels: backport, bug, st:test-and-merge

#4942 [backport] Add Performance Best Practices document
  docs/source/index.rst
  docs/source/performance.rst
  docs/source/reference/configuration.rst
Labels: backport, document, st:test-and-merge

#4654 Fix no_grads option of check_backward
  chainer/gradient_check.py
  tests/chainer_tests/test_gradient_check.py
Labels: bug, document, no-compat, st:test-and-merge

#4608 Make updaters call `new_epoch` automatically
  chainer/optimizer.py
  chainer/training/updaters/multiprocess_parallel_updater.py
  chainer/training/updaters/parallel_updater.py
  chainer/training/updaters/standard_updater.py
  tests/chainer_tests/test_optimizer.py
  tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py
Labels: feature, no-compat, st:test-and-merge

#4679 Automatic broadcast in basic_math and matmul
  chainer/functions/__init__.py
  chainer/functions/array/broadcast.py
  chainer/functions/math/basic_math.py
  chainer/functions/math/matmul.py
  chainer/functions/math/sum.py
  chainer/utils/__init__.py
  chainer/utils/array.py
  chainer/utils/type_check.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
  tests/chainer_tests/functions_tests/math_tests/test_matmul.py
  tests/chainer_tests/utils_tests/test_array.py
Labels: feature

#4943 [backport] Improve function reference and documentation
  chainer/links/connection/mlp_convolution_2d.py
  chainer/links/model/classifier.py
  chainer/optimizer.py
  docs/source/guides/functions.rst
  docs/source/reference/functions.rst
Labels: backport, document, st:test-and-merge

#4916 [backport] Add backprop tests
  tests/chainer_tests/test_function_node.py
  tests/chainer_tests/test_variable.py
Labels: backport, test

#4901 Add `F.diagonal`
  chainer/functions/__init__.py
  chainer/functions/array/diagonal.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/array_tests/test_diagonal.py
Labels: feature, st:test-and-merge

#4890 Implement `return_indices` option to `F.max_pooling_2d`
  chainer/functions/pooling/max_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4949 Raise an error on 0-dim input to matmul
  chainer/functions/math/matmul.py
  tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
Labels: bug

#4945 Fix operations in ChainList
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: bug, st:test-and-merge

#4895 Fix Adam alpha argument explanation
  chainer/optimizers/adam.py
Labels: document, to-be-backported

#4638 Add Group Normalization
  chainer/functions/__init__.py
  chainer/functions/normalization/group_normalization.py
  chainer/links/__init__.py
  chainer/links/normalization/group_normalization.py
  docs/source/reference/functions.rst
  docs/source/reference/links.rst
  tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
Labels: feature, st:test-and-merge

#4891 Implement `return_indices` option to `F.max_pooling_nd`
  chainer/functions/pooling/max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4907 Implement mask and return_mask option to `F.dropout`
  chainer/functions/noise/dropout.py
  tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4909 Implement eps and return_eps option to `F.gaussian`
  chainer/functions/noise/gaussian.py
  tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4940 [backport] Deprecate `F.fixed_batch_renormalization`
  chainer/functions/normalization/batch_renormalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
Labels: backport, enhancement

#4952 [backport] Implement `return_indices` option to `F.max_pooling_2d`
  chainer/functions/pooling/max_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
Labels: backport, enhancement, st:test-and-merge

#4953 [backport] Implement `return_indices` option to `F.max_pooling_nd`
  chainer/functions/pooling/max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
Labels: backport, enhancement, st:test-and-merge

#4955 [backport] Implement eps and return_eps option to `F.gaussian`
  chainer/functions/noise/gaussian.py
  tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
Labels: backport, enhancement, st:test-and-merge

#4828 Add testing utilities to documents
  chainer/testing/helper.py
  docs/source/reference/check.rst
Labels: document, feature, st:test-and-merge

#4954 [backport] Add `mask` and `return_mask` option to `F.dropout`
  chainer/functions/noise/dropout.py
  tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
Labels: backport, enhancement, st:test-and-merge

#4771 Fix occasional test failure of `F.average` by changing lower-bound of weight.sum
  tests/chainer_tests/functions_tests/math_tests/test_average.py
Labels: test, to-be-backported

#4947 Simplify `Broadcast.check_type_forward`
  chainer/functions/array/broadcast.py
  tests/chainer_tests/functions_tests/array_tests/test_broadcast.py
Labels: enhancement, st:test-and-merge

#4871 Improve Batch Renormalization tests
  chainer/functions/normalization/batch_renormalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py
Labels: feature, st:test-and-merge, test

#4714 Improve CNN example docs
  docs/source/examples/cnn.rst
Labels: document, to-be-backported

#4959 Add `ZippedImageDataset` and `MultiZippedImageDataset` to document
  docs/source/reference/datasets.rst
Labels: document, to-be-backported

#4960 [backport] Fix occasional test failure of `F.average` by changing lower-bound of weight.sum
  tests/chainer_tests/functions_tests/math_tests/test_average.py
Labels: backport, test

#4965 Fix kwarg name in `TestResNetLayers`
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: test

#4673 Infer input size in batchnorm using aggregate axes
  chainer/links/normalization/batch_normalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: enhancement, st:test-and-merge, takeover, to-be-backported

#4966 Remove unnecessary tests
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: test, to-be-backported

#4923 Refactor distribution
  chainer/distributions/normal.py
  chainer/testing/distribution_test.py
  tests/chainer_tests/distributions_tests/test_normal.py
Labels: test

#4963 [backport] Add `ZippedImageDataset` and `MultiZippedImageDataset` to documentation
  docs/source/reference/datasets.rst
Labels: backport, document

#4956 Add upgrade guide for `auto_new_epoch`
  docs/source/upgrade.rst
Labels: document

#4981 Fix docs of `chainer.config.dtype`
  docs/source/reference/configuration.rst
Labels: document

#4964 Cleanup batch_normalization
  chainer/functions/normalization/batch_normalization.py
Labels: enhancement, to-be-backported

#4970 [backport] Fix Adam alpha argument explanation
  chainer/optimizers/adam.py
Labels: backport, document

#4968 Fix cross-reference links in StandardUpdater
  chainer/training/updaters/standard_updater.py
Labels: document

#4975 Fix invalid keyword arguments to `L.Linear` in ImageNet example
  examples/imagenet/googlenetbn.py
Labels: example, to-be-backported

#4993 [backport] Fix cross-reference links in StandardUpdater
  chainer/training/updaters/standard_updater.py
Labels: backport, document

#4992 Update docs in upsampling_2d according to new max_pooling_2d
  chainer/functions/pooling/upsampling_2d.py
Labels: document, st:test-and-merge, to-be-backported

#4994 [backport] Fix invalid keyword arguments to `L.Linear` in ImageNet example
  examples/imagenet/googlenetbn.py
Labels: backport, example, st:test-and-merge

#4991 Fix docs of n_step_rnn and n_step_lstm
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
Labels: document, st:test-and-merge, to-be-backported

#4995 [backport] Update docs in upsampling_2d according to new max_pooling_2d
  chainer/functions/pooling/upsampling_2d.py
Labels: backport, document, st:test-and-merge

#4990 Support NumPy 1.14 in docs
  docs/source/install.rst
Labels: document, to-be-backported

#4982 Run gradient clipping on GPU, if possible
  chainer/optimizer_hooks/gradient_clipping.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4998 [backport] Fix docstrings in computational_graph
  chainer/computational_graph.py
Labels: backport, document

#3369 Support cuDNN in F.dropout
  chainer/backends/cuda.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/noise/dropout.py
  tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
Labels: enhancement

#5001 Fix `test_default_backward`
  tests/chainer_tests/test_variable.py
Labels: test, to-be-backported

#5002 Fix verb error in chainer.functions.fft docstring
  chainer/functions/math/fft.py
Labels: document, to-be-backported

#4999 [backport] Support NumPy 1.14 in docs
  docs/source/install.rst
Labels: backport, document, st:test-and-merge

#4996 [backport] Fix docs of n_step_rnn and n_step_lstm
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
Labels: backport, document, st:test-and-merge

#4971 Fix exception not raised when unsupported format is specified when dumping computational graph
  chainer/computational_graph.py
  tests/chainer_tests/test_computational_graph.py
Labels: bug, st:test-and-merge, to-be-backported

#5004 [backport] Fix verb error in chainer.functions.fft docstring
  chainer/functions/math/fft.py
Labels: backport, document, st:test-and-merge

#5003 [backport] Fix `test_default_backward`
  tests/chainer_tests/test_variable.py
Labels: backport, st:test-and-merge, test

#5000 [backport] Run gradient clipping on GPU, if possible
  chainer/optimizer_hooks/gradient_clipping.py
Labels: backport, enhancement, st:test-and-merge

#5006 Typo
  chainer/functions/connection/n_step_gru.py
Labels: document, to-be-backported

#5005 [backport] Fix exception not raised when unsupported format is specified when dumping computational graph
  chainer/computational_graph.py
  tests/chainer_tests/test_computational_graph.py
Labels: backport, bug, st:test-and-merge

#4932 Add Laplace distribution
  chainer/distributions/__init__.py
  chainer/distributions/laplace.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_laplace.py
Labels: enhancement

#5007 [backport] Fix typo in `n_step_gru` docs
  chainer/functions/connection/n_step_gru.py
Labels: backport, document

#5016 Remove unused parameter from `TestBatchRenormalization`
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
Labels: test, to-be-backported

#5010 Add notes about relationship between dilated_convolution_2d and convolution_2d
  chainer/functions/connection/dilated_convolution_2d.py
  chainer/links/connection/dilated_convolution_2d.py
Labels: document, to-be-backported

#5022 [backport] Fix typo in README of seq2seq
  examples/seq2seq/README.md
Labels: backport, document

#4983 Clarifications for L.Linear
  chainer/links/connection/linear.py
Labels: document, to-be-backported

#5011 Fix broken notations in `F.linear` docs
  chainer/functions/connection/linear.py
Labels: document, to-be-backported
