Repository chainer/chainer, pull requests merged in 2018-09, with the labels that each got.

#5284 Support all float dtypes in `F.gaussian`
  chainer/functions/noise/gaussian.py
  tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
Labels: feature

#5281 Support all float dtypes in `F.roi_pooling_2d`
  chainer/functions/pooling/roi_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
Labels: feature

#5272 Update issue-template to encourage users to use `chainer.print_runtime_info`
  .github/ISSUE_TEMPLATE.md
Labels: other

#5213 Add `L.VGG19Layers`
  chainer/links/__init__.py
  chainer/links/model/vision/vgg.py
  docs/source/reference/links.rst
  tests/chainer_tests/links_tests/model_tests/test_vision.py
Labels: feature

#5283 Add explanation about switching the three modes.
  chainer/links/normalization/batch_normalization.py
Labels: document, st:test-and-merge, to-be-backported

#5299 [v4] Amend chainer.Chain document
  chainer/link.py
Labels: document

#5294 Amend chainer.Chain document
  chainer/link.py
Labels: document

#5307 remove deprecated is_linear arg
  tests/chainer_tests/testing_tests/test_unary_math_function_test.py
Labels: test

#5318 Add quotes to stylecheck install
  docs/source/contribution.rst
Labels: document, st:test-and-merge, to-be-backported

#5316 Update Chainer at a Glance
  docs/image/glance/trainer-dataset.png
  docs/image/glance/trainer-extensions.png
  docs/image/glance/trainer-iterator.png
  docs/image/glance/trainer-model.png
  docs/image/glance/trainer-optimizer.png
  docs/image/glance/trainer-trainer.png
  docs/image/glance/trainer-updater.png
  docs/source/glance.rst
  examples/glance/README.md
  examples/glance/glance.py
  examples/glance/mushrooms.csv
Labels: document

#5296 Fix location of chainermn docs in sidebar
  docs/source/index.rst
Labels: ChainerMN, document

#5325 fix extensions.snapshot()
  examples/cifar/train_cifar.py
Labels: bug, example, to-be-backported

#5317 Fix invalid escape sequence warnings in Python 3.6
  .travis.yml
  chainer/functions/connection/linear.py
  chainer/links/connection/linear.py
  chainer/optimizer_hooks/gradient_lars.py
  chainer/training/extensions/step_shift.py
  chainer/training/extensions/variable_statistics_plot.py
  examples/memnn/memnn.py
  tests/chainer_tests/function_hooks_tests/test_debug_print.py
  tests/chainer_tests/utils_tests/test_argument.py
Labels: document, st:test-and-merge, to-be-backported

#5331 [backport] Fix snapshot trigger in CIFAR example
  examples/cifar/train_cifar.py
Labels: backport, bug, example

#5188 Fix `FunctionHook` documentation
  chainer/function_hook.py
Labels: document

#5339 [backport] Fix `FunctionHook` documentation
  chainer/function_hook.py
Labels: backport, document

#5298 Avoid using `pkg_resources` to retrieve Chainer version
  chainermn/__init__.py
Labels: ChainerMN, other

#5334 [backport] Fix invalid escape sequence warnings in Python 3.6
  .travis.yml
  chainer/optimizer_hooks/gradient_lars.py
  chainer/training/extensions/variable_statistics_plot.py
  tests/chainer_tests/function_hooks_tests/test_debug_print.py
  tests/chainer_tests/utils_tests/test_argument.py
Labels: backport, document

#5346 Fix typo
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: document, to-be-backported

#5344 Move `copyto` to `chainer.backend`
  chainer/_backprop_utils.py
  chainer/backend.py
  chainer/backends/__init__.py
  chainer/function_node.py
  chainer/link.py
  chainer/variable.py
  docs/source/reference/util/cuda.rst
  tests/chainer_tests/test_backend.py
Labels: enhancement, st:test-and-merge

#5348 [backport] Fix typo
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: backport, document

#4851 Add 1d/3d aliases for convolution/pooling functions and links
  chainer/functions/__init__.py
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_nd.py
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/unpooling_nd.py
  chainer/links/__init__.py
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_nd.py
  docs/source/reference/functions.rst
  docs/source/reference/links.rst
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_nd.py
  tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py
Labels: feature

#5069 Add a comment that explains why the Classifier chain clears Variable attribues.
  chainer/links/model/classifier.py
Labels: document

#5333 Fix PrintHook fails if grad is None
  chainer/function_hooks/debug_print.py
Labels: bug, to-be-backported

#5359 Fix sphinx version to 1.7.9
  setup.py
Labels: document, st:test-and-merge, to-be-backported

#5328 Disallow summing over ellipsis in `F.einsum`
  chainer/functions/math/einsum.py
  tests/chainer_tests/functions_tests/math_tests/test_einsum.py
Labels: enhancement

#5291 Fix Dockerfile in v4 branch to use CuPy minor versions
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: other

#5361 [backport] Fix PrintHook fails if grad is None
  chainer/function_hooks/debug_print.py
Labels: backport, bug

#5322 Make link.to_*pu return self
  chainer/links/connection/gru.py
  chainer/links/connection/lstm.py
  chainer/links/connection/mgu.py
  chainer/links/connection/peephole.py
  chainer/links/connection/zoneoutlstm.py
  chainer/links/loss/black_out.py
  chainer/links/loss/hierarchical_softmax.py
  chainer/links/loss/negative_sampling.py
Labels: bug, to-be-backported

#5362 [backport] Make link.to_*pu return self
  chainer/links/connection/gru.py
  chainer/links/connection/lstm.py
  chainer/links/connection/mgu.py
  chainer/links/connection/peephole.py
  chainer/links/connection/zoneoutlstm.py
  chainer/links/loss/black_out.py
  chainer/links/loss/hierarchical_softmax.py
  chainer/links/loss/negative_sampling.py
Labels: backport, bug

#5330 Automatic broadcast: minimum, maximum, where
  chainer/functions/array/where.py
  chainer/functions/math/maximum.py
  chainer/functions/math/minimum.py
  tests/chainer_tests/functions_tests/array_tests/test_where.py
  tests/chainer_tests/functions_tests/math_tests/test_maximum.py
  tests/chainer_tests/functions_tests/math_tests/test_minimum.py
Labels: feature

#5366 Avoid printing in test_kldivergence
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: test

#5329 Stabilize backward tests in TestTriangularInv
  tests/chainer_tests/distributions_tests/test_multivariate_normal.py
Labels: test

#5349 Fix input variable of FunctionNode of `permutate`
  chainer/functions/array/permutate.py
  chainer/links/connection/n_step_rnn.py
  tests/chainer_tests/functions_tests/array_tests/test_permutate.py
  tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py
Labels: bug, enhancement

#5345 Add long_description for PyPI
  MANIFEST.in
  README.md
  setup.py
Labels: document, st:test-and-merge, to-be-backported

#5373 Make deserializers overwrite `intel64.mdarray`
  chainer/serializers/hdf5.py
  chainer/serializers/npz.py
  tests/chainer_tests/serializers_tests/test_hdf5.py
  tests/chainer_tests/serializers_tests/test_npz.py
Labels: bug, to-be-backported

#5305 refine roi_average_align_2d interface
  chainer/functions/__init__.py
  chainer/functions/pooling/roi_average_align_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py
Labels: domain:cv, feature

#5377 [backport] Make deserializers overwrite `intel64.mdarray`
  chainer/serializers/hdf5.py
  chainer/serializers/npz.py
  tests/chainer_tests/serializers_tests/test_hdf5.py
  tests/chainer_tests/serializers_tests/test_npz.py
Labels: backport, bug

#5115 Add Dirichlet distribution
  chainer/distributions/__init__.py
  chainer/distributions/dirichlet.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_dirichlet.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: feature

#5384 Mention chainer.backend in upgrade guide
  docs/source/upgrade.rst
Labels: document

#5358 Fix dead link
  docs/source/glance.rst
Labels: document

#5369 Fix tolerance of matmul tests
  tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
  tests/chainer_tests/functions_tests/math_tests/test_matmul.py
Labels: test

#4925 [RFC] Add `params` and `xp` to `Distribution`
  chainer/distribution.py
  chainer/distributions/normal.py
Labels: feature

#5387 [takeover] Support DALI
  chainer/iterators/__init__.py
  chainer/iterators/dali_iterator.py
  docs/source/reference/iterators.rst
  examples/imagenet/dali_util.py
  examples/imagenet/train_imagenet.py
Labels: example, feature

#4544 Add DCGAN tutorial
  docs/image/dcgan/class-generative-model.png
  docs/image/dcgan/dcgan.png
  docs/image/dcgan/gan-overview.png
  docs/image/dcgan/generated-image-epoch1000.png
  docs/image/dcgan/generated-images.gif
  docs/image/dcgan/update-gan.png
  docs/source/examples/dcgan.rst
  docs/source/examples/index.rst
  docs/source/guides/models.rst
  examples/dcgan/train_dcgan.py
Labels: document

#5397 Fix typo in setup.py
  setup.py
Labels: install, st:test-and-merge, to-be-backported

#5300 Merge ChainerMN docs from master branch
  docs/source/chainermn/installation/guide.rst
  docs/source/chainermn/tutorial/tips_faqs.rst
Labels: ChainerMN, document

#5312 Remove unnecessary version checking in ChainerMN
  chainermn/functions/point_to_point_communication.py
  chainermn/links/batch_normalization.py
  chainermn/links/n_step_rnn.py
Labels: ChainerMN, st:test-and-merge, to-be-backported

#5398 [backport] Fix typo in setup.py
  setup.py
Labels: backport, install

#5395 [backport] Travis test against v5 branch
  .travis.yml
Labels: backport, test

#5400 [backport] Remove unnecessary version checking in ChainerMN
  chainermn/functions/point_to_point_communication.py
  chainermn/links/batch_normalization.py
  chainermn/links/n_step_rnn.py
Labels: ChainerMN, backport
