Repository chainer/chainer, pull requests merged in 2018-02, with the labels that each got.

#4300 Avoid keeping reference to function nodes in CupyMemoryProfileHook
  chainer/function_hooks/cupy_memory_profile.py
  tests/chainer_tests/function_hooks_tests/test_cupy_memory_profile.py
Labels: enhancement, no-compat

#4157 Fixing a minor notation error on the description of n_step_bigru
  chainer/functions/connection/n_step_gru.py
Labels: document, to-be-backported

#4321 [backport] Fix notation error
  chainer/functions/connection/n_step_gru.py
Labels: backport, document

#4323 Avoid keeping reference to function nodes in TimerHook
  chainer/function_hooks/timer.py
  tests/chainer_tests/function_hooks_tests/test_timer.py
Labels: enhancement, no-compat

#4317 Use version in external URL
  docs/source/conf.py
  docs/source/contribution.rst
  docs/source/tutorial/basic.rst
  docs/source/tutorial/function.rst
  docs/source/tutorial/gpu.rst
  docs/source/tutorial/ptb.rst
  docs/source/tutorial/recurrentnet.rst
  docs/source/tutorial/word2vec.rst
Labels: document, st:test-and-merge, to-be-backported

#4276 iDeep (basic part)
  .travis.yml
  appveyor.yml
  chainer/__init__.py
  chainer/backends/cuda.py
  chainer/backends/intel64.py
  chainer/function_node.py
  chainer/link.py
  chainer/testing/attr.py
  chainer/testing/backend.py
  chainer/utils/type_check.py
  chainer/variable.py
  tests/chainer_tests/test_link.py
  tests/chainer_tests/test_variable.py
Labels: feature

#4322 Fix docstring
  chainer/links/connection/inceptionbn.py
Labels: document, to-be-backported

#4327 [backport] Use version in external URL
  docs/source/conf.py
  docs/source/contribution.rst
  docs/source/tutorial/basic.rst
  docs/source/tutorial/function.rst
  docs/source/tutorial/gpu.rst
  docs/source/tutorial/recurrentnet.rst
Labels: backport, document

#4330 [backport] Fix docstring
  chainer/links/connection/inceptionbn.py
Labels: backport, document, st:test-and-merge

#4186 Fix backward_accumulate to accept only tuples
  chainer/function_node.py
  chainer/variable.py
Labels: bug, to-be-backported

#4283 iDeep: F.lstm and F.tree_lstm
  chainer/functions/activation/lstm.py
  chainer/functions/activation/tree_lstm.py
  tests/chainer_tests/functions_tests/activation_tests/test_lstm.py
Labels: feature

#4048 Fix initialization of random vectors in the test for RNNs
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: st:test-and-merge, test, to-be-backported

#4335 [backport] Fix initialization of random vectors in the test for RNNs
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: backport, test

#4278 iDeep: F.linear
  chainer/functions/connection/linear.py
  tests/chainer_tests/functions_tests/connection_tests/test_linear.py
Labels: feature

#4277 iDeep: F.relu
  chainer/functions/activation/relu.py
  tests/chainer_tests/functions_tests/activation_tests/test_relu.py
Labels: feature

#4338 Remove redundant stack
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: enhancement, to-be-backported

#3846 Add the error function (erf)
  chainer/functions/__init__.py
  chainer/functions/math/erf.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_erf.py
Labels: feature

#4288 iDeep: F.dropout
  chainer/functions/noise/dropout.py
  tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
Labels: feature

#4340 [backport] Remove redundant stack
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: backport, enhancement

#4280 iDeep: F.batch_normalization
  chainer/functions/normalization/batch_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Labels: feature

#4334 [backport] Fix backward_accumulate to accept only tuples
  chainer/function_node.py
  chainer/variable.py
Labels: backport, bug

#4324 add function hook changes to upgrade guide
  docs/source/upgrade.rst
Labels: document, st:test-and-merge

#4281 iDeep: F.split_axis
  chainer/functions/array/split_axis.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: feature, st:test-and-merge

#4286 iDeep: F.max_pooling_2d
  chainer/functions/pooling/max_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
Labels: feature, st:test-and-merge

#4315 Apply https in supported websites in the document
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  appveyor.yml
  appveyor/install.ps1
  appveyor/run_with_env.cmd
  chainer/functions/activation/tree_lstm.py
  chainer/functions/array/get_item.py
  chainer/functions/connection/bilinear.py
  chainer/functions/connection/depthwise_convolution_2d.py
  chainer/functions/loss/crf1d.py
  chainer/functions/loss/ctc.py
  chainer/functions/noise/simplified_dropconnect.py
  chainer/functions/normalization/local_response_normalization.py
  chainer/functions/pooling/roi_pooling_2d.py
  chainer/links/activation/simplified_dropconnect.py
  chainer/links/connection/gru.py
  chainer/links/connection/tree_lstm.py
  chainer/links/model/vision/vgg.py
  chainer/optimizers/adam.py
  chainer/optimizers/nesterov_ag.py
  chainer/optimizers/rmsprop_graves.py
  chainer/training/extensions/plot_report.py
  docs/source/compatibility.rst
  docs/source/conf.py
  docs/source/contribution.rst
  docs/source/install.rst
  docs/source/tips.rst
  docs/source/tutorial/gpu.rst
  docs/source/tutorial/train_loop.rst
  docs/source/tutorial/trainer.rst
  examples/image_captioning/README.md
  examples/pos/README.md
  examples/reinforcement_learning/dqn_cartpole.py
  examples/sentiment/download.py
  examples/seq2seq/README.md
  examples/text_classification/README.md
  examples/text_classification/text_datasets.py
  tests/chainer_tests/dataset_tests/test_download.py
Labels: document, st:test-and-merge

#4289 iDeep: F.concat
  chainer/functions/array/concat.py
  tests/chainer_tests/functions_tests/array_tests/test_concat.py
Labels: feature, st:test-and-merge

#4285 iDeep: optimizers.SGD and optimizers.MomentumSGD
  chainer/optimizers/momentum_sgd.py
  chainer/optimizers/sgd.py
  tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
Labels: feature, st:test-and-merge

#4346 Fix error messages for incompatible arrays
  chainer/function_node.py
  docs/source/upgrade.rst
Labels: document

#4344 Accept concat array in NStepRNNs
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: enhancement, st:test-and-merge

#4348 Cast to int type in split_axis
  chainer/functions/array/split_axis.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: bug

#4284 iDeep: F.convolution_2d and F.deconvolution_2d
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
Labels: feature

#4347 Improve ELU.backward
  chainer/functions/activation/elu.py
Labels: bug, st:test-and-merge, to-be-backported

#4331 Fix some inconsistency in gradient variable names.
  chainer/functions/activation/sigmoid.py
  chainer/functions/activation/softplus.py
  chainer/functions/activation/tanh.py
  chainer/functions/array/select_item.py
  chainer/functions/math/basic_math.py
  chainer/functions/math/batch_l2_norm_squared.py
  chainer/functions/math/linear_interpolate.py
  chainer/functions/math/matmul.py
  chainer/functions/math/trigonometric.py
Labels: enhancement, st:test-and-merge

#4268 [backport] Fix backward of NormalizeL2
  chainer/functions/normalization/l2_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: backport, bug

#4356 use get_device_from_id instead of get_device
  chainer/links/normalization/batch_renormalization.py
Labels: st:test-and-merge, to-be-backported

#4359 Avoid mutable default argument
  chainer/serializers/npz.py
  chainer/testing/training.py
  chainer/training/trainer.py
  tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py
Labels: st:test-and-merge

#4358 Simplify chained comparison
  chainer/testing/attr.py
Labels: st:test-and-merge, to-be-backported

#4357 Remove redundant brackets
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
Labels: st:test-and-merge

#4360 [backport] use get_device_from_id instead of get_device
  chainer/links/normalization/batch_renormalization.py
Labels: backport

#4361 [backport] Avoid mutable default argument
  tests/chainer_tests/training_tests/test_updater.py
Labels: backport, test

#4362 [backport] Simplify chained comparison
  chainer/testing/attr.py
Labels: backport

#3402 Fix crash bug when a child is reporting a value when using MultiprocessParallelUpdater
  chainer/training/updaters/multiprocess_parallel_updater.py
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: bug, st:test-and-merge, to-be-backported

#4363 Support cupyx namespace
  chainer/backends/cuda.py
  chainer/functions/array/resize_images.py
  chainer/functions/array/scatter_add.py
  chainer/functions/array/spatial_transformer_sampler.py
Labels: enhancement

#3816 Fix casing of header in README
  README.md
Labels: document

#4341 Refactor RNNs
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: enhancement, st:test-and-merge

#4376 Revert "Skip multiprocess_parallel_updater test for timeout"
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: st:test-and-merge, test

#4037 fix sphinx build option assignment in Makefile
  docs/Makefile
Labels: document, to-be-backported

#3241 Reorganize tutorial & add new contents
  docs/source/examples/cnn.rst
  docs/source/examples/index.rst
  docs/source/examples/mnist.rst
  docs/source/examples/ptb.rst
  docs/source/examples/rnn.rst
  docs/source/examples/train_loop.rst
  docs/source/examples/word2vec.rst
  docs/source/guides/define_by_run.rst
  docs/source/guides/extensions.rst
  docs/source/guides/functions.rst
  docs/source/guides/gpu.rst
  docs/source/guides/index.rst
  docs/source/guides/links.rst
  docs/source/guides/models.rst
  docs/source/guides/optimizers.rst
  docs/source/guides/serializers.rst
  docs/source/guides/trainer.rst
  docs/source/guides/type_checks.rst
  docs/source/guides/variables.rst
  docs/source/imports.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/reference/configuration.rst
  docs/source/reference/core.rst
  docs/source/reference/core/dataset.rst
  docs/source/reference/core/function.rst
  docs/source/reference/core/link.rst
  docs/source/reference/core/optimizer.rst
  docs/source/reference/core/serializer.rst
  docs/source/reference/datasets.rst
  docs/source/reference/debug.rst
  docs/source/reference/environment.rst
  docs/source/reference/extensions.rst
  docs/source/reference/function_hooks.rst
  docs/source/reference/functions.rst
  docs/source/reference/index.rst
  docs/source/reference/iterators.rst
  docs/source/reference/links.rst
  docs/source/reference/optimizers.rst
  docs/source/reference/serializers.rst
  docs/source/reference/training.rst
  docs/source/reference/variable.rst
  docs/source/tutorial/basic.rst
  docs/source/tutorial/customize.rst
  docs/source/tutorial/index.rst
  docs/source/tutorial/train.rst
  docs/source/tutorial/various_tasks.rst
  docs/source/tutorial/writenet.rst
Labels: document

#3610 Update comparison.rst (Web interface)
  docs/source/comparison.rst
Labels: document, st:test-and-merge

#4381 fix iDeep import error message not printed as expected
  chainer/backends/intel64.py
Labels: bug, st:test-and-merge

#4382 Fixed a bug that occur when using iDeep in chainer/link.py
  chainer/link.py
Labels: bug, st:test-and-merge

#4379 add F.shift to docs
  docs/source/reference/functions.rst
Labels: document, st:test-and-merge, to-be-backported

#4380 Fix numpy dtypes bug in cuda.to_gpu and cuda.copy
  chainer/backends/cuda.py
  tests/chainer_tests/test_cuda.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4256 support using cupy wheels as a dependency
  setup.py
Labels: install, st:test-and-merge

#3500 Fix some options of MNIST example not working
  examples/mnist/train_mnist_custom_loop.py
Labels: example

#3744 Add test cases for various shapes as function input
  tests/chainer_tests/test_function.py
  tests/chainer_tests/test_function_node.py
  tests/chainer_tests/test_variable.py
Labels: enhancement, st:awaiting-response, to-be-backported

#4349 Fix BatchMatMulGrad.backward
  chainer/functions/math/matmul.py
Labels: bug, st:test-and-merge

#4320 Fix lstm backward arguments
  chainer/functions/activation/lstm.py
Labels: bug, st:test-and-merge, to-be-backported

#4387 [backport] fix sphinx build option assignment in Makefile
  docs/Makefile
Labels: backport, document, st:test-and-merge

#4385 Improve ideep import error message fror missing shared objects
  chainer/backends/intel64.py
Labels: enhancement, st:test-and-merge

#4388 Fix autopep8 config
  .pep8
  .travis.yml
  docs/source/contribution.rst
  setup.cfg
Labels: other, st:test-and-merge, to-be-backported

#4367 [backport] Fix crash bug when a child is reporting a value when using MultiprocessParallelUpdater
  chainer/training/updaters/multiprocess_parallel_updater.py
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: backport, bug, st:test-and-merge

#4390 [backport] Fix some options of MNIST example not working
  examples/mnist/train_mnist_custom_loop.py
Labels: backport, example, st:test-and-merge

#4389 [backport] Add test cases for various shapes as function input
  tests/chainer_tests/test_function.py
  tests/chainer_tests/test_function_node.py
  tests/chainer_tests/test_variable.py
Labels: backport, enhancement

#4386 [backport] Fix numpy dtypes bug in cuda.to_gpu and cuda.copy
  chainer/backends/cuda.py
  tests/chainer_tests/test_cuda.py
Labels: backport, enhancement

#4366 Make install command more concise
  README.md
  docs/source/install.rst
  setup.py
Labels: document, install, st:test-and-merge, to-be-backported

#4040 add autosummary check to documents
  docs/source/_autosummary_check.py
  docs/source/conf.py
Labels: document, st:test-and-merge, to-be-backported

#4396 [backport] Prefer pip in installation guide; Add sphinx in docs requirements
  README.md
  docs/source/install.rst
  setup.py
Labels: backport, document, install

#3981 Update documentation for `chainer.backends.cuda`
  chainer/backends/cuda.py
  chainer/functions/array/copy.py
  docs/source/examples/train_loop.rst
  docs/source/guides/functions.rst
  docs/source/guides/gpu.rst
  docs/source/install.rst
  docs/source/reference/util/cuda.rst
Labels: document, st:test-and-merge

#4384 Fix link.to_intel64 for persistent values
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: bug

#4262 Add Swish activation function.
  chainer/functions/__init__.py
  chainer/functions/activation/swish.py
  chainer/links/__init__.py
  chainer/links/activation/swish.py
  docs/source/reference/functions.rst
  docs/source/reference/links.rst
  tests/chainer_tests/functions_tests/activation_tests/test_swish.py
  tests/chainer_tests/links_tests/activation_tests/test_swish.py
Labels: feature

#3807 new style simplified_dropconnect function
  chainer/functions/noise/simplified_dropconnect.py
  tests/chainer_tests/functions_tests/noise_tests/test_simplified_dropconnect.py
  tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
Labels: feature, to-be-backported

#4313 Use the same code for calculating forward and backward probabilities in CTC
  chainer/functions/loss/ctc.py
Labels: enhancement, st:test-and-merge

#4393 [backport] Fix BatchMatMulGrad.backward
  chainer/functions/math/matmul.py
Labels: bug, st:test-and-merge

#4375 Improve docs of get item
  chainer/functions/array/get_item.py
Labels: document, st:test-and-merge, to-be-backported

#4275 Child sum treelstm with less than 2 child
  chainer/functions/activation/tree_lstm.py
  chainer/links/connection/tree_lstm.py
  tests/chainer_tests/links_tests/connection_tests/test_tree_lstm.py
Labels: enhancement, st:test-and-merge

#4368 Fix test of multiprocess_parallel_updater
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: bug, st:test-and-merge, test

#4352 Detect backward of old-style functions in chainer.grad
  chainer/function_node.py
  tests/chainer_tests/test_variable.py
Labels: enhancement

#4391 [backport] Fix autopep8 config
  .pep8
  .travis.yml
  docs/source/contribution.rst
  setup.cfg
Labels: backport, other, st:test-and-merge

#4403 [backport] new style simplified_dropconnect function
  chainer/functions/noise/simplified_dropconnect.py
  tests/chainer_tests/functions_tests/noise_tests/test_simplified_dropconnect.py
  tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
Labels: backport, feature

#4132 New style AveragePoolingND/MaxPoolingND/UnpoolingND
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/max_pooling_nd_kernel.py
  chainer/functions/pooling/pooling_nd.py
  chainer/functions/pooling/unpooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_nd.py
Labels: enhancement

#4406 use CuPy wheels in Dockerfiles
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: install

#4199 [RFC] Require "scalar" variables to be 0-dim
  chainer/variable.py
  tests/chainer_tests/test_function.py
  tests/chainer_tests/test_function_node.py
  tests/chainer_tests/test_variable.py
Labels: no-compat

#4392 add cupy-cuda91 wheel dependency
  setup.py
Labels: install

#4399 [backport] add autosummary check to documents
  docs/source/_autosummary_check.py
  docs/source/conf.py
Labels: backport, document, st:test-and-merge

#4408 Fix Variable tests
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: bug

#4351 [backport] Improve ELU.backward
  chainer/functions/activation/elu.py
Labels: backport, bug

#4402 add Codecov.io configuration
  codecov.yml
Labels: other, to-be-backported

#4398 Fix typo in unpooling_nd
  chainer/functions/pooling/unpooling_nd.py
Labels: document, st:test-and-merge, to-be-backported

#4414 Prefer chainer.backends.cuda in recent added codes
  chainer/functions/array/stack.py
  chainer/functions/math/erf.py
  chainer/functions/math/erfc.py
  docs/source/conf.py
  docs/source/imports.rst
  tests/chainer_tests/functions_tests/activation_tests/test_swish.py
  tests/chainer_tests/links_tests/activation_tests/test_swish.py
Labels: enhancement, st:test-and-merge

#4410 [backport] add Codecov.io configuration
  codecov.yml
Labels: backport, other, st:test-and-merge

#4415 [backport] Improve docs of get item
  chainer/functions/array/get_item.py
Labels: backport, document, st:test-and-merge

#4241 Implement FFT
  chainer/functions/__init__.py
  chainer/functions/math/fft.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/math_tests/test_fft.py
Labels: feature

#4411 [backport] Fix typo in unpooling_nd
  chainer/functions/pooling/unpooling_nd.py
Labels: backport, document, st:test-and-merge

#4032 added initial version of AMSGrad
  chainer/optimizers/adam.py
Labels: feature

#4073 Add Local Convolution 2D connection layer
  chainer/functions/__init__.py
  chainer/functions/connection/local_convolution_2d.py
  chainer/links/__init__.py
  chainer/links/connection/local_convolution_2d.py
  docs/source/reference/functions.rst
  docs/source/reference/links.rst
  tests/chainer_tests/functions_tests/connection_tests/test_local_convolution_2d.py
  tests/chainer_tests/links_tests/connection_tests/test_local_convolution_2d.py
Labels: feature

#4044 Add test for inconsistent backend input outputs
  tests/chainer_tests/test_function_node.py
Labels: test

#3984 Add tutorial seq2seq
  docs/image/seq2seq/lstm-rnn.png
  docs/image/seq2seq/seq2seq.png
  docs/source/examples/index.rst
  docs/source/examples/seq2seq.rst
  examples/seq2seq/seq2seq.py
Labels: document, example

#4294 Implement time trigger
  chainer/training/triggers/__init__.py
  chainer/training/triggers/time_trigger.py
  docs/source/reference/triggers.rst
  tests/chainer_tests/training_tests/triggers_tests/test_time_trigger.py
Labels: feature

#4049 Test of RNN in the case when some gradients are None
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: st:test-and-merge, test, to-be-backported

#4401 Spatial pyramid pooling method specified by string instead of type
  chainer/functions/pooling/spatial_pyramid_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
Labels: feature, st:test-and-merge

#4345 Default statistics to get array modules
  chainer/training/extensions/parameter_statistics.py
  tests/chainer_tests/training_tests/extensions_tests/test_parameter_statistics.py
Labels: feature

#4420 [backport] Test of RNN in the case when some gradients are None
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: backport, test

#4409 Remove Swish function class alias
  chainer/functions/__init__.py
Labels: bug, st:test-and-merge

#4407 Fix the index page of datasets in documentation
  docs/source/reference/datasets.rst
Labels: bug, document, st:test-and-merge

#3735 Add repeat function
  chainer/functions/__init__.py
  chainer/functions/array/repeat.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/array_tests/test_repeat.py
Labels: feature, st:test-and-merge

#4416 add backward test for old-styled sclar variable
  tests/chainer_tests/test_variable.py
Labels: test

#4405 [backport] New style AveragePoolingND/MaxPoolingND/UnpoolingND
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/max_pooling_nd_kernel.py
  chainer/functions/pooling/pooling_nd.py
  chainer/functions/pooling/unpooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_nd.py
Labels: backport, enhancement
