Repository chainer/chainer, pull requests merged in 2018-05, with the labels that each got.

#4705 Update word2vec.rst
  docs/source/examples/word2vec.rst
Labels: document, st:test-and-merge, to-be-backported

#4724 fix dead link to CuPy installation guide
  docs/source/install.rst
Labels: document, to-be-backported

#4721 Update seq2seq.rst
  docs/source/examples/seq2seq.rst
Labels: document, to-be-backported

#4727 [backport] fix dead link to CuPy installation guide
  docs/source/install.rst
Labels: backport, document, st:test-and-merge

#4731 Fix hacking version
  setup.py
Labels: st:test-and-merge, test, to-be-backported

#4733 [backport] Fix hacking version
  setup.py
Labels: backport, st:test-and-merge, test

#4715 [backport] Update math formula typo
  docs/source/examples/ptb.rst
Labels: backport, document

#4713 [backport] Update word2vec.rst
  docs/source/examples/word2vec.rst
Labels: backport, document

#4671 L.BatchNormalization: miscellaneous fixes
  chainer/links/normalization/batch_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
  tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Labels: document, test

#4734 [backport] Update top sentences in documentation
  docs/source/index.rst
Labels: backport, document, st:test-and-merge

#4743 Fix incorrect attributes and incorrect indentation in pooling tests
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
Labels: test

#4728 [backport] Update seq2seq.rst
  docs/source/examples/seq2seq.rst
Labels: backport, document

#4726 separate MultiprocessParallelUpdater tests
  tests/chainer_tests/training_tests/updaters_tests/snippets/child_reporter.py
  tests/chainer_tests/training_tests/updaters_tests/snippets/raw_array.py
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: test, to-be-backported

#4717 Raise an error when CUDA has been initialized before MultiprocessParallelUpdater is initialized
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: bug, st:blocked-by-another-pr, to-be-backported

#4700 Update train_loop.rst
  docs/source/examples/train_loop.rst
Labels: document, st:awaiting-response, to-be-backported

#4738 Fix regression in bilinear
  chainer/functions/connection/bilinear.py
  tests/chainer_tests/functions_tests/connection_tests/test_bilinear.py
Labels: st:test-and-merge

#4760 Fix some typos in tutorials
  docs/source/examples/seq2seq.rst
  docs/source/examples/train_loop.rst
Labels: document, to-be-backported

#4768 Fix lazy_grad_sum debug mode
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: bug, to-be-backported

#4776 [backport] Fix lazy_grad_sum debug mode
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: backport, bug

#4112 Moveaxis array operation proposal
  chainer/functions/__init__.py
  chainer/functions/array/moveaxis.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/array_tests/test_moveaxis.py
Labels: feature

#4725 Select current device using grads of outputs in addition to inputs during backward
  chainer/variable.py
  tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py
  tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
Labels: bug, st:test-and-merge, to-be-backported

#4763 Fix dtype bug in F.normalize
  chainer/functions/normalization/l2_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: bug, to-be-backported

#4781 [backport] Fix dtype bug in F.normalize
  chainer/functions/normalization/l2_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: backport, bug

#4762 [backport] Fix regression in bilinear
  chainer/functions/connection/bilinear.py
  tests/chainer_tests/functions_tests/connection_tests/test_bilinear.py
Labels: backport, enhancement

#3429 Add order_sampler option to Iterators
  chainer/iterators/__init__.py
  chainer/iterators/multiprocess_iterator.py
  chainer/iterators/multithread_iterator.py
  chainer/iterators/order_samplers.py
  chainer/iterators/serial_iterator.py
  docs/source/reference/iterators.rst
  tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
  tests/chainer_tests/iterators_tests/test_multithread_iterator.py
  tests/chainer_tests/iterators_tests/test_serial_iterator.py
Labels: feature

#4450 grouped convolution for intel64 backed environment
  chainer/backends/intel64.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/links/connection/convolution_2d.py
Labels: feature, st:test-and-merge

#4722 add doc build steps to contrib guide
  docs/source/contribution.rst
Labels: document, to-be-backported

#4775 Optimize Huber loss by simpler calculation
  chainer/functions/loss/huber_loss.py
Labels: enhancement, st:test-and-merge

#4764 [backport] Add abs to document of Variable
  chainer/variable.py
Labels: backport, document

#4790 Add favicon
  docs/source/_static/favicon.png
  docs/source/conf.py
Labels: document, to-be-backported

#4788 [backport] Optimize Huber loss by simpler calculation
  chainer/functions/loss/huber_loss.py
Labels: backport, enhancement

#4759 [backport] Update train_loop.rst
  docs/source/examples/train_loop.rst
Labels: backport, document

#4787 [backport] grouped convolution for intel64 backed environment
  chainer/backends/intel64.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/links/connection/convolution_2d.py
Labels: backport, feature

#4792 Revert "Add favicon"
  docs/source/_static/favicon.png
  docs/source/conf.py
Labels: st:test-and-merge

#4784 [backport] add doc build steps to contrib guide
  docs/source/contribution.rst
Labels: backport, document, st:test-and-merge

#4663 Warn only if the BN input tensor is 2-dimensional
  chainer/functions/normalization/batch_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Labels: bug, st:test-and-merge, to-be-backported

#4637 [backport] Provide a cleaner way to collect threads and processes in MultiprocessIterator
  chainer/dataset/iterator.py
  chainer/iterators/multiprocess_iterator.py
  chainer/iterators/multithread_iterator.py
  examples/mnist/train_mnist_custom_loop.py
Labels: backport, feature, st:awaiting-response

#4746 Support copying 1-dim array to ideep
  chainer/backends/intel64.py
  chainer/link.py
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: enhancement, to-be-backported

#4794 [backport] Support copying 1-dim array to ideep
  chainer/backends/intel64.py
  chainer/link.py
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: backport, enhancement, st:test-and-merge

#4693 Added the support of PolynomialShift in the extensions of training.
  chainer/training/extensions/__init__.py
  chainer/training/extensions/polynomial_shift.py
  docs/source/reference/training.rst
  tests/chainer_tests/training_tests/extensions_tests/test_polynomial_shift.py
Labels: feature, st:test-and-merge

#3764 new style prod function
  chainer/functions/math/prod.py
  tests/chainer_tests/functions_tests/math_tests/test_prod.py
Labels: feature, st:test-and-merge

#4780 [backport] Select current device using grads of outputs in addition to inputs during backward
  chainer/variable.py
  tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py
  tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
Labels: backport, bug

#4786 Sparse matrix example docs
  chainer/functions/math/sparse_matmul.py
  chainer/utils/sparse.py
  docs/source/reference/util/sparse.rst
Labels: document, st:test-and-merge

#4778 Document the pros and cons of the multi-GPU updaters
  docs/source/reference/training.rst
Labels: document

#4802 [backport] Fix some typos in tutorials
  docs/source/examples/seq2seq.rst
  docs/source/examples/train_loop.rst
Labels: backport, document

#4803 [backport] update URL in README
  README.md
Labels: backport, document

#4797 Output the direction of differentiation in `gradient_check` error
  chainer/gradient_check.py
Labels: enhancement, to-be-backported

#4814 Fix a documenation bug in `TransformDataset`
  chainer/datasets/transform_dataset.py
Labels: document, to-be-backported

#4810 Fix test warning filter for Theano 1.0.2 which triggers DeprecationWarning
  setup.cfg
Labels: st:test-and-merge, test, to-be-backported

#4815 [backport] Fix comment in `caffe.py`
  chainer/exporters/caffe.py
Labels: backport, document

#4801 [backport] separate MultiprocessParallelUpdater tests
  tests/chainer_tests/training_tests/updaters_tests/snippets/child_reporter.py
  tests/chainer_tests/training_tests/updaters_tests/snippets/raw_array.py
  tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Labels: backport, test

#4804 [backport] Fix custom loop examples to disable train mode during evaluation
  examples/cifar/train_cifar_custom_loop.py
  examples/mnist/train_mnist_custom_loop.py
  examples/ptb/train_ptb_custom_loop.py
Labels: backport, example

#4820 [backport] Fix test warning filter for Theano 1.0.2 which triggers DeprecationWarning
  setup.cfg
Labels: backport, st:test-and-merge, test

#4816 Test `F.layer_normalization` with large eps
  tests/chainer_tests/functions_tests/normalization_tests/test_layer_normalization.py
Labels: test

#4817 [backport] Output the direction of differentiation in `gradient_check` error
  chainer/gradient_check.py
Labels: backport, enhancement, st:test-and-merge

#4826 [backport] Support double-backprop in `F.prod`
  chainer/functions/math/prod.py
  tests/chainer_tests/functions_tests/math_tests/test_prod.py
Labels: backport, feature, st:test-and-merge

#4766 Show progress report to stderr
  chainer/dataset/download.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
Labels: enhancement, to-be-backported

#4827 [backport] Show progress report to stderr
  chainer/dataset/download.py
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
Labels: backport, enhancement, st:test-and-merge
