Repository chainer/chainer, pull requests merged in 2018-04, with the labels that each got.

#4266 Add axis option to batch normalization
  chainer/functions/normalization/batch_normalization.py
  chainer/links/normalization/batch_normalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Labels: feature

#4552 improve description of Extensions
  docs/source/reference/training.rst
Labels: document, to-be-backported

#4561 [backport] improve description of Extensions
  docs/source/reference/training.rst
Labels: backport, document

#4468 add upgrade guide for optimizer_hooks namespace
  docs/source/upgrade.rst
Labels: document, to-be-backported

#3688 add tutorial for Reporter and report.
  docs/source/guides/index.rst
  docs/source/guides/report.rst
Labels: document, enhancement, to-be-backported

#4563 fix dead link to optimizer hooks
  docs/source/upgrade.rst
Labels: document, to-be-backported

#4155 Provide a cleaner way to collect threads and processes in MultiprocessIterator
  chainer/dataset/iterator.py
  chainer/iterators/multiprocess_iterator.py
  chainer/iterators/multithread_iterator.py
  examples/mnist/train_mnist_custom_loop.py
Labels: feature, to-be-backported

#3631 Implement caffe export
  chainer/exporters/__init__.py
  chainer/exporters/caffe.py
  docs/source/reference/caffe.rst
  examples/caffe_export/README.md
  examples/caffe_export/export.py
  setup.py
  tests/chainer_tests/exporters_tests/__init__.py
  tests/chainer_tests/exporters_tests/test_caffe.py
Labels: feature, to-be-backported

#4569 Fix a typo
  chainer/functions/connection/local_convolution_2d.py
Labels: document, st:test-and-merge, to-be-backported

#4564 Fix group argument of {de,}convolution_2d to keyword-only argument.
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/deconvolution_2d.py
Labels: bug, st:test-and-merge, to-be-backported

#4573 [backport] Fix group argument of {de,}convolution_2d to keyword-only argument.
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/deconvolution_2d.py
Labels: backport, bug

#4571 [backport] add upgrade guide for optimizer_hooks namespace
  docs/source/upgrade.rst
Labels: backport, document

#4567 [backport] Implement caffe export
  chainer/exporters/__init__.py
  chainer/exporters/caffe.py
  docs/source/reference/caffe.rst
  examples/caffe_export/README.md
  examples/caffe_export/export.py
  setup.py
  tests/chainer_tests/exporters_tests/__init__.py
  tests/chainer_tests/exporters_tests/test_caffe.py
Labels: backport, feature

#4539 fix docs in {convolution,deconvolution}_2d
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/links/connection/convolution_2d.py
Labels: document, to-be-backported

#4575 [backport] fix docs in {convolution,deconvolution}_2d
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/links/connection/convolution_2d.py
Labels: backport, document, st:test-and-merge

#4574 fix typo
  chainer/variable.py
Labels: document, st:test-and-merge

#4555 Simplify TestSoftmaxCrossEntropyInvalidReduce in test_softmax_cross_entropy
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: test, to-be-backported

#4578 fix document in EarlyStoppingTrigger
  chainer/training/triggers/early_stopping_trigger.py
Labels: document, st:test-and-merge, to-be-backported

#4579 Simplify TestSoftmaxCrossEntropyInvalidReduce in test_softmax_cross_entropy
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: backport, test

#4576 [backport] fix typo
  chainer/variable.py
Labels: backport, document

#4584 [backport] fix document in EarlyStoppingTrigger
  chainer/training/triggers/early_stopping_trigger.py
Labels: backport, document

#4543 add document for chainer.config.lazy_grad_sum
  docs/source/reference/configuration.rst
Labels: document, st:test-and-merge, to-be-backported

#4570 [backport] Fix a typo
  chainer/functions/connection/local_convolution_2d.py
Labels: backport, document

#4482 Optimize depth2space & space2depth funcs by reducing operations
  chainer/functions/array/depth2space.py
  chainer/functions/array/space2depth.py
Labels: enhancement, st:awaiting-response

#4592 Fix to_intel64 not updating VariableNode.data
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: bug, to-be-backported

#4577 Fix to_intel64 to check if it is suitable for iDeep
  chainer/link.py
  chainer/variable.py
  tests/chainer_tests/test_link.py
  tests/chainer_tests/test_variable.py
Labels: bug, st:test-and-merge, to-be-backported

#4585 [backport] add document for chainer.config.lazy_grad_sum
  docs/source/reference/configuration.rst
Labels: backport, document, st:test-and-merge

#4419 Avoid mutable default arguments
  chainer/links/model/vision/googlenet.py
  chainer/links/model/vision/resnet.py
  chainer/links/model/vision/vgg.py
Labels: enhancement, to-be-backported

#2918 Add Sequential class for easy model definition of a single-stream computational graph
  chainer/__init__.py
  chainer/link.py
  chainer/sequential.py
  chainer/variable.py
  docs/source/reference/links.rst
  tests/chainer_tests/test_link.py
  tests/chainer_tests/test_sequential.py
  tests/chainer_tests/test_variable.py
Labels: feature, reviewer-team, st:needs-discussion, to-be-backported

#4598 [backport] Fix to_intel64 to check if it is suitable for iDeep
  chainer/link.py
  chainer/variable.py
  tests/chainer_tests/test_link.py
  tests/chainer_tests/test_variable.py
Labels: backport, bug, st:test-and-merge

#4597 [backport] Fix to_intel64 not updating VariableNode.data
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: backport, bug, st:test-and-merge

#4545 Add extensions.NaNKiller
  chainer/training/extensions/__init__.py
  chainer/training/extensions/fail_on_nonnumber.py
  docs/source/reference/training.rst
  tests/chainer_tests/training_tests/extensions_tests/test_fail_on_nonnumber.py
Labels: feature, st:test-and-merge, to-be-backported

#4609 [backport] Fix installation order of hacking
  setup.py
Labels: backport, install, st:test-and-merge, test

#4603 [backport] Improve docstrings about axis of Caffe functions
  chainer/functions/math/bias.py
  chainer/functions/math/scale.py
Labels: backport, document

#4559 Implement interface to print runtime information
  chainer/__init__.py
  chainer/_runtime_info.py
  tests/chainer_tests/test_runtime_info.py
Labels: feature, to-be-backported

#4551 Improve chainer.utils.argument exception message
  chainer/utils/argument.py
  tests/chainer_tests/utils_tests/test_argument.py
Labels: enhancement, st:test-and-merge

#4611 fix seq2seq example ignoring limitation for target length
  examples/seq2seq/seq2seq.py
Labels: bug, example, to-be-backported

#4601 [backport] Add Sequential class for easy model definition of a single-stream computational graph
  chainer/__init__.py
  chainer/link.py
  chainer/sequential.py
  chainer/variable.py
  docs/source/reference/links.rst
  tests/chainer_tests/test_link.py
  tests/chainer_tests/test_sequential.py
  tests/chainer_tests/test_variable.py
Labels: backport, feature

#4618 [backport] Save snapshot in the OS default permission
  chainer/training/extensions/_snapshot.py
  tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
Labels: backport, bug, st:test-and-merge

#4617 [backport] fix seq2seq example ignoring limitation for target length
  examples/seq2seq/seq2seq.py
Labels: backport, bug, example, st:test-and-merge

#4604 improve docs of get_device_from_array
  chainer/backends/cuda.py
Labels: document, to-be-backported

#4554 Fix and simplify TestForwardConsistency in softmax_cross_entropy
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: test, to-be-backported

#4621 [backport] Implement caffe export
  chainer/exporters/__init__.py
  chainer/exporters/caffe.py
  docs/source/reference/caffe.rst
  examples/caffe_export/README.md
  examples/caffe_export/export.py
  setup.py
  tests/chainer_tests/exporters_tests/__init__.py
  tests/chainer_tests/exporters_tests/test_caffe.py
Labels: backport, feature

#4626 [backport] Fix and simplify TestForwardConsistency in softmax_cross_entropy
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Labels: backport, test

#4615 [backport] Improve chainer.utils.argument exception message
  chainer/utils/argument.py
  tests/chainer_tests/utils_tests/test_argument.py
Labels: backport, enhancement

#4590 [backport] Optimize depth2space & space2depth funcs by reducing operations
  chainer/functions/array/depth2space.py
  chainer/functions/array/space2depth.py
Labels: backport, enhancement

#4624 [backport] improve docs of get_device_from_array
  chainer/backends/cuda.py
Labels: backport, document, st:test-and-merge

#4580 Removed redundant member variables
  chainer/functions/connection/n_step_rnn.py
Labels: enhancement, st:test-and-merge, to-be-backported

#4605 Fix docstrings of Sequential
  chainer/sequential.py
Labels: bug, document, to-be-backported

#4602 [backport] Add extension to kill training when NaN or Inf is detected (FailOnNonNumber)
  chainer/training/extensions/__init__.py
  chainer/training/extensions/fail_on_nonnumber.py
  docs/source/reference/training.rst
  tests/chainer_tests/training_tests/extensions_tests/test_fail_on_nonnumber.py
Labels: backport, feature

#4589 Add FAQ for MultiprocessIterator + OpenCV problem
  docs/source/tips.rst
Labels: document, to-be-backported

#4629 [backport] Add FAQ for MultiprocessIterator + OpenCV problem
  docs/source/tips.rst
Labels: backport, document

#4628 [backport] Fix docstrings of Sequential
  chainer/sequential.py
Labels: backport, bug, document

#4627 [backport] Removed redundant member variables
  chainer/functions/connection/n_step_rnn.py
Labels: backport, enhancement

#4649 Fix Chain.repeat
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: bug, to-be-backported

#4643 fix typos in seq2seq tutorial document
  docs/source/examples/seq2seq.rst
Labels: document, st:test-and-merge, to-be-backported

#4558 Unify `TestBatchNormalization` and `TestBatchNormalizationAxis`
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Labels: test, to-be-backported

#2135 Mini-batch training for recursive neural networks example
  examples/sentiment/data.py
  examples/sentiment/test_thin_stack.py
  examples/sentiment/thin_stack.py
  examples/sentiment/train_recursive_minibatch.py
  examples/sentiment/train_sentiment.py
Labels: example, feature, reviewer-team

#4568 Fix custom loop examples to disable train mode during evaluation
  examples/cifar/train_cifar_custom_loop.py
  examples/mnist/train_mnist_custom_loop.py
  examples/ptb/train_ptb_custom_loop.py
Labels: example, to-be-backported

#4653 [backport] Fix Chain.repeat
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: backport, bug

#4612 Use rsqrt in batch_normalization
  chainer/functions/normalization/batch_normalization.py
Labels: enhancement, st:test-and-merge

#4204 Add n_batch_axes option to Linear function
  chainer/functions/connection/linear.py
  tests/chainer_tests/functions_tests/connection_tests/test_linear.py
Labels: feature

#4237 Support Layer-wise Adaptive Rate Scaling(LARS)
  chainer/optimizer_hooks/__init__.py
  chainer/optimizer_hooks/gradient_lars.py
  docs/source/reference/optimizers.rst
  tests/chainer_tests/optimizer_hooks_tests/test_gradient_lars.py
Labels: feature, to-be-backported

#4657 update URL in README
  README.md
Labels: document, to-be-backported

#4665 [backport] Use rsqrt in batch_normalization
  chainer/functions/normalization/batch_normalization.py
Labels: backport, enhancement

#4651 [backport] fix typos in seq2seq tutorial document
  docs/source/examples/seq2seq.rst
Labels: backport, document

#4666 fix batch_normalization axis document
  chainer/functions/normalization/batch_normalization.py
Labels: document, to-be-backported

#4633 [backport] rewrite installation guide to align with CuPy's installation guide
  docs/source/install.rst
Labels: backport, document, enhancement

#4634 [backport] improve F.rsqrt performance in CPU
  chainer/functions/math/sqrt.py
Labels: backport, enhancement

#4635 [backport] Fix temporary file permission issue in LogReport
  chainer/dataset/download.py
  chainer/testing/serializer.py
  chainer/training/extensions/_snapshot.py
  chainer/training/extensions/log_report.py
  chainer/utils/__init__.py
Labels: backport, enhancement

#4636 [backport] Add higher-order derivative support of Chainer to the comparison table
  docs/source/comparison.rst
Labels: backport, document

#4664 [backport] Fix `ChainList.copy` not supporting `mode` argument
  chainer/link.py
  tests/chainer_tests/test_link.py
Labels: backport, bug

#4668 [backport] Support Layer-wise Adaptive Rate Scaling(LARS)
  chainer/optimizer_hooks/__init__.py
  chainer/optimizer_hooks/gradient_lars.py
  docs/source/reference/optimizers.rst
  tests/chainer_tests/optimizer_hooks_tests/test_gradient_lars.py
Labels: backport, feature

#4632 [backport] add tutorial for Reporter and report.
  docs/source/guides/index.rst
  docs/source/guides/report.rst
Labels: backport, document, enhancement

#4685 Support skipping tests decorated by condition or parametize
  chainer/testing/condition.py
  chainer/testing/parameterized.py
  tests/chainer_tests/testing_tests/test_condition.py
  tests/chainer_tests/testing_tests/test_parameterized.py
Labels: st:test-and-merge, test, to-be-backported

#4682 add ignore_names option to load_npz
  chainer/serializers/npz.py
  tests/chainer_tests/serializers_tests/test_npz.py
Labels: feature, st:test-and-merge

#4681 Fix import failure when matplotlib 1.x is installed
  chainer/training/extensions/variable_statistics_plot.py
Labels: bug, st:test-and-merge, to-be-backported

#4631 fix heading level of Caffe docs
  docs/source/reference/caffe.rst
Labels: document, to-be-backported

#4688 [backport] Support skipping tests decorated by condition or parametize
  chainer/testing/condition.py
  chainer/testing/parameterized.py
  tests/chainer_tests/testing_tests/test_condition.py
  tests/chainer_tests/testing_tests/test_parameterized.py
Labels: backport, test

#4689 [backport] Fix import failure when matplotlib 1.x is installed
  chainer/training/extensions/variable_statistics_plot.py
Labels: backport, bug

#4690 [backport] fix heading level of Caffe docs
  docs/source/reference/caffe.rst
Labels: backport, document, st:test-and-merge
