Repository chainer/chainer, pull requests merged in 2018-10, with the labels that each got.

#5382 Fix beta distribution
  chainer/distributions/beta.py
  tests/chainer_tests/distributions_tests/test_beta.py
Labels: to-be-backported

#5033 Update Adam for iDeep 2.0
  chainer/optimizers/adam.py
Labels: enhancement, st:blocked-by-another-pr, to-be-backported

#5320 Dynamically import matplotlib
  chainer/training/extensions/plot_report.py
  chainer/training/extensions/variable_statistics_plot.py
  tests/chainer_tests/training_tests/extensions_tests/test_plot_report.py
  tests/chainer_tests/training_tests/extensions_tests/test_variable_statistics_plot.py
Labels: enhancement, to-be-backported

#5371 add `D.Pareto`
  chainer/distributions/__init__.py
  chainer/distributions/pareto.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_pareto.py
Labels: feature, st:test-and-merge

#5407 [backport] Update Adam for iDeep 2.0
  chainer/optimizers/adam.py
Labels: backport, enhancement

#5306 Introduce `utils.mixed_presision` decorator
  chainer/utils/precision.py
  tests/chainer_tests/utils_tests/test_precision.py
Labels: feature

#5380 Fix occasional test failure of `l2normalize` with float16
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: st:test-and-merge, test

#5419 add document for `D.Beta`
  chainer/distributions/beta.py
Labels: document, to-be-backported

#5310 add Gamma distribution
  chainer/distributions/__init__.py
  chainer/distributions/gamma.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_gamma.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: feature

#5430 Remove debug print
  chainer/functions/math/polygamma.py
Labels: to-be-backported

#5426 [backport] add document for `D.Beta`
  chainer/distributions/beta.py
Labels: backport, document

#5341 add `D.Exponential`
  chainer/distributions/__init__.py
  chainer/distributions/exponential.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_exponential.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
Labels: feature

#5423 Fix docstring of discriminative loss
  chainer/functions/loss/discriminative_loss.py
Labels: document

#5437 [backport] Fix some E241 style errors
  chainer/backends/cuda.py
  chainer/links/model/vision/resnet.py
  tests/chainer_tests/functions_tests/activation_tests/test_lstm.py
  tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
  tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
  tests/chainer_tests/test_variable.py
Labels: backport, enhancement

#5399 [backport] Merge ChainerMN docs from master branch
  docs/source/chainermn/installation/guide.rst
  docs/source/chainermn/tutorial/tips_faqs.rst
Labels: ChainerMN, backport, document

#5415 Fix a ReST escape
  docs/source/reference/configuration.rst
Labels: document, to-be-backported

#5447 [backport] Fix typos in doc of `chainer.report`
  chainer/reporter.py
Labels: backport, document

#5448 [backport] Fix occasional test failure of `l2normalize` with float16
  tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
Labels: backport, test

#5449 [backport] Fix a ReST escape
  docs/source/reference/configuration.rst
Labels: backport, document

#5433 Fix style of imports
  chainer/distributions/log_normal.py
  chainer/distributions/utils.py
  chainer/functions/loss/discriminative_loss.py
  chainer/utils/precision.py
  tests/chainer_tests/distributions_tests/test_bernoulli.py
  tests/chainer_tests/distributions_tests/test_beta.py
  tests/chainer_tests/distributions_tests/test_categorical.py
  tests/chainer_tests/distributions_tests/test_dirichlet.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_laplace.py
  tests/chainer_tests/distributions_tests/test_log_normal.py
  tests/chainer_tests/distributions_tests/test_multivariate_normal.py
  tests/chainer_tests/distributions_tests/test_normal.py
  tests/chainer_tests/distributions_tests/test_pareto.py
  tests/chainer_tests/distributions_tests/test_uniform.py
  tests/chainer_tests/distributions_tests/test_utils.py
Labels: enhancement, st:test-and-merge, to-be-backported

#5446 Add Google Colaboratory installation steps and link to community examples
  docs/source/index.rst
  docs/source/install.rst
Labels: document, to-be-backported

#5453 fix typo in static graph optimization
  chainer/graph_optimizations/static_graph_utilities.py
Labels: document, to-be-backported

#5458 [backport] Fix style of imports
  chainer/distributions/log_normal.py
  chainer/distributions/utils.py
  tests/chainer_tests/distributions_tests/test_bernoulli.py
  tests/chainer_tests/distributions_tests/test_beta.py
  tests/chainer_tests/distributions_tests/test_categorical.py
  tests/chainer_tests/distributions_tests/test_dirichlet.py
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_laplace.py
  tests/chainer_tests/distributions_tests/test_log_normal.py
  tests/chainer_tests/distributions_tests/test_multivariate_normal.py
  tests/chainer_tests/distributions_tests/test_normal.py
  tests/chainer_tests/distributions_tests/test_uniform.py
  tests/chainer_tests/distributions_tests/test_utils.py
Labels: backport, enhancement

#5456 [backport] fix typo in static graph optimization
  chainer/graph_optimizations/static_graph_utilities.py
Labels: backport, document

#5438 Fix docstring of chainer.Sequential
  chainer/sequential.py
Labels: document, to-be-backported

#5427 Fix docstrings to follow OpenStack Style Guidelines
  chainer/training/extensions/warmup_shift.py
  chainer/utils/precision.py
Labels: document, st:test-and-merge, to-be-backported

#5461 [backport] Fix docstring of chainer.Sequential
  chainer/sequential.py
Labels: backport, document

#5460 Validate shape of weight in F.convolution_2d
  chainer/functions/connection/convolution_2d.py
Labels: enhancement, to-be-backported

#5465 [backport] Fix docstrings to follow OpenStack Style Guidelines
  chainer/training/extensions/warmup_shift.py
Labels: backport, document

#5463 [bugfix] CaffeFunction ignores pad_w
  chainer/links/caffe/caffe_function.py
Labels: bug, st:test-and-merge, to-be-backported

#5420 Rename Adam.lr
  chainer/optimizers/adam.py
Labels: enhancement, st:test-and-merge

#5464 [backport] Add Google Colaboratory installation steps and link to community examples
  docs/source/index.rst
  docs/source/install.rst
Labels: backport, document

#5424 Fix FunctionNode.retained_outputs
  chainer/function_node.py
  tests/chainer_tests/test_function_node.py
Labels: bug, to-be-backported

#5425 Check optional dependencies at runtime
  chainer/_environment_check.py
  chainer/_version.py
  setup.py
Labels: install, to-be-backported

#5468 [backport] [bugfix] CaffeFunction ignores pad_w
  chainer/links/caffe/caffe_function.py
Labels: backport, bug

#5476 [backport] Fix FunctionNode.retained_outputs
  chainer/function_node.py
  tests/chainer_tests/test_function_node.py
Labels: backport, bug

#5471 Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15
  setup.cfg
Labels: test, to-be-backported

#5490 [backport] Relax tolerance of check_double_backward test
  tests/chainer_tests/test_gradient_check.py
Labels: backport, st:test-and-merge, test

#5491 [backport] Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15
  setup.cfg
Labels: backport, test

#5475 [backport] Dedup assertion in MpiCommunicatorBase.allreduce
  chainermn/communicators/mpi_communicator_base.py
Labels: ChainerMN, backport, enhancement

#5469 Fix `train_imagenet_data_parallel.py` example cannot be run
  examples/imagenet/train_imagenet_data_parallel.py
Labels: bug, st:test-and-merge, to-be-backported

#5499 [backport] Fix `train_imagenet_data_parallel.py` example cannot be run
  examples/imagenet/train_imagenet_data_parallel.py
Labels: backport, bug

#5496 Fix `F.softmax` and `F.log_softmax` with `axis=-1` on gpu
  chainer/functions/activation/softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
Labels: bug, to-be-backported

#5502 [backport] Fix `F.softmax` and `F.log_softmax` with `axis=-1` on gpu
  chainer/functions/activation/softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
Labels: backport, bug

#5353 For proper resuming, don't raise KeyError at UpdateRule deserialization
  chainer/optimizer.py
  tests/chainer_tests/test_optimizer.py
Labels: bug, to-be-backported

#5495 Consistently use `Variable.array` instead of `.data`
  chainer/variable.py
Labels: enhancement, to-be-backported

#5478 Implement no-double-backprop version of F.softmax_cross_entropy using FunctionNode
  chainer/functions/loss/softmax_cross_entropy.py
Labels: enhancement

#5508 Fix SoftmaxCrossEntropy grad function node
  chainer/functions/loss/softmax_cross_entropy.py
Labels: bug, st:test-and-merge

#5029 Update packaging for iDeep 2.0
  chainer/_runtime_info.py
  chainer/backends/intel64.py
  docs/source/tips.rst
Labels: enhancement, st:blocked-by-another-pr, to-be-backported

#5504 Fix dead fragments to CuPy docs
  chainer/backends/cuda.py
  docs/source/chainermn/installation/guide.rst
Labels: document, to-be-backported

#5488 [backport] replace variable.data with variable.array in chainer.variable.py
  chainer/variable.py
Labels: backport, enhancement

#5517 [backport] Consistently use `Variable.array` instead of `.data`
  chainer/variable.py
Labels: backport, enhancement

#5515 [backport] Fix dead fragments to CuPy docs
  chainer/backends/cuda.py
  docs/source/chainermn/installation/guide.rst
Labels: backport, document

#5513 [backport] Update packaging for iDeep 2.0
  chainer/_runtime_info.py
  chainer/backends/intel64.py
  docs/source/tips.rst
Labels: backport, enhancement

#5514 Ignore protobuf is warned by Python 3.7
  setup.cfg
Labels: test, to-be-backported

#5505 [backport] Add discriminative margin based clustering loss
  chainer/functions/__init__.py
  chainer/functions/loss/discriminative_loss.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/loss_tests/test_discriminative_margin_based_clustering_loss.py
Labels: backport, feature

#4630 Add error handler interface to trainer extensions
  chainer/training/extension.py
  chainer/training/extensions/_snapshot.py
  chainer/training/trainer.py
  tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
  tests/chainer_tests/training_tests/test_trainer.py
Labels: feature, st:test-and-merge

#5493 Fix backward of HuberLoss
  chainer/functions/loss/huber_loss.py
Labels: bug, to-be-backported

#5518 [backport] Ignore protobuf is warned by Python 3.7
  setup.cfg
Labels: backport, test

#5388 Improve code sample appearance in docs
  docs/source/glance.rst
  examples/glance/glance.py
Labels: document

#5323 Support all float dtypes in `F.det` and `F.inv`
  chainer/functions/math/det.py
  chainer/functions/math/inv.py
  tests/chainer_tests/functions_tests/math_tests/test_det.py
  tests/chainer_tests/functions_tests/math_tests/test_inv.py
Labels: feature

#5523 Fix a typo in `Extension.on_error`
  chainer/training/extension.py
Labels: document

#5510 Use arr.item() instead of np.asscalar(arr) to support NumPy 1.16
  chainer/training/extensions/exponential_shift.py
  chainer/training/extensions/inverse_shift.py
  chainer/training/extensions/linear_shift.py
  chainer/training/extensions/polynomial_shift.py
  chainer/training/extensions/step_shift.py
  docs/source/guides/extensions.rst
Labels: enhancement, st:test-and-merge, to-be-backported

#5522 [backport] Improve code sample appearance in docs
  docs/source/glance.rst
  examples/glance/glance.py
Labels: backport, document

#5450 Use "documentation" instead of "document" in our documentation
  chainer/datasets/sub_dataset.py
  chainer/functions/array/get_item.py
  chainer/link.py
  chainer/utils/type_check.py
  chainermn/functions/pseudo_connect.py
  docs/source/compatibility.rst
  docs/source/contribution.rst
  docs/source/guides/gpu.rst
  docs/source/reference/check.rst
  docs/source/reference/static_graph_design.rst
  docs/source/upgrade_v2.rst
Labels: document, to-be-backported

#5520 [backport] Fix backward of HuberLoss
  chainer/functions/loss/huber_loss.py
Labels: backport, bug

#5529 [backport] Use arr.item() instead of np.asscalar(arr) to support NumPy 1.16
  chainer/training/extensions/exponential_shift.py
  chainer/training/extensions/inverse_shift.py
  chainer/training/extensions/linear_shift.py
  chainer/training/extensions/polynomial_shift.py
  chainer/training/extensions/step_shift.py
  docs/source/guides/extensions.rst
Labels: backport, enhancement

#5531 Chainer v5 requires CuPy v5
  docs/source/install.rst
  docs/source/upgrade.rst
Labels: document, to-be-backported

#5537 [backport] Fix docstring of discriminative loss
  chainer/functions/loss/discriminative_loss.py
Labels: backport, document

#5527 Improve FunctionNode upgrade guide
  docs/source/upgrade.rst
Labels: document, to-be-backported

#5439 Simplify scalar handling in `basic_math`
  chainer/functions/math/basic_math.py
Labels: enhancement, to-be-backported

#5497 Support negative `axis` for `F.softmax`
  chainer/functions/activation/softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
Labels: enhancement, to-be-backported

#5540 [backport] Chainer v5 requires CuPy v5
  docs/source/install.rst
  docs/source/upgrade.rst
Labels: backport, document

#5541 [backport] Improve FunctionNode upgrade guide
  docs/source/upgrade.rst
Labels: backport, document

#5477 Avoid Iterable in CaffeFunction
  chainer/links/caffe/caffe_function.py
Labels: enhancement

#5335 Support all float dtypes in `F.scatter_add` and `F.get_item`
  chainer/functions/array/get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_scatter_add.py
Labels: feature

#5516 Tests with maxtasksperchild=1 or 10 are slow
  tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
Labels: test, to-be-backported

#5519 Use `SerialIterator` in `train_mnist_custom_loop.py`
  examples/mnist/train_mnist_custom_loop.py
Labels: example, to-be-backported

#5014 In-place update in `F.batch_renormalization`
  chainer/functions/normalization/batch_renormalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
Labels: enhancement, to-be-backported

#5543 [backport] Support negative `axis` for `F.softmax`
  chainer/functions/activation/softmax.py
  tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
Labels: backport, enhancement

#5428 Simplify scalar handling in `basic_math`
  chainer/functions/math/basic_math.py
Labels: enhancement, to-be-backported

#5546 [backport] In-place update in `F.batch_renormalization`
  chainer/functions/normalization/batch_renormalization.py
  chainer/links/normalization/batch_renormalization.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
Labels: backport, enhancement

#5459 Grouped convolutions using matmul
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/deconvolution_nd.py
  chainer/utils/conv.py
  chainer/utils/conv_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
  tests/chainer_tests/utils_tests/test_conv.py
  tests/chainer_tests/utils_tests/test_conv_nd.py
Labels: enhancement, to-be-backported

#5548 Fix `D.Uniform.log_prob` to avoid returning -inf at boundary
  chainer/distributions/uniform.py
Labels: bug, to-be-backported

#5545 [backport] Add support for NumPy 1.15 in docs
  docs/source/install.rst
Labels: backport, document, st:test-and-merge

#5535 Import chainermn updates preserving commit logs
  chainermn/communicators/mpi_communicator_base.py
  chainermn/communicators/non_cuda_aware_communicator.py
  chainermn/communicators/single_node_communicator.py
  chainermn/functions/batch_normalization.py
  chainermn/links/batch_normalization.py
  chainermn/optimizers.py
  docs/source/chainermn/tutorial/tips_faqs.rst
  examples/chainermn/imagenet/train_imagenet.py
  examples/chainermn/parallel_convolution/parallel-conv.png
  tests/chainermn_tests/communicator_tests/test_communicator.py
  tests/chainermn_tests/datasets_tests/test_mnist.py
  tests/chainermn_tests/extensions_tests/test_checkpoint.py
  tests/chainermn_tests/links_tests/test_batch_normalization.py
  tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
  tests/chainermn_tests/optimizer_tests/test_multi_node_optimizer.py
Labels: ChainerMN

#5533 [backport] Use "documentation" instead of "document" in our documentation
  chainer/datasets/sub_dataset.py
  chainer/functions/array/get_item.py
  chainer/link.py
  chainer/utils/type_check.py
  chainermn/functions/pseudo_connect.py
  docs/source/compatibility.rst
  docs/source/contribution.rst
  docs/source/guides/gpu.rst
  docs/source/reference/check.rst
  docs/source/reference/static_graph_design.rst
  docs/source/upgrade_v2.rst
Labels: backport, document

#5558 Add upgrade guide for get_device_from_array
  docs/source/upgrade.rst
Labels: blocking, document, to-be-backported

#5560 [backport] Add upgrade guide for get_device_from_array
  docs/source/upgrade.rst
Labels: backport, blocking, document

#5302 Update ChainerMN documents
  docs/source/chainermn/index.rst
  docs/source/chainermn/installation/guide.rst
  docs/source/install.rst
  docs/source/upgrade.rst
Labels: ChainerMN, blocking, document, to-be-backported

#5562 [backport] ChainerMN: add an error message when mpi4py is missing
  chainermn/communicators/__init__.py
Labels: ChainerMN, backport, blocking, enhancement, st:test-and-merge

#5564 [backport] Update ChainerMN documents
  docs/source/chainermn/index.rst
  docs/source/chainermn/installation/guide.rst
  docs/source/install.rst
  docs/source/upgrade.rst
Labels: ChainerMN, backport, blocking, st:test-and-merge

#5553 Un-deprecate `Link.add_param` and `Link.add_link`
  chainer/link.py
  setup.cfg
  tests/chainer_tests/test_link.py
Labels: blocking, enhancement, to-be-backported

#5521 Update base docker image
  docker/python2/Dockerfile
  docker/python3/Dockerfile
  docs/source/upgrade.rst
Labels: blocking, install, to-be-backported

#5571 [backport] Update base docker image
  docker/python2/Dockerfile
  docker/python3/Dockerfile
  docs/source/upgrade.rst
Labels: backport, blocking, install

#5573 Add Python 3.7 support to installation docs
  docs/source/install.rst
Labels: document, to-be-backported

#5574 [backport] Add Python 3.7 support to installation docs
  docs/source/install.rst
Labels: backport, document

#5572 Fix test for python 3.7
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py
Labels: test, to-be-backported

#5576 [backport] Fix test for python 3.7
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py
Labels: backport, test

#5577 Fix for python 3.7
  chainer/functions/pooling/roi_average_align_2d.py
Labels: enhancement, to-be-backported

#5569 [backport] Un-deprecate `Link.add_param` and `Link.add_link`
  chainer/link.py
  setup.cfg
  tests/chainer_tests/test_link.py
Labels: backport, blocking, enhancement, st:test-and-merge

#5579 Bump version to v6.0.0a1
  chainer/_version.py
Labels: install

#5482 Fix `reporter.Summary` float value deserialization
  chainer/reporter.py
  chainer/testing/backend.py
  tests/chainer_tests/test_reporter.py
Labels: bug, st:test-and-merge, to-be-backported

#5550 [backport] Fix `D.Uniform.log_prob` to avoid returning -inf at boundary
  chainer/distributions/uniform.py
Labels: backport, bug

#5583 [backport] Add ChainerMN paper to references
  README.md
  chainermn_bibtex.txt
Labels: ChainerMN, backport, document

#5372 add `D.OneHotCategorical`
  chainer/distributions/__init__.py
  chainer/distributions/one_hot_categorical.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_one_hot_categorical.py
Labels: feature, st:test-and-merge

#5402 Serialize BestValueTrigger
  chainer/training/triggers/minmax_value_trigger.py
  tests/chainer_tests/training_tests/triggers_tests/test_minmax_trigger.py
Labels: feature, st:test-and-merge

#5584 [backport] Fix `reporter.Summary` float value deserialization
  chainer/reporter.py
  chainer/testing/backend.py
  tests/chainer_tests/test_reporter.py
Labels: backport, bug

#5586 Fix docstring of `F.forget`
  chainer/functions/util/forget.py
Labels: document, to-be-backported

#5434 Include ChainerCV doc
  docs/source/conf.py
  docs/source/reference/datasets.rst
  docs/source/reference/links.rst
Labels: document, to-be-backported

#5588 [backport] Fix docstring of `F.forget`
  chainer/functions/util/forget.py
Labels: backport, document

#5336 Support all float dtypes in `F.negative_sampling`
  chainer/functions/loss/negative_sampling.py
  tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
Labels: feature

#5598 [backport] Fix typo in updaters
  chainer/training/updaters/multiprocess_parallel_updater.py
  chainer/training/updaters/parallel_updater.py
  chainer/training/updaters/standard_updater.py
Labels: backport, document

#5596 Fix test warnings in NumPy 1.15
  setup.cfg
  tests/chainer_tests/utils_tests/test_type_check.py
Labels: st:test-and-merge, test, to-be-backported

#5544 [backport] Use `SerialIterator` in `train_mnist_custom_loop.py`
  examples/mnist/train_mnist_custom_loop.py
Labels: backport, example

#5599 [backport] Fix test warnings in NumPy 1.15
  setup.cfg
  tests/chainer_tests/utils_tests/test_type_check.py
Labels: backport, test

#5594 [backport] Support all float dtypes in `F.scatter_add` and `F.get_item`
  chainer/functions/array/get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_get_item.py
  tests/chainer_tests/functions_tests/array_tests/test_scatter_add.py
Labels: backport, feature, st:test-and-merge

#5597 Add `return_samples` argument to `F.negative_sampling` and `L.NegativeSampling`
  chainer/functions/loss/negative_sampling.py
  chainer/links/loss/negative_sampling.py
  tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
  tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
Labels: feature

#5593 [backport] Support all float dtypes in `F.negative_sampling`
  chainer/functions/loss/negative_sampling.py
  tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
Labels: backport, feature, st:test-and-merge

#5364 add `D.Poisson`
  chainer/distributions/__init__.py
  chainer/distributions/poisson.py
  docs/source/reference/distributions.rst
  tests/chainer_tests/distributions_tests/test_kldivergence.py
  tests/chainer_tests/distributions_tests/test_poisson.py
Labels: feature, st:test-and-merge

#5600 Improve iDeep version checking
  chainer/_version.py
  docs/source/install.rst
Labels: bug

#5601 [v5] Update docs for iDeep constraints
  docs/source/install.rst
Labels: document
