Repository chainer/chainer, pull requests merged in 2019-01, with the labels that each got.

#5746 ChainerX MNIST C++ example
  chainerx_cc/CMakeLists.txt
  chainerx_cc/examples/CMakeLists.txt
  chainerx_cc/examples/imagenet_py/image_dataset.py
  chainerx_cc/examples/imagenet_py/resnet50.py
  chainerx_cc/examples/imagenet_py/train_imagenet.py
  chainerx_cc/examples/mnist/CMakeLists.txt
  chainerx_cc/examples/mnist/mnist.cc
  chainerx_cc/examples/mnist/mnist.h
  chainerx_cc/examples/mnist/train_mnist.cc
  chainerx_cc/examples/mnist_py/.gitignore
  chainerx_cc/examples/mnist_py/README.md
  chainerx_cc/examples/mnist_py/download.sh
  chainerx_cc/examples/mnist_py/train_mnist.py
Labels: ChainerX, cat:example, st:test-and-merge

#5816 `L.NegativeSampling` ChainerX support
  chainer/functions/array/get_item.py
  chainer/functions/array/scatter_add.py
  chainer/functions/loss/negative_sampling.py
  tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
  tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
Labels: ChainerX

#5947 [backport] Transform dataset documentation fix
  chainer/datasets/transform_dataset.py
Labels: backport, cat:document

#5936 Fix visibility for pybind exception registration for macOS
  chainerx_cc/chainerx/macro.h
  chainerx_cc/chainerx/python/CMakeLists.txt
  chainerx_cc/chainerx/python/testing/device_buffer.cc
Labels: cat:install, st:test-and-merge

#5955 Check integrity of CuPy wheel for CUDA 10
  chainer/_version.py
Labels: cat:install, to-be-backported

#5951 Update the note in DCGAN example to be compatible with the code.
  docs/source/examples/dcgan.rst
Labels: cat:document, to-be-backported

#5956 [backport] Check integrity of CuPy wheel for CUDA 10
  setup.py
Labels: backport, cat:install

#4741 Add inference code to MNIST example
  examples/mnist/.gitignore
  examples/mnist/README.md
  examples/mnist/inference.py
  examples/mnist/train_mnist_custom_loop.py
  examples/mnist/train_mnist_data_parallel.py
  examples/mnist/train_mnist_model_parallel.py
Labels: cat:example, st:test-and-merge

#5511 Test statistics of initializers
  tests/chainer_tests/initializer_tests/test_normal.py
  tests/chainer_tests/initializer_tests/test_orthogonal.py
  tests/chainer_tests/initializer_tests/test_uniform.py
Labels: cat:test, st:test-and-merge, to-be-backported

#5882 Warn if `reset` method is not implemented in an iterator
  chainer/training/extensions/evaluator.py
  tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
Labels: cat:enhancement, st:test-and-merge

#5846 Add Travis matrix for macOS ChainerX tests
  .travis.yml
  scripts/ci/travis/run-tests.sh
Labels: ChainerX, cat:test, st:test-and-merge

#5416 Add `cached_property` decorator
  chainer/distributions/normal.py
  chainer/utils/cache.py
  tests/chainer_tests/utils_tests/test_cache.py
Labels: cat:feature, st:test-and-merge

#5957 Use FunctionNode on ROIPooling2D
  chainer/functions/pooling/roi_pooling_2d.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#5965 Fix doc of `F.softmax_cross_entropy` on output shape with `reduce=no`
  chainer/functions/loss/sigmoid_cross_entropy.py
  chainer/functions/loss/softmax_cross_entropy.py
Labels: cat:document, st:test-and-merge, to-be-backported

#5961 [backport] Test statistics of initializers
  tests/chainer_tests/initializer_tests/test_normal.py
  tests/chainer_tests/initializer_tests/test_orthogonal.py
  tests/chainer_tests/initializer_tests/test_uniform.py
Labels: backport, cat:test

#5962 [backport] Update the note in DCGAN example to be compatible with the code.
  docs/source/examples/dcgan.rst
Labels: backport, cat:document

#5969 [backport] Fix doc of `F.softmax_cross_entropy` on output shape with `reduce=no`
  chainer/functions/loss/sigmoid_cross_entropy.py
  chainer/functions/loss/softmax_cross_entropy.py
Labels: backport, cat:document

#5892 Cache attributes of distributions
  chainer/distributions/bernoulli.py
  chainer/distributions/beta.py
  chainer/distributions/categorical.py
  chainer/distributions/cauchy.py
  chainer/distributions/chisquare.py
  chainer/distributions/dirichlet.py
  chainer/distributions/exponential.py
  chainer/distributions/gamma.py
  chainer/distributions/geometric.py
  chainer/distributions/gumbel.py
  chainer/distributions/laplace.py
  chainer/distributions/log_normal.py
  chainer/distributions/multivariate_normal.py
  chainer/distributions/one_hot_categorical.py
  chainer/distributions/pareto.py
  chainer/distributions/poisson.py
  chainer/distributions/uniform.py
Labels: cat:enhancement

#5975 Make some docs of functions refer `ndarray`
  chainer/functions/evaluation/accuracy.py
  chainer/functions/evaluation/binary_accuracy.py
  chainer/functions/evaluation/classification_summary.py
  chainer/functions/evaluation/r2_score.py
  chainer/functions/loss/absolute_error.py
  chainer/functions/loss/black_out.py
  chainer/functions/loss/contrastive.py
  chainer/functions/loss/crf1d.py
  chainer/functions/loss/cross_covariance.py
  chainer/functions/loss/ctc.py
  chainer/functions/loss/decov.py
  chainer/functions/loss/discriminative_loss.py
  chainer/functions/loss/hinge.py
  chainer/functions/loss/huber_loss.py
  chainer/functions/loss/mean_absolute_error.py
  chainer/functions/loss/mean_squared_error.py
  chainer/functions/loss/negative_sampling.py
  chainer/functions/loss/sigmoid_cross_entropy.py
  chainer/functions/loss/softmax_cross_entropy.py
  chainer/functions/loss/squared_error.py
  chainer/functions/loss/triplet.py
  chainer/functions/loss/vae.py
  chainer/functions/noise/dropout.py
  chainer/functions/noise/gaussian.py
  chainer/functions/noise/gumbel_softmax.py
  chainer/functions/noise/simplified_dropconnect.py
  chainer/functions/noise/zoneout.py
  chainer/functions/normalization/batch_normalization.py
  chainer/functions/normalization/group_normalization.py
  chainer/functions/normalization/l2_normalization.py
  chainer/functions/normalization/layer_normalization.py
  chainer/functions/normalization/local_response_normalization.py
  chainer/functions/util/forget.py
Labels: cat:document, to-be-backported

#4472 Asynchronous snapshot writers
  chainer/serializers/hdf5.py
  chainer/serializers/npz.py
  chainer/training/extensions/_snapshot.py
  chainer/training/extensions/snapshot_writers.py
  docs/source/reference/snapshot_writers.rst
  docs/source/reference/training.rst
  tests/chainer_tests/serializers_tests/test_npz.py
  tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
  tests/chainer_tests/training_tests/extensions_tests/test_snapshot_writers.py
Labels: cat:feature, takeover

#5976 [backport] Make some docs of functions refer `ndarray`
  chainer/functions/evaluation/accuracy.py
  chainer/functions/evaluation/binary_accuracy.py
  chainer/functions/evaluation/classification_summary.py
  chainer/functions/evaluation/r2_score.py
  chainer/functions/loss/absolute_error.py
  chainer/functions/loss/black_out.py
  chainer/functions/loss/contrastive.py
  chainer/functions/loss/crf1d.py
  chainer/functions/loss/cross_covariance.py
  chainer/functions/loss/ctc.py
  chainer/functions/loss/decov.py
  chainer/functions/loss/discriminative_loss.py
  chainer/functions/loss/hinge.py
  chainer/functions/loss/huber_loss.py
  chainer/functions/loss/mean_absolute_error.py
  chainer/functions/loss/mean_squared_error.py
  chainer/functions/loss/negative_sampling.py
  chainer/functions/loss/sigmoid_cross_entropy.py
  chainer/functions/loss/softmax_cross_entropy.py
  chainer/functions/loss/squared_error.py
  chainer/functions/loss/triplet.py
  chainer/functions/loss/vae.py
  chainer/functions/noise/dropout.py
  chainer/functions/noise/gaussian.py
  chainer/functions/noise/gumbel_softmax.py
  chainer/functions/noise/simplified_dropconnect.py
  chainer/functions/noise/zoneout.py
  chainer/functions/normalization/batch_normalization.py
  chainer/functions/normalization/group_normalization.py
  chainer/functions/normalization/l2_normalization.py
  chainer/functions/normalization/layer_normalization.py
  chainer/functions/normalization/local_response_normalization.py
  chainer/functions/util/forget.py
Labels: backport, cat:document, st:test-and-merge

#5967 [backport] Use FunctionNode on ROIPooling2D
  chainer/functions/pooling/roi_pooling_2d.py
Labels: backport, cat:enhancement

#5981 Raise an appropriate error on cuDNN RNN backward in testing mode
  chainer/functions/connection/n_step_rnn.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: cat:bug, to-be-backported

#5814 Fix error message of `testing.assert_allclose`
  chainer/testing/array.py
  tests/chainer_tests/testing_tests/test_array.py
Labels: cat:enhancement, to-be-backported

#5972 improve `F.elu` memory consumption by retaining output
  chainer/functions/activation/elu.py
  tests/chainer_tests/functions_tests/activation_tests/test_elu.py
Labels: cat:enhancement

#5941 Fix code formatting
  chainerx_cc/chainerx/cuda/cuda_device/memory.cc
Labels: ChainerX, cat:code-fix, st:test-and-merge

#5973 Allow `import chainer.testing` without pytest
  chainer/testing/_distribution_test.py
  chainer/testing/distribution_test.py
Labels: cat:bug, to-be-backported

#5829 Batched pack/unpack params before/after allreduce
  chainermn/communicators/__init__.py
  chainermn/communicators/pure_nccl_communicator.py
  tests/chainermn_tests/communicator_tests/test_communicator.py
Labels: ChainerMN, cat:enhancement, prio:medium

#5983 [backport] Raise an appropriate error on cuDNN RNN backward in testing mode
  chainer/functions/connection/n_step_rnn.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: backport, cat:bug

#5984 [backport] Fix error message of `testing.assert_allclose`
  chainer/testing/array.py
  tests/chainer_tests/testing_tests/test_array.py
Labels: backport, cat:enhancement, st:test-and-merge

#5914 Add copyparams method to Sequential
  chainer/sequential.py
  tests/chainer_tests/test_sequential.py
Labels: cat:bug, to-be-backported

#5979 Fix document in NStepLSTM/NStepRNN
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
Labels: cat:document, to-be-backported

#5282 Fix document in NStepLSTM/NStepRNN
  chainer/links/connection/n_step_lstm.py
  chainer/links/connection/n_step_rnn.py
Labels: cat:document, st:awaiting-response

#5994 Avoid deprecated `numpy.asscalar`
  chainer/functions/math/basic_math.py
Labels: cat:code-fix

#5948 Override _to_device for consistency
  chainer/links/connection/mgu.py
Labels: ChainerX, cat:bug, st:test-and-merge

#5937 [backport] Improve installation guide of ChainerMN
  docs/source/chainermn/installation/guide.rst
Labels: ChainerMN, backport, cat:document

#5861 Stop managing memory in max pooling specific manner
  chainer/functions/pooling/max_pooling_2d.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/pooling_2d.py
  chainer/functions/pooling/pooling_nd.py
Labels: cat:enhancement

#6007 Remove chainerx.asscalar
  chainerx/_docs/routines.py
  chainerx_cc/chainerx/python/routines.cc
  docs/source/chainerx/reference/routines.rst
  tests/chainerx_tests/acceptance_tests/test_elementwise.rst
  tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Labels: ChainerX, st:test-and-merge

#6002 Fix travis script to continue on failure in each step
  scripts/ci/travis/run-tests.sh
Labels: cat:test, prio:high

#5603 Show forward stacktrace in backward
  chainer/_backprop_utils.py
  tests/chainer_tests/test_variable.py
Labels: cat:enhancement

#6014 Post macro comment for consistency
  chainerx_cc/chainerx/cuda/cuda_runtime.cc
  chainerx_cc/chainerx/cuda/elementwise.cuh
  chainerx_cc/chainerx/cuda/reduce.cuh
  chainerx_cc/chainerx/macro.h
Labels: cat:code-fix, st:test-and-merge

#5763 Improve coding style
  chainer/backend.py
  chainer/configuration.py
  chainer/function_node.py
  chainer/initializers/__init__.py
  chainer/iterators/multiprocess_iterator.py
  chainer/iterators/multithread_iterator.py
  chainer/iterators/serial_iterator.py
  chainer/link.py
  chainerx/__init__.py
  chainerx_cc/examples/imagenet_py/resnet50.py
  chainerx_cc/examples/mnist_py/train_mnist.py
  tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
  tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
  tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Labels: cat:code-fix

#5971 Use more precise timer in funciton_hooks/timer.py
  chainer/function_hooks/timer.py
  tests/chainer_tests/function_hooks_tests/test_timer.py
Labels: cat:enhancement

#5966 Add 'mean' value as an option for vae loss reduce
  chainer/functions/loss/vae.py
  tests/chainer_tests/functions_tests/loss_tests/test_vae.py
Labels: cat:feature

#5904 Allow mixing `testing.inject_backend_tests` and `testing.parameterize`
  chainer/testing/_bundle.py
  chainer/testing/backend.py
  chainer/testing/parameterized.py
  chainer/testing/random.py
  tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
Labels: cat:enhancement, no-compat, st:test-and-merge

#6022 [backport] Introduce `utils.mixed_presision` decorator
  chainer/utils/precision.py
  tests/chainer_tests/utils_tests/test_precision.py
Labels: backport, cat:feature

#5821 CuPy/ChainerX memory pool sharing
  chainerx/__init__.py
  chainerx/__init__.pyi
  chainerx/_cuda.py
  chainerx_cc/chainerx/cuda/cuda_device.h
  chainerx_cc/chainerx/python/CMakeLists.txt
  chainerx_cc/chainerx/python/core_module.cc
  chainerx_cc/chainerx/python/cuda/cuda_module.cc
  chainerx_cc/chainerx/python/cuda/cuda_module.h
Labels: cat:feature, st:test-and-merge

#6013 [backport] Use default dtype in `L.NegativeSampling`
  chainer/links/loss/negative_sampling.py
  tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
Labels: backport, cat:feature

#5619 Add type check for `r` arg of `F.rrelu`
  chainer/functions/activation/rrelu.py
  tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
Labels: cat:enhancement

#6021 [backport] Use more precise timer in funciton_hooks/timer.py
  chainer/function_hooks/timer.py
  tests/chainer_tests/function_hooks_tests/test_timer.py
Labels: backport, cat:enhancement

#5998 [backport] Allow `import chainer.testing` without pytest
  chainer/testing/_distribution_test.py
  chainer/testing/distribution_test.py
Labels: backport, cat:bug

#6011 [backport] Support all float dtypes in `F.connectionist_temporal_classification`
  chainer/functions/loss/ctc.py
  tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Labels: backport, cat:feature

#5990 [backport] Add copyparams method to Sequential
  chainer/sequential.py
  tests/chainer_tests/test_sequential.py
Labels: backport, cat:bug

#6028 Fix `inject_backend_tests` `multi_gpu` test mark
  chainer/testing/backend.py
Labels: cat:test

#6029 Allow doctest to run in single-GPU environment
  chainer/links/theano/theano_function.py
  chainer/testing/__init__.py
  chainer/testing/doctest_helper.py
  chainer/testing/helper.py
  docs/source/conf.py
  docs/source/guides/gpu.rst
Labels: cat:test

#6032 Make docs of math functions refer `ndarray`
  chainer/functions/math/average.py
  chainer/functions/math/batch_l2_norm_squared.py
  chainer/functions/math/bias.py
  chainer/functions/math/ceil.py
  chainer/functions/math/clip.py
  chainer/functions/math/cumprod.py
  chainer/functions/math/cumsum.py
  chainer/functions/math/det.py
  chainer/functions/math/digamma.py
  chainer/functions/math/erf.py
  chainer/functions/math/erfc.py
  chainer/functions/math/erfcinv.py
  chainer/functions/math/erfcx.py
  chainer/functions/math/erfinv.py
  chainer/functions/math/exponential.py
  chainer/functions/math/exponential_m1.py
  chainer/functions/math/fft.py
  chainer/functions/math/fix.py
  chainer/functions/math/floor.py
  chainer/functions/math/fmod.py
  chainer/functions/math/hyperbolic.py
  chainer/functions/math/inv.py
  chainer/functions/math/lgamma.py
  chainer/functions/math/linear_interpolate.py
  chainer/functions/math/log_ndtr.py
  chainer/functions/math/logarithm_1p.py
  chainer/functions/math/logsumexp.py
  chainer/functions/math/matmul.py
  chainer/functions/math/maximum.py
  chainer/functions/math/minimum.py
  chainer/functions/math/minmax.py
  chainer/functions/math/ndtr.py
  chainer/functions/math/ndtri.py
  chainer/functions/math/polygamma.py
  chainer/functions/math/prod.py
  chainer/functions/math/scale.py
  chainer/functions/math/sign.py
  chainer/functions/math/sqrt.py
  chainer/functions/math/square.py
  chainer/functions/math/squared_difference.py
  chainer/functions/math/sum.py
  chainer/functions/math/tensordot.py
  chainer/functions/math/trigonometric.py
Labels: cat:document, to-be-backported

#6034 [backport] Make docs of math functions refer `ndarray`
  chainer/functions/math/average.py
  chainer/functions/math/batch_l2_norm_squared.py
  chainer/functions/math/bias.py
  chainer/functions/math/ceil.py
  chainer/functions/math/clip.py
  chainer/functions/math/cumprod.py
  chainer/functions/math/cumsum.py
  chainer/functions/math/det.py
  chainer/functions/math/digamma.py
  chainer/functions/math/erf.py
  chainer/functions/math/erfc.py
  chainer/functions/math/erfcinv.py
  chainer/functions/math/erfcx.py
  chainer/functions/math/erfinv.py
  chainer/functions/math/exponential.py
  chainer/functions/math/exponential_m1.py
  chainer/functions/math/fft.py
  chainer/functions/math/fix.py
  chainer/functions/math/floor.py
  chainer/functions/math/fmod.py
  chainer/functions/math/hyperbolic.py
  chainer/functions/math/inv.py
  chainer/functions/math/lgamma.py
  chainer/functions/math/linear_interpolate.py
  chainer/functions/math/log_ndtr.py
  chainer/functions/math/logarithm_1p.py
  chainer/functions/math/logsumexp.py
  chainer/functions/math/matmul.py
  chainer/functions/math/maximum.py
  chainer/functions/math/minimum.py
  chainer/functions/math/minmax.py
  chainer/functions/math/ndtr.py
  chainer/functions/math/ndtri.py
  chainer/functions/math/polygamma.py
  chainer/functions/math/prod.py
  chainer/functions/math/scale.py
  chainer/functions/math/sign.py
  chainer/functions/math/sqrt.py
  chainer/functions/math/square.py
  chainer/functions/math/squared_difference.py
  chainer/functions/math/sum.py
  chainer/functions/math/tensordot.py
  chainer/functions/math/trigonometric.py
Labels: backport, cat:document

#6035 [backport] Adjust testing tolerance of F.connectionist_temporal_classification
  tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Labels: backport, cat:test

#6037 Fix CUDA specific Python binding
  chainerx_cc/chainerx/python/CMakeLists.txt
Labels: cat:install

#6043 Fix `chainerx.maximum` to restore CUDA device
  chainerx_cc/chainerx/cuda/cuda_device/activation.cu
Labels: cat:bug, st:test-and-merge

#6017 Document CuPy memory pool sharing
  docs/source/chainerx/index.rst
  docs/source/chainerx/tips.rst
Labels: ChainerX, cat:document, st:test-and-merge

#6044 Test if the default CUDA device keeps being 0 after each test
  tests/chainer_tests/conftest.py
Labels: cat:test, to-be-backported

#6038 [backport] add a naive TimerHook LinkHook.
  chainer/link_hook.py
  chainer/link_hooks/__init__.py
  chainer/link_hooks/timer.py
  docs/source/reference/links.rst
  setup.py
  tests/chainer_tests/link_hooks_tests/test_timer.py
Labels: backport, cat:feature

#5949 Do not ignore FutureWarning other than experimental features
  setup.cfg
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: cat:test, st:test-and-merge, to-be-backported

#6047 [backport] Test if the default CUDA device keeps being 0 after each test
  tests/chainer_tests/conftest.py
Labels: backport, cat:test, st:test-and-merge

#5782 Encode parameters in parameterized class name
  chainer/testing/parameterized.py
Labels: cat:enhancement, cat:test

#5993 Fix FixedCapacityDummyAllocator in CUDA memory pool test
  chainerx_cc/chainerx/cuda/memory_pool_test.cc
  chainerx_cc/chainerx/testing/threading.h
Labels: cat:test, st:test-and-merge

#6046 Fix wrong MNIST MLP anchor
  docs/source/examples/mnist.rst
  docs/source/guides/serializers.rst
Labels: cat:document, to-be-backported

#5940 Avoid `cudaMemcpyAsync` for pinned memory for faster host-to-device transfer
  chainerx_cc/chainerx/cuda/cuda_device.cc
  chainerx_cc/chainerx/cuda/cuda_device.h
  chainerx_cc/chainerx/cuda/cuda_device/memory.cc
Labels: cat:enhancement, prio:high, st:test-and-merge

#5902 Add F.as_strided
  chainer/functions/__init__.py
  chainer/functions/array/as_strided.py
  docs/source/reference/functions.rst
  tests/chainer_tests/functions_tests/array_tests/test_as_strided.py
Labels: cat:feature

#3499 `FunctionTestCase` for function tests
  chainer/_backend.py
  chainer/backends/_chainerx.py
  chainer/backends/_cpu.py
  chainer/backends/cuda.py
  chainer/backends/intel64.py
  chainer/functions/activation/clipped_relu.py
  chainer/gradient_check.py
  chainer/testing/__init__.py
  chainer/testing/array.py
  chainer/testing/function.py
  chainer/testing/parameterized.py
  chainer/utils/__init__.py
  chainer/utils/error.py
  chainerx/__init__.py
  chainerx/_fallback_workarounds.py
  docs/source/reference/check.rst
  tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
  tests/chainer_tests/functions_tests/activation_tests/test_relu.py
  tests/chainer_tests/functions_tests/array_tests/test_hstack.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
  tests/chainer_tests/functions_tests/connection_tests/test_linear.py
  tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
  tests/chainer_tests/testing_tests/test_function.py
Labels: cat:test

#6057 Fix stochastic failure in `WalkerAlias`
  chainer/utils/walker_alias.py
Labels: cat:bug, st:test-and-merge

#6065 Fix manifest typos
  MANIFEST.in
Labels: cat:install, prio:high

#6069 Skip ChainerX float16 tests when FunctionTestCase is used
  chainer/testing/function.py
  tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
  tests/chainer_tests/functions_tests/activation_tests/test_relu.py
  tests/chainer_tests/functions_tests/array_tests/test_hstack.py
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
Labels: cat:test, st:test-and-merge

#5832 Converter decorator for ChainerX device support
  chainer/dataset/__init__.py
  chainer/dataset/convert.py
  chainer/training/updaters/standard_updater.py
  docs/source/reference/datasets.rst
  tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py
Labels: cat:feature

#5615 Make signs generated by `initializers.Orthogonal` unbiased
  chainer/initializers/orthogonal.py
  tests/chainer_tests/initializer_tests/test_orthogonal.py
Labels: cat:bug

#5539 Unchain all variables after running extensions
  chainer/training/extensions/__init__.py
  chainer/training/extensions/variable_unchain.py
  docs/source/reference/training.rst
Labels: cat:feature

#6048 Fix chainermn tests
  tests/chainermn_tests/communicator_tests/test_communicator.py
  tests/chainermn_tests/conftest.py
Labels: ChainerMN

#6051 Add NOLINT to reinterpret cast
  chainerx_cc/chainerx/python/cuda/cuda_module.cc
Labels: cat:code-fix, st:test-and-merge

#6062 Upgrade clang-tidy to 6.0
  scripts/ci/chainerx/setup-ubuntu.sh
Labels: ChainerX, cat:install, st:test-and-merge

#6060 Limit the length of parameterized test class name
  chainer/testing/parameterized.py
Labels: cat:test, st:test-and-merge

#5992 Fix thread safety of CUDA memory pool FreeUnusedBlocks
  chainerx_cc/chainerx/cuda/memory_pool.cc
  chainerx_cc/chainerx/cuda/memory_pool_test.cc
Labels: cat:bug, st:test-and-merge

#5989 Support NumPy integers in `chainerx.ndarray.__getitem__`
  chainerx_cc/chainerx/python/array_index.cc
  tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
Labels: cat:performance, prio:high, st:test-and-merge

#6055 [backport] Fix wrong MNIST MLP anchor
  docs/source/examples/mnist.rst
  docs/source/guides/serializers.rst
Labels: backport, cat:document

#6064 DimsFormatter to print StackVector<int64_t, kMaxNdim>
  chainerx_cc/chainerx/CMakeLists.txt
  chainerx_cc/chainerx/dims.cc
  chainerx_cc/chainerx/dims.h
  chainerx_cc/chainerx/dims_test.cc
Labels: cat:enhancement, st:test-and-merge

#5823 Simplify `F.concat` test
  tests/chainer_tests/functions_tests/array_tests/test_concat.py
Labels: cat:test, st:test-and-merge

#5999 Fix python 3.5 incompatibility in Chainer X train_mnist.py example
  chainerx_cc/examples/mnist_py/train_mnist.py
Labels: cat:bug, prio:high, st:test-and-merge

#5988 Fix pickling of ChainerX link
  chainer/variable.py
  chainerx/__init__.py
  chainerx/_device.py
  chainerx_cc/chainerx/python/array.cc
  chainerx_cc/chainerx/python/device.cc
  tests/chainerx_tests/unit_tests/test_array.py
  tests/chainerx_tests/unit_tests/test_device.py
Labels: cat:bug, prio:high, st:test-and-merge

#6070 Simplify `F.crelu` and `F.elu` test
  chainerx_cc/chainerx/python/array.cc
  tests/chainer_tests/functions_tests/activation_tests/test_crelu.py
  tests/chainer_tests/functions_tests/activation_tests/test_elu.py
Labels: cat:test, st:test-and-merge

#6091 Fix seq2seq example
  examples/seq2seq/seq2seq.py
Labels: cat:example, to-be-backported

#6033 Add `Variable._init_unchecked()` static method for faster instantiation
  chainer/backend.py
  chainer/function_node.py
  chainer/optimizer.py
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: cat:performance, st:test-and-merge

#6090 fix typo in classifier.py
  chainer/links/model/classifier.py
Labels: cat:document, to-be-backported

#6093 [backport] Fix seq2seq example
  examples/seq2seq/seq2seq.py
Labels: backport, cat:example

#6067 Validate Conv, ConvTranspose stride
  chainerx_cc/chainerx/routines/connection.cc
  chainerx_cc/chainerx/routines/connection_test.cc
Labels: cat:bug, st:test-and-merge

#6066 Validate `{Max,Average}Pool` `kernel_size` and `stride`
  chainerx_cc/chainerx/routines/pooling.cc
  chainerx_cc/chainerx/routines/pooling_test.cc
Labels: ChainerX, cat:bug, st:test-and-merge

#6085 Fix cupy import failure detection
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#6100 Reduce memory usage in `MultiprocessParallelUpdater`
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#6105 Fix memory leak during backprop in Python 2
  chainer/utils/_collections.py
  chainer/variable.py
Labels: cat:bug, to-be-backported

#6114 Use `CMAKE_CURRENT_BINARY_DIR` in `CMakeLists.txt`
  chainerx_cc/CMakeLists.txt
Labels: cat:install, st:test-and-merge

#6113 [backport] Reduce memory usage in `MultiprocessParallelUpdater`
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: backport, cat:enhancement

#6108 Remove legacy `CHAINERX_CUDA_MULTITHREAD_TEST_SEGV_WORKAROUND` from Jenkins script
  scripts/ci/steps.sh
Labels: cat:test, st:test-and-merge

#6082 Fix Travis CI ignoring non-last command errors in each step
  scripts/ci/travis/run-step.sh
  scripts/ci/travis/run-tests.sh
  scripts/ci/travis/steps.sh
Labels: cat:test, st:test-and-merge

#6124 Move Jenkins mypy check to misc matrix
  scripts/ci/chainerx/jenkins/run.sh
  scripts/ci/steps.sh
Labels: cat:test, st:test-and-merge

#6099 Fix iterator syntax in MNIST custom loop example
  examples/mnist/train_mnist_custom_loop.py
Labels: cat:example, to-be-backported

#6126 Do not compare `xp` with `numpy` for cupy code path
  chainer/functions/activation/log_softmax.py
  chainer/functions/activation/softmax.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/normalization/batch_normalization.py
  chainer/functions/pooling/average_pooling_nd.py
  chainer/functions/theano/theano_function.py
  chainer/initializers/normal.py
  chainermn/functions/batch_normalization.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  tests/chainer_tests/link_hooks_tests/test_timer.py
Labels: cat:bug, st:test-and-merge

#6109 Run ChainerX python tests in Travis CI
  scripts/ci/travis/run-tests.sh
  scripts/ci/travis/steps.sh
  tests/chainerx_tests/acceptance_tests/conftest.py
Labels: cat:test, st:test-and-merge

#6110 Enable ChainerX C++ test in Travis CI
  .travis.yml
  scripts/ci/travis/run-tests.sh
  scripts/ci/travis/steps.sh
Labels: cat:test, st:test-and-merge

#6130 Remove anchor to non-existing section
  chainerx.md
Labels: cat:document, st:test-and-merge

#6102 [backport] Fix typo in `classifier.py`
  chainer/links/model/classifier.py
Labels: backport, cat:document, st:test-and-merge

#6111 Document NumPy 1.16 support
  docs/source/install.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#5985 Use ideep in optimizers properly
  chainer/optimizers/adam.py
  chainer/optimizers/corrected_momentum_sgd.py
  chainer/optimizers/momentum_sgd.py
Labels: cat:bug, to-be-backported

#6136 Fix tolerance and numeric grad precision in `F.triplet` test
  tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
Labels: cat:test, st:test-and-merge, to-be-backported

#6123 Remove unused test step
  scripts/ci/steps.sh
Labels: cat:test, st:test-and-merge

#6144 [backport] Fix tolerance and numeric grad precision in `F.triplet` test
  tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
Labels: backport, cat:test

#6128 Fix import order
  chainer/distributions/multivariate_normal.py
  chainer/functions/loss/vae.py
  chainer/variable.py
Labels: cat:code-fix

#6118 Fix `FunctionNode.get_retained_outputs` to return `()` if no output is retained
  chainer/function_node.py
  tests/chainer_tests/test_function_node.py
Labels: cat:bug, st:test-and-merge

#6141 [backport] Document NumPy 1.16 support
  docs/source/install.rst
Labels: backport, cat:document

#6112 [backport] Fix cupy import failure detection
  chainer/training/updaters/multiprocess_parallel_updater.py
Labels: backport, cat:bug, st:test-and-merge

#6142 Reorganize documentation for easier access to tutorials and examples
  docs/source/guides/index.rst
  docs/source/index.rst
  docs/source/reference/index.rst
Labels: cat:document

#6147 [backport] Fix `dump_graph` not to memory leak
  chainer/training/extensions/computational_graph.py
Labels: backport, cat:bug

#6138 CuPy cannot be enabled when cuDNN is unavailable
  chainer/backends/cuda.py
Labels: cat:bug, st:test-and-merge

#6149 Remove Travis Ubuntu Py34 job
  .travis.yml
Labels: cat:test, st:test-and-merge

#6107 Remove Travis macOS Py34 job
  .travis.yml
Labels: cat:test, st:test-and-merge

#5652 Fix `pseudo_connect` with `None` input
  chainermn/functions/pseudo_connect.py
  chainermn/links/multi_node_chain_list.py
  chainermn/links/n_step_rnn.py
  tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
  tests/chainermn_tests/functions_tests/test_pseudo_connect.py
  tests/chainermn_tests/links_tests/test_n_step_rnn.py
Labels: ChainerMN

#6121 Fix `get_retained_{in/out}puts` to return `None` for `None` inputs/outputs
  chainer/function.py
  chainer/function_node.py
  tests/chainer_tests/test_backprop.py
Labels: no-compat, st:test-and-merge

#6143 [backport] Use ideep in optimizers properly
  chainer/optimizers/adam.py
  chainer/optimizers/corrected_momentum_sgd.py
  chainer/optimizers/momentum_sgd.py
Labels: backport, cat:bug

#5716 [backport] Refactor `train_mnist_dual_parallel.py`
  examples/chainermn/mnist/train_mnist_dual_parallel.py
Labels: ChainerMN, backport, cat:example

#6086 [backport] Fix chainermn tests
  tests/chainermn_tests/communicator_tests/test_communicator.py
  tests/chainermn_tests/conftest.py
Labels: ChainerMN, backport

#6152 [backport] Reorganize documentation for easier access to tutorials and examples
  docs/source/guides/index.rst
  docs/source/index.rst
  docs/source/reference/index.rst
Labels: backport, cat:document, st:test-and-merge
