Repository chainer/chainer, pull requests merged in 2019-02, with the labels that each got.

#6098 Call `Iterator.finalize` from `__del__` and `__exit__`
  chainer/dataset/iterator.py
  chainer/iterators/multiprocess_iterator.py
  chainer/iterators/multithread_iterator.py
Labels: cat:feature, st:test-and-merge

#6164 Fix unit test collection timeout
  setup.py
Labels: cat:test

#6159 Do not compare `xp` with `numpy` for cupy code path (cont.)
  chainer/training/extensions/variable_statistics_plot.py
Labels: cat:bug, st:test-and-merge

#6166 Set CMake policy in a proper way
  chainerx_cc/CMakeLists.txt
Labels: ChainerX, cat:install, st:test-and-merge

#6156 Check Array constructor for nullptr
  chainerx_cc/chainerx/array.h
  chainerx_cc/chainerx/array_test.cc
Labels: cat:bug, st:test-and-merge

#6063 `chainerx.grad` Python binding
  chainerx/_docs/backprop.py
  chainerx_cc/chainerx/array.cc
  chainerx_cc/chainerx/array.h
  chainerx_cc/chainerx/python/backward.cc
  tests/chainerx_tests/unit_tests/test_backward.py
Labels: cat:feature, st:test-and-merge

#6139 Fix double-backprop of `F.rrelu`
  chainer/functions/activation/rrelu.py
  tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
Labels: cat:bug, st:test-and-merge

#6122 Support FunctionNode None inputs in ChainerX
  chainer/function_node.py
  chainerx_cc/chainerx/backward_builder.cc
  chainerx_cc/chainerx/python/chainer_interop.cc
  tests/chainer_tests/test_backprop.py
Labels: ChainerX

#6171 Fix `Optimizer` to convert state arrays back to ChainerX
  chainer/optimizer.py
Labels: ChainerX, cat:bug, st:test-and-merge

#6054 Wrap platform specific operations and reduce macro usage
  chainerx_cc/chainerx/CMakeLists.txt
  chainerx_cc/chainerx/context.cc
  chainerx_cc/chainerx/context_test.cc
  chainerx_cc/chainerx/cuda/cuda_backend.cc
  chainerx_cc/chainerx/cuda/cuda_backend_test.cc
  chainerx_cc/chainerx/dynamic_lib.cc
  chainerx_cc/chainerx/dynamic_lib.h
  chainerx_cc/chainerx/platform.cc
  chainerx_cc/chainerx/platform.h
  chainerx_cc/chainerx/platform/windows.cc
  chainerx_cc/chainerx/platform/windows.h
  chainerx_cc/chainerx/testing/util.cc
  chainerx_cc/chainerx/util.cc
  chainerx_cc/chainerx/util.h
Labels: ChainerX, cat:code-fix, st:test-and-merge

#6172 Stop mypy in CIs
  appveyor.yml
  scripts/ci/chainerx/jenkins/run.sh
  scripts/ci/steps.sh
  scripts/ci/travis/run-tests.sh
  scripts/ci/travis/steps.sh
Labels: cat:test

#6135 Fix filtering `FutureWarning`
  setup.cfg
  tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
Labels: cat:test, to-be-backported

#6177 Fix old and broken PTB url
  chainer/datasets/ptb.py
Labels: cat:document, to-be-backported

#6180 [backport] Fix old and broken PTB url
  chainer/datasets/ptb.py
Labels: backport, cat:document, st:test-and-merge

#6169 Check input size consistency in RNN and LSTM when using cuDNN
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#6183 Add upgrade guide for use of forward method
  docs/source/upgrade.rst
Labels: cat:document, to-be-backported

#6173 Simplify `F.tanh` test
  tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
Labels: cat:test

#6175 Add dilate argument to L.Deconvolution2D
  chainer/links/connection/deconvolution_2d.py
  tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
Labels: cat:feature

#6189 Add `FunctionTestCase` to documentation
  docs/source/reference/check.rst
Labels: cat:document, st:test-and-merge

#6193 [backport] Add upgrade guide for use of forward method
  docs/source/upgrade.rst
Labels: backport, cat:document

#6186 [backport] Check input size consistency in RNN and LSTM when using cuDNN
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
  tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
Labels: backport, cat:enhancement, st:test-and-merge

#6081 Add sequence and numpy array indices support to `ndarray.take`
  chainerx/__init__.pyi
  chainerx_cc/chainerx/python/array.cc
  chainerx_cc/chainerx/python/array.h
  chainerx_cc/chainerx/python/routines.cc
  tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
Labels: ChainerX, cat:enhancement

#6174 Simplify `F.sigmoid` test
  tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py
Labels: cat:test

#6202 Remove bad brew option from Travis CI
  scripts/ci/travis/steps.sh
Labels: cat:install

#5822 Simplify `F.mean_squared_error` test
  tests/chainer_tests/functions_tests/loss_tests/test_mean_squared_error.py
Labels: cat:test

#6206 Minor fix on README of seq2seq example
  examples/seq2seq/README.md
Labels: cat:example, to-be-backported

#6205 Fix seq2seq example encoding problem on Python3
  examples/seq2seq/seq2seq.py
Labels: cat:example, to-be-backported

#6209 [backport] Fix seq2seq example encoding problem on Python3
  examples/seq2seq/seq2seq.py
Labels: backport, cat:example

#6208 [backport] Minor fix on README of seq2seq example
  examples/seq2seq/README.md
Labels: backport, cat:example

#6192 simplify `F.hard_sigmoid` test
  tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py
Labels: cat:test

#6042 Make docs of functions refer `ndarray`
  chainer/functions/activation/rrelu.py
  chainer/functions/loss/vae.py
  chainer/functions/noise/simplified_dropconnect.py
  chainer/functions/pooling/max_pooling_2d.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/upsampling_2d.py
  chainer/functions/util/forget.py
Labels: cat:document, to-be-backported

#6179 Add imports of initializers and math, required in "Define your own function" examples
  docs/source/imports.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#6219 Add references for n-dimensional arrays
  chainer/dataset/convert.py
  chainer/distributions/cauchy.py
  chainer/distributions/geometric.py
  chainer/function.py
  chainer/function_hook.py
  chainer/function_node.py
  chainer/initializer.py
  chainer/initializers/__init__.py
  chainer/initializers/constant.py
  chainer/links/activation/simplified_dropconnect.py
  chainer/links/connection/gru.py
  chainer/links/connection/lstm.py
  chainer/links/normalization/batch_normalization.py
  chainer/utils/sparse.py
  chainer/variable.py
Labels: cat:document, to-be-backported

#6223 Imagenet README.md typo
  examples/imagenet/README.md
Labels: cat:document, to-be-backported

#6221 [backport] Add references for n-dimensional arrays
  chainer/dataset/convert.py
  chainer/function.py
  chainer/function_hook.py
  chainer/function_node.py
  chainer/initializer.py
  chainer/initializers/__init__.py
  chainer/initializers/constant.py
  chainer/links/activation/simplified_dropconnect.py
  chainer/links/connection/gru.py
  chainer/links/connection/lstm.py
  chainer/links/normalization/batch_normalization.py
  chainer/utils/sparse.py
  chainer/variable.py
Labels: backport, cat:document

#6220 [backport] Add imports of initializers and math, required in "Define your own function" examples
  docs/source/imports.rst
Labels: backport, cat:document

#6227 Use FMA in `NativeDevice::Dot`
  chainerx_cc/chainerx/native/native_device/dot.cc
Labels: ChainerX, cat:enhancement

#6218 Fix ChainerX fallback for replaced optimizer state
  chainer/optimizer.py
Labels: ChainerX, st:test-and-merge

#6224 [backport] Imagenet README.md typo
  examples/imagenet/README.md
Labels: backport, cat:document

#5830 ChainerX seq2seq example
  chainer/functions/connection/n_step_lstm.py
  docs/source/examples/seq2seq.rst
  examples/seq2seq/seq2seq.py
Labels: cat:example, st:test-and-merge

#5634 support spatial_scale >= 1.0 in roi_average_align_2d.py
  chainer/functions/pooling/roi_average_align_2d.py
  chainer/functions/pooling/roi_max_align_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py
Labels: cat:enhancement, domain:cv

#6182 Update URL of PTB dataset
  chainer/datasets/ptb.py
Labels: cat:document, st:test-and-merge, to-be-backported

#6184 Avoid `# NOQA` in docstrings
  chainer/datasets/svhn.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_rnn.py
  chainer/functions/loss/negative_sampling.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_2d.py
  chainer/links/connection/deconvolution_nd.py
  chainer/links/connection/mlp_convolution_2d.py
  chainer/training/extensions/_snapshot.py
  chainer/variable.py
Labels: cat:document, st:test-and-merge, to-be-backported

#6239 [backport] Update URL of PTB dataset
  chainer/datasets/ptb.py
Labels: backport, cat:document

#5742 add spectral normalization linkhook
  chainer/link_hooks/__init__.py
  chainer/link_hooks/spectral_normalization.py
  docs/source/reference/links.rst
  tests/chainer_tests/link_hooks_tests/test_spectral_normalization.py
Labels: cat:feature

#6231 Write comment about `CHAINERX_VISIBILITY_HIDDEN`
  chainerx_cc/chainerx/macro.h
Labels: ChainerX, cat:code-fix, st:test-and-merge

#6211 Rewrite the tests of `F.average_pooling_2d`
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
Labels: cat:test

#6246 Use float accumulation in ChainerX float16 `Dot`
  chainerx_cc/chainerx/native/native_device/dot.cc
Labels: ChainerX, st:test-and-merge

#6243 Simplify `F.selu` test
  tests/chainer_tests/functions_tests/activation_tests/test_selu.py
Labels: cat:test

#6268 Improve `F.relu` performance with CuPy
  chainer/functions/activation/relu.py
Labels: cat:performance, st:test-and-merge, to-be-backported

#6270 [backport] Improve `F.relu` performance with CuPy
  chainer/functions/activation/relu.py
Labels: backport, cat:performance

#6267 Fix clang-tidy errors
  chainerx_cc/chainerx/array.cc
  chainerx_cc/chainerx/array_repr_test.cc
  chainerx_cc/chainerx/backend.cc
  chainerx_cc/chainerx/backward_builder.h
  chainerx_cc/chainerx/backward_builder_test.cc
  chainerx_cc/chainerx/backward_test.cc
  chainerx_cc/chainerx/check_backward.cc
  chainerx_cc/chainerx/cuda/cuda_backend_test.cc
  chainerx_cc/chainerx/cuda/cuda_conv.cc
  chainerx_cc/chainerx/indexable_array.h
  chainerx_cc/chainerx/native/elementwise.h
  chainerx_cc/chainerx/python/array.cc
  chainerx_cc/chainerx/python/backward.cc
  chainerx_cc/chainerx/python/chainer_interop.cc
  chainerx_cc/chainerx/python/check_backward.cc
  chainerx_cc/chainerx/python/context.cc
  chainerx_cc/chainerx/python/routines.cc
  chainerx_cc/chainerx/python/testing/device_buffer.cc
  chainerx_cc/chainerx/routines/connection.cc
  chainerx_cc/chainerx/routines/manipulation.cc
  chainerx_cc/chainerx/routines/normalization.cc
  chainerx_cc/chainerx/routines/routines_util.h
  chainerx_cc/chainerx/stack_vector.h
  chainerx_cc/chainerx/stack_vector_test.cc
  chainerx_cc/chainerx/testing/array_check.h
  chainerx_cc/chainerx/thread_local_state_test.cc
Labels: cat:code-fix, st:test-and-merge

#6271 Cosmetic fix to `test_gradient_check`
  tests/chainer_tests/test_gradient_check.py
Labels: cat:code-fix

#6264 Avoid `contextmanager` in backprop
  chainer/_backprop_utils.py
Labels: cat:performance, to-be-backported

#6214 Use `_has_chainerx_array` in `Variable`
  chainer/variable.py
Labels: cat:code-fix

#6236 Rewrite linear function test
  tests/chainer_tests/functions_tests/connection_tests/test_linear.py
Labels: cat:test, st:test-and-merge

#6274 Fix inappropriate usage of `is_arrays_compatible`
  chainer/__init__.py
  chainer/links/activation/maxout.py
  chainer/variable.py
Labels: cat:code-fix

#6269 Improve `get_variable` performance
  chainer/variable.py
Labels: cat:performance, st:test-and-merge

#6241 add group option value of Convolution2D to Caffe exporter
  chainer/exporters/caffe.py
  tests/chainer_tests/exporters_tests/test_caffe.py
Labels: cat:enhancement, st:test-and-merge

#6234 Add support for importing and exporting Caffe Sigmoid layer
  chainer/exporters/caffe.py
  chainer/links/caffe/caffe_function.py
  tests/chainer_tests/exporters_tests/test_caffe.py
  tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
Labels: cat:enhancement, st:test-and-merge

#5357 Unify arguments of file names
  chainer/training/extensions/computational_graph.py
  chainer/training/extensions/log_report.py
  chainer/training/extensions/plot_report.py
  chainer/training/extensions/variable_statistics_plot.py
  tests/chainer_tests/training_tests/extensions_tests/test_computational_graph.py
  tests/chainer_tests/training_tests/extensions_tests/test_variable_statistics_plot.py
Labels: cat:enhancement, st:test-and-merge

#6291 Reduce `chainer.is_debug()` overhead
  chainer/__init__.py
  chainer/configuration.py
  chainer/functions/normalization/batch_normalization.py
Labels: cat:performance, st:test-and-merge, to-be-backported

#6281 Support ChainerX TrueDivide for integer types
  chainerx_cc/chainerx/python/routines.cc
  chainerx_cc/chainerx/routines/math.cc
  chainerx_cc/chainerx/routines/math.h
  chainerx_cc/chainerx/routines/math_test.cc
  tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Labels: ChainerX

#6294 [backport] Add support for importing and exporting Caffe Sigmoid layer
  chainer/exporters/caffe.py
  chainer/links/caffe/caffe_function.py
  tests/chainer_tests/exporters_tests/test_caffe.py
  tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
Labels: backport, cat:enhancement

#6293 [backport] add group option value of Convolution2D to Caffe exporter
  chainer/exporters/caffe.py
  tests/chainer_tests/exporters_tests/test_caffe.py
Labels: backport, cat:enhancement

#6288 [backport] Make docs of functions refer `ndarray`
  chainer/functions/activation/rrelu.py
  chainer/functions/loss/vae.py
  chainer/functions/noise/simplified_dropconnect.py
  chainer/functions/pooling/max_pooling_2d.py
  chainer/functions/pooling/max_pooling_nd.py
  chainer/functions/pooling/upsampling_2d.py
  chainer/functions/util/forget.py
Labels: backport, cat:document

#6286 Pass debug flag to `backprop_step`
  chainer/_backprop_utils.py
  chainer/function_node.py
  chainer/variable.py
  tests/chainer_tests/test_backprop_utils.py
Labels: cat:performance

#6284 Unwrap ChainerX connected array from `Variable`
  chainer/variable.py
  tests/chainer_tests/test_variable.py
Labels: cat:feature

#6292 Improve performance of `using_device` for NumPy and Intel64 devices
  chainer/_backend.py
Labels: cat:performance

#6233 skip MultiprocessIterator finalization at exit
  chainer/iterators/multiprocess_iterator.py
Labels: cat:bug

#6278 Make Chainer backprop modes affect ChainerX counterparts
  chainer/function.py
  tests/chainer_tests/test_function_node.py
Labels: cat:enhancement

#6295 add Kuzushiji-MNIST dataset
  README.md
  chainer/datasets/__init__.py
  chainer/datasets/kuzushiji_mnist.py
  docs/source/reference/datasets.rst
  tests/chainer_tests/datasets_tests/test_mnist.py
Labels: cat:feature

#6287 Fix error message of parameterized test
  chainer/testing/parameterized.py
Labels: cat:bug, st:test-and-merge

#6026 Fix warning message for backward on a scalar array
  chainer/variable.py
Labels: cat:bug, to-be-backported

#6297 [backport] Reduce `chainer.is_debug()` overhead
  chainer/__init__.py
  chainer/configuration.py
  chainer/functions/normalization/batch_normalization.py
Labels: backport, cat:performance

#6213 Simplify `_check_grad_type`
  chainer/_backprop_utils.py
  chainer/function.py
  chainer/variable.py
Labels: cat:code-fix

#6308 Remove `PrintReport` entries in seq2seq example
  examples/seq2seq/seq2seq.py
Labels: cat:example, st:test-and-merge, to-be-backported

#6313 Improve accuracy of ChainerX native float16 Sum
  chainerx_cc/chainerx/native/native_device/reduction.cc
Labels: cat:enhancement, st:test-and-merge

#6318 Improve accuracy of test of `F.rrelu`
  tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
Labels: cat:test

#6298 test_softplus : Simplify `F.softplus` test
  tests/chainer_tests/functions_tests/activation_tests/test_softplus.py
Labels: cat:test

#6215 Remove FP16 specific models from imagenet example
  examples/imagenet/README.md
  examples/imagenet/alex.py
  examples/imagenet/dali_util.py
  examples/imagenet/googlenetbn.py
  examples/imagenet/train_imagenet.py
  examples/imagenet/train_imagenet_data_parallel.py
Labels: cat:example, to-be-backported

#5977 Add non-deterministic warning
  chainer/__init__.py
  chainer/configuration.py
  chainer/functions/connection/embed_id.py
  chainer/functions/loss/ctc.py
  chainer/functions/loss/negative_sampling.py
  chainer/functions/math/sparse_matmul.py
  chainer/functions/pooling/roi_average_align_2d.py
  chainer/functions/pooling/roi_average_pooling_2d.py
  chainer/functions/pooling/roi_max_align_2d.py
  chainer/functions/pooling/roi_max_pooling_2d.py
  chainer/links/loss/hierarchical_softmax.py
  chainer/utils/__init__.py
  chainer/utils/nondeterministic.py
  docs/source/reference/configuration.rst
Labels: cat:feature

#5635 support spatial_scale >= 1.0 in roi_max_align_2d.py
  chainer/functions/pooling/roi_max_align_2d.py
  tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_align_2d.py
Labels: domain:cv

#6319 [backport] Fix warning message for backward on a scalar array
  chainer/variable.py
Labels: backport, cat:bug, st:test-and-merge

#6280 Fix to check chainerx device in ImageNet example
  examples/imagenet/train_imagenet.py
Labels: ChainerX, cat:example, st:test-and-merge

#6300 Update docs for Python 3.4 end-of-life
  chainer/utils/type_check.py
  docs/source/install.rst
Labels: cat:document

#6329 Use `utils.size_of_shape` in `F.convolution_nd` and `F.deconvolution_nd`
  chainer/functions/connection/convolution_nd.py
  chainer/functions/connection/deconvolution_nd.py
Labels: cat:code-fix

#6023 Add `finished` property to `once_trigger`
  chainer/training/triggers/once_trigger.py
  tests/chainer_tests/training_tests/triggers_tests/test_once_trigger.py
Labels: cat:feature

#6312 Rename `chainerx` -> `chx` in public API
  chainer/backend.py
  chainer/backends/_chainerx.py
  chainer/function.py
  chainer/function_node.py
  chainer/functions/array/get_item.py
  chainer/functions/array/scatter_add.py
  chainer/functions/array/select_item.py
  chainer/functions/loss/negative_sampling.py
  chainer/functions/loss/softmax_cross_entropy.py
  chainer/functions/math/basic_math.py
  chainer/functions/normalization/batch_normalization.py
  chainer/link.py
  chainer/optimizer.py
  chainer/variable.py
  chainerx/_fallback_workarounds.py
  tests/chainer_tests/backends_tests/test_chainerx.py
  tests/chainer_tests/functions_tests/array_tests/test_stack.py
  tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
  tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
  tests/chainer_tests/functions_tests/loss_tests/test_hinge.py
  tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
  tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
  tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
  tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
  tests/chainer_tests/test_function_node.py
  tests/chainer_tests/test_link.py
  tests/chainer_tests/test_optimizer.py
  tests/chainer_tests/test_variable.py
Labels: st:test-and-merge

#6248 ChainerX test tool for ops
  chainer/testing/function.py
  tests/chainerx_tests/op_utils.py
  tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
  tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Labels: cat:test, st:test-and-merge

#6335 Add `__ne__` in Device for Python 2
  chainer/_backend.py
  tests/chainer_tests/test_backend.py
Labels: ChainerX, cat:bug, st:test-and-merge

#6334 Use Chainer-style parameterization in ChainerX op test
  chainer/testing/__init__.py
  chainer/testing/_bundle.py
  chainer/testing/parameterized.py
  tests/chainerx_tests/op_utils.py
  tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
Labels: cat:test

#6255 Improve errors for disabled `Variable` operators
  chainer/variable.py
  tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
  tests/chainer_tests/test_variable.py
Labels: cat:enhancement, st:test-and-merge

#6345 Add Synchronized Iterator (Rebased version of #5396)
  chainermn/iterators/__init__.py
  chainermn/iterators/synchronized_iterator.py
  docs/source/chainermn/reference/index.rst
  tests/chainermn_tests/iterators_tests/test_iterator_compatibility.py
  tests/chainermn_tests/iterators_tests/test_synchronized_iterator.py
Labels: ChainerMN, cat:feature

#6342 Fix dali_util in imagenet example for fp16
  examples/imagenet/dali_util.py
Labels: cat:example, to-be-backported

#6321 [backport] Remove `PrintReport` entries in seq2seq example
  examples/seq2seq/seq2seq.py
Labels: backport, cat:example

#6355 [backport] Avoid `# NOQA` in docstrings
  chainer/datasets/svhn.py
  chainer/functions/connection/convolution_2d.py
  chainer/functions/connection/deconvolution_2d.py
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_rnn.py
  chainer/links/connection/convolution_2d.py
  chainer/links/connection/convolution_nd.py
  chainer/links/connection/deconvolution_2d.py
  chainer/links/connection/deconvolution_nd.py
  chainer/links/connection/mlp_convolution_2d.py
  chainer/variable.py
Labels: backport, cat:document, st:test-and-merge

#6328 Fix ChainerMN Step-by-Step Troubleshooting
  docs/source/chainermn/installation/troubleshooting.rst
Labels: ChainerMN

#6245 add create_mnbn_model
  chainermn/links/__init__.py
  chainermn/links/create_mnbn_model.py
  tests/chainermn_tests/links_tests/test_create_mnbn_model.py
Labels: ChainerMN

#6347 ResultType
  chainerx_cc/chainerx/routines/CMakeLists.txt
  chainerx_cc/chainerx/routines/type_util.h
  chainerx_cc/chainerx/routines/type_util_test.cc
  chainerx_cc/scripts/run-clang-tidy.sh
Labels: cat:feature, st:test-and-merge

#6290 Improve performance of `using_config`
  chainer/configuration.py
Labels: cat:performance

#6354 Document ChainerX op test tool
  tests/chainerx_tests/op_utils.py
Labels: st:test-and-merge

#6360 Add chainermn.links.create_mnbn_model document
  docs/source/chainermn/reference/index.rst
Labels: ChainerMN, cat:document

#6358 Simplify `_array_to_gpu` with stream argument
  chainer/backends/cuda.py
Labels: cat:code-fix

#6361 Write test types in Travis CI job names
  .travis.yml
Labels: cat:test

#6382 Bump version number to v5.3.0
  chainer/_version.py
  docker/intel/python2/Dockerfile
  docker/intel/python3/Dockerfile
  docker/python2/Dockerfile
  docker/python3/Dockerfile
  setup.py
Labels: cat:other

#6350 Add ChainerX `FloorDivide`
  chainerx_cc/chainerx/cuda/cuda_device.h
  chainerx_cc/chainerx/cuda/cuda_device/arithmetic.cu
  chainerx_cc/chainerx/cuda/float16.cuh
  chainerx_cc/chainerx/device.h
  chainerx_cc/chainerx/native/native_device.h
  chainerx_cc/chainerx/native/native_device/arithmetic.cc
  chainerx_cc/chainerx/python/array.cc
  chainerx_cc/chainerx/python/routines.cc
  chainerx_cc/chainerx/routines/math.cc
  chainerx_cc/chainerx/routines/math.h
  chainerx_cc/chainerx/routines/math_test.cc
  tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Labels: ChainerX, cat:feature, st:test-and-merge

#6365 Fix error messages in `get_fans`
  chainer/initializer.py
Labels: cat:enhancement, st:test-and-merge

#6364 Set `requires_grad` explicitly in `gradient_check` and function test
  chainer/gradient_check.py
  chainer/testing/function.py
Labels: cat:enhancement, st:test-and-merge
