Repository chainer/chainer, pull requests merged in 2020-01, with the labels that each got.

#8527 Remove '--pre' from 'pip install' commands in ChainerX installation document
  docs/source/chainerx/install/index.rst
Labels: cat:document

#8454 Fix several documentation errors in chainer.functions.rnn.*
  chainer/functions/rnn/n_step_gru.py
  chainer/functions/rnn/n_step_lstm.py
  chainer/functions/rnn/n_step_rnn.py
Labels: cat:document, to-be-backported

#8526 Fix typo: chainermn.extension -> chainermn.extensions
  chainermn/extensions/checkpoint.py
Labels: ChainerMN, cat:document

#8523 [backport] Use `FunctionTestCase` to test `F.decov`
  tests/chainer_tests/functions_tests/loss_tests/test_decov.py
Labels: backport, cat:test

#8530 [backport] Fix several documentation errors in chainer.functions.rnn.*
  chainer/functions/connection/n_step_gru.py
  chainer/functions/connection/n_step_lstm.py
  chainer/functions/connection/n_step_rnn.py
Labels: backport, cat:document

#8187 Fix `CooMatrix.to_dense` for duplicate indices
  chainer/utils/sparse.py
  tests/chainer_tests/utils_tests/test_sparse.py
Labels: cat:bug

#8517 Do not install chainer>=7.0.0 in python2
  setup.py
Labels: cat:install, st:test-and-merge

#8536 Remove trailing whitespaces
  chainer/exporters/caffe.py
  chainer/function_node.py
  chainer/functions/array/tile.py
  chainer/testing/array.py
  chainermn/global_except_hook.py
  examples/chainermn/imagenet/train_imagenet.py
  tests/chainermn_tests/communicator_tests/test_mpi.py
Labels: cat:enhancement, st:test-and-merge

#8539 Bump version to v6.7.0
  chainer/_version.py
  docker/intel/python2/Dockerfile
  docker/intel/python3/Dockerfile
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#8534 Fix accuracy calculation of custom loop examples
  examples/cifar/train_cifar_custom_loop.py
  examples/mnist/train_mnist_custom_loop.py
  examples/static_graph_optimizations/cifar/train_cifar_custom_loop.py
  examples/static_graph_optimizations/mnist/train_mnist_custom_loop.py
Labels: cat:example

#8537 Add Optuna to README.md
  README.md
Labels: cat:document, st:test-and-merge
