Repository chainer/chainer, pull requests merged in 2020-04, with the labels that each got.

#8554 Use CuPy v7 in CI
  .pfnci/script.sh
Labels: cat:test, st:test-and-merge

#8043 Fix `backend.copyto` for mismatched dtypes to CuPy ndarray
  chainer/backend.py
  tests/chainer_tests/test_backend.py
Labels: cat:bug, st:test-and-merge

#8553 Fix local_convolution_2d result shape documentation
  chainer/functions/connection/local_convolution_2d.py
Labels: cat:document, st:test-and-merge

#8382 Fix `optimizer.use_fp32_update` on ChainerX model
  chainer/optimizer.py
Labels: cat:bug, st:test-and-merge

#8557 Update functions.rst
  docs/source/guides/functions.rst
Labels: cat:document, st:test-and-merge

#8559 Bump version to v7.4.0
  chainer/_version.py
  docker/intel/python3/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other
