Repository chainer/chainer, pull requests merged in 2020-07, with the labels that each got.

#8572 Update Twitter ID
  README.md
Labels: cat:other

#8574 Install CuPy v7 for ChainerX Jenkins tests
  scripts/ci/chainerx/jenkins/Dockerfile.template
Labels: cat:test, st:test-and-merge

#8568 Fix array indexing in `create_multi_node_evaluator`
  chainermn/extensions/multi_node_evaluator.py
Labels: ChainerMN
