Repository chainer/chainer, pull requests merged in 2020-12, with the labels that each got.

#8589 Ignore CuPy deprecation warnings in tests
  setup.cfg
Labels: cat:test, prio:high

#8590 Support importing cuDNN in CuPy v8
  chainer/backends/cuda.py
Labels: cat:enhancement, prio:high

#8591 Use Python 3.7 in ReadTheDocs
  docs/rtd_conda.yml
  readthedocs.yml
Labels: cat:test, prio:high

#8585 Update `[jenkins]` requirement
  setup.py
Labels: cat:test, st:test-and-merge

#8592 Use stable CuPy v7 in ONNX test
  onnx_chainer/.flexci/README.md
  onnx_chainer/.flexci/run_test.bat
  onnx_chainer/.flexci/run_test.sh
Labels: cat:test, prio:high

#8588 Add CHAINER_WARN_VERSION_MISMATCH environment variable
  chainer/_environment_check.py
Labels: cat:enhancement

#8595 docs: fix simple typo, cotiguousness -> contiguousness
  tests/chainer_tests/testing_tests/test_function_link.py
Labels: cat:document
