Repository chainer/chainer, pull requests merged in 2020-02, with the labels that each got.

#8325 Calculate `beta` with `static_code` on `F.BatchNormalization.forward`
  chainer/links/normalization/batch_normalization.py
  tests/chainer_tests/graph_optimization_tests/test_static_graph_models.py
Labels: cat:bug, st:test-and-merge

#7956 Remove stable version section from README
  README.md
Labels: cat:document, st:test-and-merge

#8541 Fix typo
  chainer/functions/loss/decov.py
Labels: cat:document, st:test-and-merge

#8542 Remove py2 warnings
  chainer/_environment_check.py
Labels: cat:code-fix, st:test-and-merge

#8544 Add cupy-cuda102
  chainer/_version.py
Labels: cat:feature
