Repository chainer/chainer, pull requests merged in 2021-06, with the labels that each got.

#8605 Import cupy.cuda.cudnn first to show preload warning
  chainer/backends/cuda.py
Labels: cat:code-fix

#8609 Add recent cupy packages
  chainer/_version.py
Labels: cat:install

#8610 Fix debug print tests
  tests/chainer_tests/function_hooks_tests/test_debug_print.py
  tests/chainer_tests/test_variable.py
Labels: cat:test

#8608 Add cupy version recommendation
  docs/source/install.rst
Labels: cat:document

#8606 Fix random for CuPy v8/v9
  chainer/testing/random.py
Labels: cat:code-fix

#8607 Fix broken `skip` condition
  tests/chainer_tests/test_init.py
Labels: cat:test

#8611 Fix `chainer.testing` requring pytest installed
  chainer/testing/condition.py
Labels: cat:bug

#8612 Bump chainer version to 7.8.0
  chainer/_version.py
Labels: cat:install, prio:high

#8613 Bump Dockerfiles to v.7.8.0
  docker/intel/python3/Dockerfile
  docker/python3/Dockerfile
Labels: cat:install, prio:high
